### ISSUE TITLE
Automation tree rules exit option

### ISSUE THREAD

**Issue by g1augusto** [Cacti/cacti#1004]
I would like to request an exit function under the **Tree Creation Criteria** and restrict it running a subquery after the initial matching of Object Selection Criteria

This would be an improvement in a scenario like what I am managing where I wish to have a tree where each node is a folder named after a site name and each subfolder of each site would be categorized for the device typology, example: 

- Site name
  - Core Devices
  - Access Switches
  - Server Switches

Problem is that I am matching a hostname description regex pattern to get in list ALL devices for a single site :

SiteCode(GW\|CORE\|SW).*

and subsequentially I apply the creation (or insertion) in the appropriate subtree by the **Tree Creation Criteria** Example:

![image](https://user-images.githubusercontent.com/26431888/30960064-3730c72e-a442-11e7-8a47-d767c755ea3c.png)
 

but I noticed that changes are affecting also items that are not matched by the regex, in this example the first two entries are a match but also the creation applies for the other 2 entries.

![image](https://user-images.githubusercontent.com/26431888/30960227-b18c16b8-a442-11e7-9ce8-8ca960de80c4.png)

With the current operation, the only viable way is to restrict the **Object Selection Criteria** and create multiple entries ,precisely an entry for each device type/subfolder for EACH site...we have 56 sites for 8 device types = 448 rules (!!!) oO

**Comment by cigamit** [comment]
In the 1.2 branch, we are going to add a 'Site Tree' branch option.  As a part of that feature, we will be adding a 'location' column to the database.  That could equate to 'Closet Such and Such', 'Rack1Enclosure2', etc.

Then we will allow you to Place a site on a tree and from there, we will have drill downs by Graph Template, Location, Device Templates, and Host.  But now to think of it, I think we need two new columns, Device Type, and Device Location, as things like Access Switches will be different than, for example a 'Cisco 3750' Device Template.

Would that be a sufficient longer term workaround.  I'm seeking comment as this work will likely be finished in about 3 weeks and comments on the design are relevant at the moment.

As far as the exit function is concerned, I would also be interested in how you would expect that to work from the GUI.  Please take a screen shot of your Cacti GUI and mark it up with how that might look and post it to this ticket.

**Comment by jhonnyx82** [comment]
Hi, Thanks for looking into this.

Let me give you an overview of what it is I build as tree structure for our sites:

![image](https://user-images.githubusercontent.com/26431888/31518688-59b327ba-afa0-11e7-8b96-1ce2754dbcd8.png)

Each site belongs to a Region and first half of the hostname is a reference of its location:

- Region
  - Country
    - Site

Second half of the hostname refers to which device is and what is the role, example : 

- Switch
  - Core
  - Distribution
  - Access
  - Server 
  - DMZ 
  - etc

- Router
  - Wan
  - IP SLA
  - etc

Now, at least for us this is a repetitive structure, and what really changes and should locate the site node is the first part of the hostname, ideally I would have a site subset of the initial query for that specific site and insert (eventually also create) into the relative subfolder based on regex matches of the second half of the hostname from the site subset : Access Switch, Core, etc

Currently this is not possible for the only reason that from the site subset extracted by the initial tree maching rule, every other additional maching rule applies to all the subset, example:

How I would have it : 


All Devices:
- Site1Core01
- Site1Switch01
- Site1Router01
- Site2Core01
- Site2Switch01
- Site2Router01

```
Tree rule : Site1
Object Selection Criteria : 
Site1.*  --> Region1 - Site1

Tree Creation Criteria : 
1) .*Router.*  --> Routers (Region1 - Site1 - Routers)
2) .*Core.*  --> Cores (Region1 - Site1 - Cores)
3) .*Switch.*  --> Switches (Region1 - Site1 - Switches)
```

Resulting tree:

- Region 1
  - Site1
    - Cores
      - Site1Core01
    - Switches
      - Site1Switch01
    - Routers
      - Site1Router01


How is it today with the same rule:

- Region 1
  - Site1
    - Site1Core01
    - Site1Switch01
    - Cores
    - Switches
    - Routers
      - Site1Router01

This because the first rule of the **tree creation criteria** affect ALL the subset extracted by **Object Selection Criteria**



So the exit function may even not be necessary if the logic will be changed in the current automation for tree creation and insertion, as I mentioned the idea of an exit function could be coupled with the scope of the **tree creation criteria** rules, if inclusive (so means applied to ALL the subset) or exclusive (so applied only to what that specific regex matches from the  **Object Selection Criteria** subset and not modifying the rest)

**Comment by cigamit** [comment]
Well, let me take you comments and adopt into the plan.  More to follow.

**Comment by TheWitness** [comment]
Related to #412.  I think this is resolved now.  You may want to spend some time reviewing the changes in the develop branch.

Essentially, for automation now, you add the Tree rules to the Device rules.  If you have more than one tree rule, you order the way you would like to, and there is an exit option after the first matching rule if found and the tree's are created/modified.
