### ISSUE TITLE
Reflected XSS in 1.1.27

### ISSUE THREAD

**Issue by cibvetr2** [Cacti/cacti#1071]
We (worlak2 and cibvetr2) found Reflected XSS vuln in last version 1.1.27.(For example we found in Google host with last version of cacti)  
PoC
1)_http://128.65.97.6/host.php/gahv8'-alert(document.domain)-'w6vt7??host_status=-1&host_template_id=-1&site_id=-1&poller_id=-1&rows=-1&filter=&_
![default](https://user-images.githubusercontent.com/33294474/32657029-c086b972-c646-11e7-9266-ffe9f2f48a8b.png)

With regards worlak2 and cibvetr2

**Comment by cigamit** [comment]
Can you please confirm this against the current develop branch?  I can not reproduce using your example.

**Comment by cibvetr2** [comment]
Yes we tested this on local version 
1)If you not login
![default](https://user-images.githubusercontent.com/33294474/32686593-25a6fe1e-c6da-11e7-8095-093d201b3371.png)
2) If you login 
![default](https://user-images.githubusercontent.com/33294474/32686603-80e7f120-c6da-11e7-877f-97df42ccf6a3.png)
we use version from https://www.cacti.net/downloads/cacti-latest.zip

**Comment by carnil** [comment]
This issue was assigned CVE-2017-16785

**Comment by cigamit** [comment]
I don't believe you understood me correctly.  Please test with the latest develop branch.  I believe this problem has already been solved and is a duplicate of another issue that was resolved recently and finally in this issue https://github.com/Cacti/cacti/commit/e21919937ff5803aeca40915d24ead378f3e432b.

Therefore, I will mark unable to reproduce until you are able to attempt to reproduce with the latest develop branch.  If you find you can not reproduce, we can make it closed and update the change record since we have the CVE to deal with.  Please advise.

**Comment by worlak2** [comment]
We thought that the latest version. 1.1.27 and it's on github 1.1.28 and the site is still old
Therefore, the problem is fixed in 1.1.2. Please update the information on the website

**Comment by ronytomen** [comment]
1.1.28 has not been released and that is why it does not appear as a download.  It's under active development.

1.2.x is a feature branch for later release.

**Comment by cigamit** [comment]
We are enhancing the fix to the issue linked below in 1.1.28.  Also, per ronytomen, I don't believe you understood me correctly.  Please test with the latest develop branch.  I believe this problem has already been solved and is a duplicate of another issue that was resolved recently and finally in this issue https://github.com/Cacti/cacti/commit/e21919937ff5803aeca40915d24ead378f3e432b.

Therefore, I will mark unable to reproduce until you are able to attempt to reproduce with the latest develop branch.  If you find you can not reproduce, we can make it closed and update the change record since we have the CVE to deal with.  Please advise.

**Comment by cibvetr2** [comment]
yes in 1.1.28 it's problem fixed

**Comment by cigamit** [comment]
Thanks for confirming.  Marking resolved in changelog and closing.

**Comment by paulgevers** [comment]
I think this is a duplicate of CVE-2017-15194 / issue #1010, or if not, one could consider this a reintroduction of it in commit 054aa82d, as discussed in the comments there.
