### ISSUE TITLE
Opening graph links by unlogged user - validation error

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#1109]
1. Be Logout from cacti.
2. Open https://cacti/graph_view.php?action=preview&reset=1&host_id=510
3. You will be redirected to login page so please login.
4. You receive an error 
`Validation error for variable host_id with a value of 510?newtheme=1. See backtrace below for more details.
(/graph_view.php: 325 html_graph_validate_preview_request_vars)(/lib/html_graph.php: 142 validate_store_request_vars)(/lib/html_utility.php: 651 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)`
5. You need to refresh to see the graph.

**Comment by netniV** [comment]
I think I found the issue as there are only two places where the header is redirected with **newtheme=** that isn't part of a hard coded link.  The first is using the &amp; symbol so it can't be that, the other is using the $referer string but doesn't check if it already contains the ? character.  My fix is to change auth_login.php's code of:

`header("Location: $referer" . ($newtheme ? '?newtheme=1':''));`

So that it checks the $referer string for an ? symbol and if it finds it, uses the &amp; symbol instead:

```
$param_char = "?";
if (substr_count($referer,"?")) {
	$param_char = "&";
}
header("Location: $referer" . ($newtheme ? $param_char . 'newtheme=1':''));
```

**Comment by netniV** [comment]
If you could make that change manually, I will submit a pull request once verified.

**Comment by interduo** [comment]
Cannot do this today.
I will do this as early as monday morning starts. ;/

**Comment by netniV** [comment]
https://github.com/netniV/cacti/commit/0dee1026ac860e34802436bdff199dd5cdba2af7 Is the change I made in my local copy.  It is no doubt part of the same #1107 pull request.

**Comment by netniV** [comment]
Created a pull request of #1115 which separates out the previous #1107 pull request into individual components.

**Comment by cigamit** [comment]
Marking resolved.  Thanks for reporting and helping all.

**Comment by interduo** [comment]
This is resolved properly. Thanks!
