### ISSUE TITLE
Field user_auth.locked seems to be incorrect

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1123]
user_auth.locked is defined as a varchar(3), yet its contents always seem to be a number.  Should this be changed to an integer ?  

Once a user is locked, there seems to be no way to unlock without a manual database clearing since untick the locked flag seems to do nothing.  Setting to any value apart from empty, also forces the account to be locked.

**Comment by cigamit** [comment]
Locked is a varchar for a reason.  It is a checkbox, which in our form logic will have a value of 'on' for checked and '' if not.  Please tell me where in the code that it is set to 1 or 0?  It should be blank when unlocked.  Please review lib/auth.php for more specifics on the secpass process.

**Comment by netniV** [comment]
I will give you an update on that on Monday. But I saw a value of 3 which made me think it was an integer in the first place. There are some other fixes to that function I’m going to propose.

**Comment by cigamit** [comment]
Sure.  I'm trying to focus on 1.2 starting in mid December.  There are some desperately needed changes that need to be finished for some real large installs and we want to have that release ready by the new year.

**Comment by netniV** [comment]
Can you do me a favour? It's probably in the source somewhere but I can't find it.  Can you get me the definition of the user_auth table, until I modified something, it was failing to replace the "enabled", "locked" columns with the changed value.

Mine is:

```
show create table `user_auth`\G;
*************************** 1. row ***************************
       Table: user_auth
Create Table: CREATE TABLE `user_auth` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL DEFAULT '0',
  `password` varchar(2048) NOT NULL DEFAULT '',
  `realm` mediumint(8) NOT NULL DEFAULT '0',
  `full_name` varchar(100) DEFAULT '0',
  `email_address` varchar(128) DEFAULT NULL,
  `must_change_password` char(2) DEFAULT NULL,
  `password_change` char(2) DEFAULT 'on',
  `show_tree` char(2) DEFAULT 'on',
  `show_list` char(2) DEFAULT 'on',
  `show_preview` char(2) NOT NULL DEFAULT 'on',
  `graph_settings` char(2) DEFAULT NULL,
  `login_opts` tinyint(1) NOT NULL DEFAULT '1',
  `policy_graphs` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `policy_trees` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `policy_hosts` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `policy_graph_templates` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `enabled` char(2) NOT NULL DEFAULT 'on',
  `lastchange` int(12) NOT NULL DEFAULT '-1',
  `lastlogin` int(12) NOT NULL DEFAULT '-1',
  `password_history` varchar(4096) NOT NULL DEFAULT '-1',
  `locked` varchar(3) NOT NULL DEFAULT '',
  `failed_attempts` int(5) NOT NULL DEFAULT '0',
  `lastfail` int(12) NOT NULL DEFAULT '0',
  `reset_perms` int(12) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `realm` (`realm`),
  KEY `enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1
1 row in set (0.01 sec)
```

I changed the columns because I noticed that enabled/locked which were giving me a problem where both varchar(3) with not null.  Whereas, must_change_password was just a char(2) with null.  I am a bit confused though as you said that the checkbox must be a char value, yet policy_xxx columns are tinyint's?

**Comment by cigamit** [comment]
The ERD and Data Dictionaries are both in desperate need of updating.  It's more than a decade old.  It's not something I have time for at the moment, but I'll shorthand it here:

*  id - A unique id per user
*  username - The users username
*  password - The md5 or php strong encoded password
*  realm - The login type local, ldap, web basic, multiple domains
*  full_name - The users full name
*  email_address - The users email address
*  must_change_password - 'On' indicates that the user must change their password at the next login
*  password_change - 'On' means that the user can change their password
*  show_tree - Permission to the graph tree page
*  show_list - Permission to the graph list page
*  show_preview - Permission to the graph preview page
*  graph_settings - 'On' means that the user can change their graph/user settings
*  login_opts - The default location to direct the user at login 
*  policy_graphs - By default does the user have access to all graphs or none
*  policy_trees - By default does the user have access to all trees or none
*  policy_hosts - By default does the user have access to all hosts or none
*  policy_graph_templates - By default does the user have access to all graph templates or none
*  enabled - 'On' is for an enabled user
*  lastchange - The UNIX timestamp, stored as an integer, of the users last password change
*  lastlogin - The UNIX timestamp, stored as an integer, of the users last login
*  password_history - A spaced delimited list of encoded last passwords for the user
*  locked - 'On' if the user is locked from their account
*  failed_attempts - The number of failed attempts since the last successful login
*  lastfail - The UNIX timestamp, stored as an integer, of the last failed login attempt
*  reset_perms - 'On' if the user, who is logged in should clear their session of user settings.  Used as a global refresh you settings.

**Comment by netniV** [comment]
I was trying to debug the issue I had because the locked/enabled flags were not removing.  However, I see that I was looking at the wrong fields (policy_ instead of show_) as the correct ones are also char(2) with default, where locked/enabled are varchar(3) with a default value and not null.

Could you get me the output of `SHOW CREATE TABLE `user_auth`\G;` so that I can check my setup again?

**Comment by cigamit** [comment]
It should be in the cacti.sql.

**Comment by netniV** [comment]
Yes, I have since found that file but I haven't had a chance to compare :)

**Comment by netniV** [comment]
Turns out that "locked" was introduced in 1.0.0 (see install/upgrades/1_0_0.php) and has always been varchar(3).  I will see if I can get my issue to present itself again otherwise I may just abandon this in the new year.
