### ISSUE TITLE
Cacti 1.1.28 - Import Template doesn't work

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1136]
![image](https://user-images.githubusercontent.com/17400240/33939527-9fa05d4a-e01c-11e7-990f-50847bb12ded.png)

**Comment by pautiina** [comment]
@Izmenoff  I think it's double for https://github.com/Cacti/cacti/issues/1133

**Comment by netniV** [comment]
Hi @Izmenoff - Firstly, this could be a double of #1133 as @pautiina has suggested, but you haven't actually explained what your problem is or provided any logs that show the issue?

Could you read through the #1133 issue and if possible provide that information if it is the same? It would help both @Kallyx and I to diagnose the issue.

**Comment by cigamit** [comment]
Closing due to no feedback.
