### ISSUE TITLE
Aggregate Graphs can not include some classes of COMMENT

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1200]
Since the comments in the aggregated graphs are disabled as an enhancement, Is there any way to re enable it?

https://github.com/Cacti/cacti/issues/1173

**Comment by cigamit** [comment]
Well, it would be something that you would want on the bottom of a graph or graphs.  I'm expecting its just comments right?  What other examples.

**Comment by chathurag** [comment]
I just need to get the Total In & Total Out Values to be added to the aggregated graphs as mentioned in issue #1173

**Comment by cigamit** [comment]
Okay, perfect.  There may have been some assumptions on that comment type before.  I have an idea though.

**Comment by chathurag** [comment]
Is this feature will be enabled on next update so we can have Total In & Out (comments) on aggregates?

**Comment by cigamit** [comment]
It will not be in 1.1.32, no.  It's something that, unless we get a pull request from others, will be prioritized as time permits.  Right now, the aggregate component is not at the top of the list.  There are other more pressing matters.

**Comment by chathurag** [comment]
Please let me know when this is re enabled

**Comment by chathurag** [comment]
Would like to know the status of this issue

**Comment by cigamit** [comment]
Sorry, I've been busy.  Would you be willing to take a crack at creating a pull request?

**Comment by chathurag** [comment]
Could please check the possibility of having this feature enabled in next version as this is reported a long time ago. This was there in previous cacti versions but disabled later

**Comment by cigamit** [comment]
You should take a crack at fixing it.  We need all the help we can get at this point.  There is only so much time in the day and we need more developers.

**Comment by netniV** [comment]
Actually, development mans to develop.  Sometimes that means adding features, other times if a feature is causing too many problems it may be removed for safety.  Either way, it's still a development.  And just because disabling it takes a few minutes, it shouldn't just be re-enabled without thought to the consequences and proper implementation.  

All of that takes time and whilst we are trying to get through what we can in our spare time, but that is why we do ask if others have the time/patient/energy to create a patch it helps out, even if it's only a starting point on the road to what becomes the final piece of the jigsaw.  I've had many patches that whilst heading the right direction, don't ultimately get merged as a different way was implemented.

If you are unwilling or unable to do the work, then you'll have to be patient and wait to see who else can.

**Comment by cigamit** [comment]
This issue is resolved.  You can backport this change to 1.1.38 without issue.

**Comment by chathurag** [comment]
@cigamit -  on 1.1.38 can select comment on total
But total does not show the accurate value. Check the attached image.
![cacti](https://user-images.githubusercontent.com/35136010/39465269-0c1bc500-4d40-11e8-9e56-f463ae331ebc.png)
