### ISSUE TITLE
When editing a CDEF item, changing the type switches from EDIT to CREATE

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1210]
If you are editing a CDEF, and use the wrong order of items, you are unable to simply correct the issue by changing the types whilst editing an item as it switches to create mode (button also changes from save to create).

Eg, you create a CDEF, 
1. Special Data Source, Current
2. Operator *
3. String 8

Then realise, actually 2 and 3 are the wrong way around, so you click on Item 2 and try to change that to String, but it now creates a new item and if you aren't paying attention you end up with 

1. Special Data Source, Current
2. Operator *
3. String 8
4. String 8

**Comment by cigamit** [comment]
Oh my, that's some old code that slipped through the cracks.  Both CDEF and VDEF were based upon each other, so I reviewed the VDEF code and found the same issue.  There was some i18n missing too.  Ugly stuff.  Need to open a new bug since this interface does not use the form API and therefore will not work well on a mobile device.

**Comment by cigamit** [comment]
Logged #1211 to cover this change.
