### ISSUE TITLE
Language support does not support localization properly

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1250]
Currently, cacti sets the 'country' of the language based on the 'locale' code only (ie, 'en').  This is not correct, since there can be many country codes for one locale, for example Arabic has 16, English has 14, and Chinese has 5.  

I went to see about adding en-GB as a language so that we could have correct localisation for the UK, but found that because of the above, we would always be forced into the "usa" mode.

**Comment by snsupersharp** [comment]
As chinese , I see the warning

RRDtool say:
Fontconfig warning: ignoring zh-cn_CN.UTF-8: not a valid language tag

change lib/rrd.php ,it will be ok.so zh-cn.UTF-8 is the right language tag


function rrdtool_set_language($lang = -1) {
	global $prev_lang;

	$prev_lang = getenv('LANG');

	if ($lang == -1) {
		// putenv('LANG=' . CACTI_LOCALE . '_' . strtoupper(CACTI_COUNTRY) . '.UTF-8');
		putenv('LANG=' . CACTI_LOCALE . '.UTF-8');
	} else {
		putenv('LANG=en_EN.UTF-8');
	}
}

**Comment by cigamit** [comment]
This is kind of sick, but if you review the $lang2local array in include/global_languages.php, @browniebraun has treated the country as the localization rather than it being in fact the country.  The notations for the various Chinese localities was a typo in the file.  Now that it's corrected, it more closely matches the output of:

`localectl list-locales | grep -i utf8 | grep -v "@"`

I'm assuming the the OS is able to differentiate between 'utf8' and 'UTF-8'.  @snsupersharp can you please verify?

**Comment by cigamit** [comment]
This should be resolved now.  Need @snsupersharp to confirm if you are still up.

**Comment by cigamit** [comment]
This is resolved now.
