### ISSUE TITLE
How to Upgrade Cacti form 1.1.31 to 1.1.33 

### ISSUE THREAD

**Issue by gaojianberkeley** [Cacti/cacti#1255]
How to Upgrade Cacti form 1.1.31 to 1.1.33 and keep the old data is nesessary,
please tell me the method Thank you very much!

**Comment by netniV** [comment]
I find the best way to upgrade is to use `git` to update between releases on the master branch.  As you already have a directory with the website in, you need to do the initial clone to a different directory.  So if your website was at /var/www/html/cacti I would first do the following:
```
git clone https://github.com/cacti/cacti -b master /tmp/cacti
cp -R /tmp/cacti/ /var/www/html/cacti/
```

Then on future upgrades, you just type
```
cd /var/www/html/cacti/
git pull
```
It's that simple.  This last command basically fetches the latest source control data, and merges in to your local files.  As long as you never modify the sources that are pulled down, you should have no issues with the updates coming through.  You can check that at any point but it's best to do it before the pull by doing the following:
```
cd /var/www/html/cacti/
git status
```
This will any modified files, plus any untracked changes.  Untracked changes are files that are not part of the source control so are flagged in case they need adding (you won't need to do so).  Any modified files can be reverted by using `git checkout <filename>` although you may want to use `git diff <filename>` to see why you changed it in the first place.

Others prefer to download the source from the [releases](https://github.com/Cacti/cacti/releases) section of GitHub and do the copy without using git.  This is the same as using the git clone but without the advantage of verifying that all the sources are unmodified.

Whenever you copy the files and an upgrade occurs, cacti will attempt to verify that all folder permissions are as required.  Go through the installation steps (which are shorter on an upgrade) and then you should be ready to go.  

ALWAYS browse to your cacti site as quickly as possible after upgrading the sources via git or cp.  This is because there are sometimes database changes that are needed to be done by the installer which can cause errors to appear before that point.

**Comment by netniV** [comment]
Updated my notes above to allow for checking out to a specific release rather than the latest development version.

**Comment by ginesgb** [comment]
Hello, he performs all the steps that indicate but he always gives me the error in this step. 
 git pull
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
Greetings and thank you
