### ISSUE TITLE
PHP ERROR NOTICE Backtrace after Upgrade to 1.1.33

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#1256]
2018/01/23 11:47:19 - WEBUI ERROR: Cacti Error Message Id 'custom_error' Not Defined

2018/01/23 11:47:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php:  39 clog_view_logfile)(/lib/clog_webapi.php: 320  bottom_footer)(/lib/functions.php: 3443  display_messages)(/lib/functions.php: 3464  display_output_messages)(/lib/functions.php: 462  is_error_message)(/lib/functions.php: 434  CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)

2018/01/23 11:47:19 - ERROR PHP NOTICE: Undefined index:  custom_error in file: /srv/www/cacti/lib/functions.php  on line: 434

**Comment by pautiina** [comment]
I don't have this error.
Try clean your browser cache.

**Comment by netniV** [comment]
No point clearing the browser cache. This is an error that can occur I think mostly during authentication.  It's one that I have picked up on but not corrected yet.  It happens because the base messages are setting an array, but there's a custom message that is being set causing the array to become a string instead.  Then when another message tries to set a custom message, it's trying to use the 'custom_message' index on a string which only expects integers for character positions, ie:

```
$works = array();
$works[0] = 'message 0'
$works[1] = 'message 1'
$works['custom'] = 'custom'
```
But when it fails, it's because the array either isn't there, or it's been set to a string already
```
$fails1 = null;
$fails1['custom'] = 'custom message';

$fails2 = "my string";
$fails2['custom'] = 'custom message';
```

**Comment by netniV** [comment]
Oh and this error has actually been around since 1.1.28 or 1.1.29 (I forget which).

**Comment by DavidLiedke** [comment]
I checked my logfiles from the last days. I get this error only with version 1.1.33.

**Comment by netniV** [comment]
I've been having it for a while.  However, I will be combining my logs and yours to try and track it down further.

**Comment by netniV** [comment]
This should be corrected with the patch above.  Can you give it a try and see what your results are?

**Comment by cigamit** [comment]
Thanks for all the good work netniV!  Closing.  To be part of 1.1.34.
