### ISSUE TITLE
cacti.sql does not appear to be up to date for all tables

### ISSUE THREAD

**Issue by HomeServ** [Cacti/cacti#1258]
> CMDPHP PHP ERROR NOTICE Backtrace: (/automation_snmp.php: 89 automation_snmp_edit)(/automation_snmp.php: 656 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
> ERROR PHP NOTICE: Undefined index: snmp_community in file: /opt/cacti/automation_snmp.php  on line: 656

snmp_community isn't a column in the automation_snmp_items table.
There is, however, a snmp_readstring column.

**Comment by netniV** [comment]
Your `automation_snmp_items` table should have a column called `snmp_community`:

```
show create table automation_snmp_items \G;
*************************** 1. row ***************************
       Table: automation_snmp_items
Create Table: CREATE TABLE `automation_snmp_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `snmp_id` int(10) unsigned NOT NULL DEFAULT '0',
  `sequence` int(10) unsigned NOT NULL DEFAULT '0',
  `snmp_version` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `snmp_community` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `snmp_port` int(10) NOT NULL DEFAULT '161',
  `snmp_timeout` int(10) unsigned NOT NULL DEFAULT '500',
  `snmp_retries` tinyint(11) unsigned NOT NULL DEFAULT '3',
  `max_oids` int(12) unsigned DEFAULT '10',
  `snmp_username` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snmp_password` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snmp_auth_protocol` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `snmp_priv_passphrase` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `snmp_priv_protocol` char(6) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `snmp_context` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `snmp_engine_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`id`,`snmp_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Set of SNMP Options'
1 row in set (0.02 sec)
```

**Comment by netniV** [comment]
For reference, this table was added to the base code as part of the v1.0.0 upgrade.

**Comment by HomeServ** [comment]
I've just setup a new server with a fresh cacti clone from github.

cacti.sql;

>CREATE TABLE `automation_snmp_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `snmp_id` int(10) unsigned NOT NULL DEFAULT '0',
  `sequence` int(10) unsigned NOT NULL DEFAULT '0',
  `snmp_version` varchar(100) NOT NULL DEFAULT '',
  `snmp_readstring` varchar(100) NOT NULL,
  `snmp_port` int(10) NOT NULL DEFAULT '161',
  `snmp_timeout` int(10) unsigned NOT NULL DEFAULT '500',
  `snmp_retries` tinyint(11) unsigned NOT NULL DEFAULT '3',
  `max_oids` int(12) unsigned DEFAULT '10',
  `snmp_username` varchar(50) DEFAULT NULL,
  `snmp_password` varchar(50) DEFAULT NULL,
  `snmp_auth_protocol` char(6) DEFAULT '',
  `snmp_priv_passphrase` varchar(200) DEFAULT '',
  `snmp_priv_protocol` char(6) DEFAULT '',
  `snmp_context` varchar(64) DEFAULT '',
  `snmp_engine_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`,`snmp_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 COMMENT='Set of SNMP Options';

**Comment by netniV** [comment]
Interesting, that would suggest that the cacti.sql hasn't been updated.  I'm going to check that.

**Comment by HomeServ** [comment]
Could you send me a structure export of your database (mysqldump --no-data)?
Then I can compare it to mine.

**Comment by netniV** [comment]
```
alter table `automation_snmp_items` change `snmp_readstring` `snmp_community` varchar(50) NOT NULL DEFAULT "";
alter table `test_automation_snmp_items` change `snmp_auth_protocol` `snmp_auth_protocol` varchar(6) NULL DEFAULT "";
```
These two alterations should correct that column.  I'll be doing a fuller comparison later of my db to the SQL file to see if there are any other changes.  I don't particularly want to say mine is gospel because of other plugins/mods I've installed/removed etc until I've looked it over.

**Comment by netniV** [comment]
Whilst populating the database from the SQL file is probably faster, I am wondering if another change would be to make the installer always perform the DB changes rather performing a manual install.  That might be a complication though for people like @paulgevers who maintain packages and I think change the default admin password (or that might be just the SQL one I can't recall).

**Comment by netniV** [comment]
So I have done some database comparisons for the structures that are present.  These are comparing my live (upgraded through various stages of 1.x), the 1.1.33 SQL file sourced into the database and finally the 0.8.8f SQL file sourced, then upgraded.

I am not sure if changing between InnoDB and MyISAM changes any values/defaults but I think it unlikely many, if any, of these differences could be down to that scenario.

## Comparing Live 1.1.33 to SQL 1.1.33
So far I have found comparing my live to dev, I have found:

- automation_snmp_items:
   - snmp_readstring is now snmp_community and reduced from 100 chars to 50
   - snmp_auth_protocol is now varchar(6) not char(6)
- poller_item
   - snmp_auth_protocol is now nullable but SQL file says it isn't
- settings
   - value is varchar(4096) is now increased to 4096 from 2048 characters
- snmpagent_managers
   - snmp_username, snmp_password, snmp_auth_protocol, snmp_priv_passphrase, snmp_priv_protocol all now have a default of '' where SQL file does not specify this

## Comparing Live 1.1.33 to SQL 0.8.8f upgraded to 1.1.33
What I next did was to create a basic 0.8.8f database from the cacti.sql in the 0.8.8f release file.  However, the upgrade seems to have skipped all database updates. So I ran `update version set cacti = '0.8.8f';` and then the installer this time applied the database updates.  This suggests that anyone updating from 0.8.8 or below will have an issue with the database as a result.

### Upgrade Errors
The following errors were reported during the upgrade:

**_1.0.0_**
```
[Fail] 
ALTER TABLE `host_snmp_cache` ADD `last_updated`

[Fail] 
ALTER TABLE `host_snmp_cache` ADD INDEX last_updated(last_updated)

[Fail] 
ALTER TABLE host_snmp_cache MODIFY COLUMN field_value varchar(512) DEFAULT NULL
```
**_1.0.4_**
```
[Fail] 
ALTER TABLE host_snmp_cache MODIFY COLUMN field_value varchar(512) DEFAULT NULL

[Fail] 
ALTER TABLE poller_reindex DROP PRIMARY KEY, ADD PRIMARY KEY (host_id, data_query_id)
```

### Differences
The following differences were found on the upgraded version including that many tables are MyISAM rather than InnoDB

- aggregate_graph_templates
   - created has an extra `ON UPDATE CURRENT_TIMESTAMP`
- aggregate_graph_templates_graph
   - Many columns have a different default value (ie, upgrade has '0' rather than '')
   - tab_width has a default of null rather than '30'
- automation_ips
   - hostname is 250 characters on upgrade, 100 characters on live
- automation_networks
   - subnet_range is missing a comment that is on the live version
- data_local
   - Missing key `host_id_snmp_query_id`
- data_template_data
   - Several columns have a different default value (ie, upgrade has '0' rather than '')
- external_links
   - Table comment is different
- graph_local
   - snmp_query_graph_id is int(10) unsigned on upgrade, mediumint(8) on live
- graph_templates_graph
   - Many columns have a different default value (ie, upgrade has '0' rather than '')
   - t_export and export are both extra during the upgrade as a varchar(2)
- graph_tree
   - sequence is not nullable on upgrade
- host
   - poller_id and site_id are not nullable on upgrade
   - hostname is 250 characters on upgrade, 100 on live
   - Extra keys present on upgrade, last_updated, hostname
- host_snmp_cache
   - Completely missing from upgrade
- poller
   - hostname is 250 characters on upgrade, 100 on live
   - dbHost no does not have default of 'cacti' on upgrade
- poller_command
   - poller_id is int(10) unsigned on upgrade, smallint(5) unsigned on live
   - Extra keys present on upgrade, last_updated
- poller_item
   - poller_id is nullable on upgrade, not null on live
   - hostname is 250 characters on upgrade, 100 on live
   - Extra keys present on upgrade: last_updated
- poller_reindex
   - Completely missing on upgrade
- settings
   - value is 2048 characters on upgrade, 4096 on live
- snmpagent_cache
   - type, otype, kind and max-access have no defaults on upgrade
- snmpagent_cache_textual_conventions
   - type has no default on upgrade
- snmpagent_managers
   - snmp_engine_id does not have default and is nullable on upgrade
- snmpagent_notifications_log
   - notification and mib have different lengths on upgrade
- user_auth
   - reset_perms is nullable on upgrade
- user_auth_cache
   - hostname has different length on upgrade

**Comment by dsclassen** [comment]
Thanks for doing this. I've had similar thoughts wrt the DB not getting properly upgraded during updates. Is there no way for a sanity check to be done on the DB after a new release (i.e. from 1.1.29 to 1.1.30 ) to make sure that all tables and rows are present and accounted for? Not just the new one that may have been added, but compared to a pristine newly created DB.

**Comment by netniV** [comment]
Not  so easy as MySQL adds extra info to the tables etc.  Not impossible just have to try and strip out all known extras then display any differences as warnings. Plus there are plugins which add columns and even tables so they would also should as a difference.

**Comment by cigamit** [comment]
No more overtime for me.  I make too many mistakes.

**Comment by cigamit** [comment]
I have resolved the major part of this.  The NULL vs NOT NULL we will have to handle in a separate issue.  That issue can be found here: https://github.com/Cacti/cacti/issues/1263

**Comment by cigamit** [comment]
Thanks for all the good work netniV!  Closing.  To be part of 1.1.34.
