### ISSUE TITLE
N/A 	when host is not using SNMP

### ISSUE THREAD

**Issue by interduo** [Cacti/cacti#126]
In my opininion that behavavior is not proper. The uptime should be counted in other way when host is only pingable (and not allowed to connect with SNMP).

**Comment by cigamit** [comment]
Be more specific.

**Comment by interduo** [comment]
![cacti_uptime](https://cloud.githubusercontent.com/assets/17087236/21608959/073f91f8-d1c0-11e6-8d5a-dc5ddeef7894.png)

**Comment by interduo** [comment]
Ok. I get it.

**Comment by cigamit** [comment]
By 'be more specific', I am asking you a question on what you would propose as an alternate method.  The term Uptime is specific to a hosts availability.  You can get Uptime using WMI (ex. wmic), you can get Uptime using a remote shell (ssh hostname uptime).  However, the most popular way, at least in the network world has traditionally been, through something like an snmpget.  Now, since the Cacti database is open, and the snmp_sysUptime column is open to anyone, theoretically anyone could update it.  Therefore, you are free to, and could write a script, that gathers Uptime using ssh or wmic, and then simply update that host record.  You don't need a developer to do that for you.

There has been some talk for years about writing a WMI/wmic plugins, in fact there was one at some time, but this has never been a priority for us since much of what we are monitoring has nothing to do with Windows.  However, more and more device manufacturers as supporting cousins of WMI for storage and environmental data, so it's not completely off the table in the future.

In any event, as shown by the merge 19 plugins into Cacti 1.0, it all starts with a plugin.  You could be the one to write it.  Who knows.

**Comment by interduo** [comment]
I didn't noticed that column 'in state' and that generates my problem. Information in column 'in state' is sufficient for me.
