### ISSUE TITLE
Automatic logout should not fire when using Web Basic Authentication

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#1261]
![2018-01-24_08-03-34](https://user-images.githubusercontent.com/25581728/35318835-67f5b4e4-00dd-11e8-849e-a1d527dd6709.gif)

cacti/logout.php?action=timeout
Sometimes i get a automatic logout. The "Login Again" option on the timeout page doesn´t work for me. 

I have to go to the following page ( **cacti/index.php** ) to log in again

I use the Authentication Method: "Web Basic Authentication"

Is this an cacti issue or a browser issue?

**Comment by netniV** [comment]
That is probably ore a cacti issue.  It's probably trying to look you out a second time when it hits the index page, even though it should already be logged out by that point and taking you the the auth_login.php page.  Out of curiosity what does the link point at for you?

**Comment by DavidLiedke** [comment]
Login Again --> /cacti/index.php

**Comment by netniV** [comment]
OK, just wanted to make sure.  So I'm guessing that jQuery is converting the link to an AJAX call and at this point it's redirecting you back to being logged out, rather than to login as you've already logged out. 
 The reason potentially being that the referrer isn't present when making the ajax call but I'm not totally sure.

I've just signed into my test system (using local auth). I'll let that time out and see what occurs, then I'll switch to apache auth and retest

**Comment by cigamit** [comment]
Web Basic should not time out.  It's likely something in the bottom footer code.

**Comment by cigamit** [comment]
Should be resolved now.  Please test.

**Comment by DavidLiedke** [comment]
Thanks. I give you a feedback asap.

**Comment by netniV** [comment]
How has your testing gone?

**Comment by DavidLiedke** [comment]
At the moment it looks very good :)

**Comment by netniV** [comment]
Cool.  In that case, you may as well close this issue and if you discover anything further feel free to open it again.
