### ISSUE TITLE
Prevent system running if system log is not writable

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1298]
I think that the global.php include should first check for write permissions to the cacti.log file.  If this is not available, immediate issue a die() to report this to screen.  Otherwise, scripts are able to run but no logging is performed which give the appearance that a script hasn't run.

I came across this problem when I ran a cli-only script manually with normal level of logging but with the plugin in debug mode.  Nothing is output to screen which is normal, but nothing was appearing in the cacti.log either despite being in the plugin debug list.  It turned out that because the website rotates the log the user and group were www-data which was a group the user I was using was not part of.

This could also cause issues with the Poller if there it is running under a user that does not have access to the log file.  

Additionally, I think because the user does not have access to the cacti log file, any plugin with that issue gets disabled.  At least mine seemed to but I haven't tested that again further.

**Comment by netniV** [comment]
Interesting side effect of this issue that you should be aware of @cigamit is that CLI scripts will now fail if the user running them cannot write to the cacti log file:

```
# php add_datasource.php
System log file is not available for writing, please enable write access
```

**Comment by mhoran** [comment]
Hey @netniV. This effectively broke my installation after upgrading to 1.2.1. My poller runs as user `cacti`, but the frontend as `www`. I don't think this is a unique configuration, but when I navigate to my installation, I get an error because the `www` user can't write to the log.

I've changed the permissions so that the directory is group writable, and added the www group to the directory. If you can think of a better way that this should set up, let me know.

Note that this is the default configuration of the FreeBSD cacti package, so if that's not how you envision cacti being run, it'd be good to get that fixed in the package.

**Comment by mhoran** [comment]
Great, that makes sense. Happy to know that this is a supported configuration. It's likely that my frontend was never able to log any errors (certainly leading to headaches) while the poller was successfully logging.
