### ISSUE TITLE
Automation discovery : New devices added by automation discovery have empty SNMP community field

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#1300]
Hi Everyone,

Since last version update I noticed that for Automation discovery all our newly added devices discovered by a scan are added to CACTI but without the **SNMP community**

Before it was correctly adding the SNMP community from the Automation discovery **SNMP Option** matching SNMP community

**Comment by netniV** [comment]
In your network discovery, is it using the correct option set?  I'm wondering if this is a problem with changing from snmp_readstring to snmp_community in the host table's column name

**Comment by jhonnyx82** [comment]
Yes, the option were not changed and I had these discoveries working well before the 1.1.33 update

**Comment by netniV** [comment]
What version were you on prior to the 1.1.33 update?

**Comment by netniV** [comment]
OK, I'll check out the differences between the two release tags later today and see if anything is likely to impact on this issue.

**Comment by jhonnyx82** [comment]
thanks a lot, let me know if I can help with the testing anyway

**Comment by netniV** [comment]
So I can see a lot of changes to the automation to move from snmp_readstring to snmp_community.  I think it may be related to this.

**Comment by netniV** [comment]
One thing, can you make sure that your automation tables are right.  Do a SHOW CREATE TABLE _tablename_ \G against each fo them and paste here.

**Comment by jhonnyx82** [comment]
If it's OK with you I ran DESCRIBE instead (let me know if you need the other command):

[automation_tables.txt](https://github.com/Cacti/cacti/files/1689749/automation_tables.txt)

**Comment by netniV** [comment]
OK, I believe that I have found the problem. It's in `lib/api_automation.php` and it assigns `automation_snmp_items`.`snmp_readstring` to `automation_device`.`snmp_community`

This is wrong on two levels because for starters, `snmp_readstring` on `automation_snmp_items` is now `snmp_community`; and because `snmp_community` is just `community` on automation_devices;

I think if you look at automation_devices, you'll find that community is not populated for your devices.

**Comment by jhonnyx82** [comment]
TBH the automation automatically adds the devices to CACTI in my installation, so I found out looking at new devices with missing SNMP community, but I guess it's the same as you are looking at.

Funny is that the device is queried with the right SNMP community and then it's not saved with any community, as you pointed out.

**Comment by netniV** [comment]
Do this SQL query:
```sql
select community, count(*) from automation_devices;
```

**Comment by jhonnyx82** [comment]
![image](https://user-images.githubusercontent.com/26431888/35752246-87ec08fe-085b-11e8-85aa-b9b75e5cac07.png)

**Comment by netniV** [comment]
So they all have a community.  OK, let me check the code again to see if that is what I expected 👍

**Comment by netniV** [comment]
Actually first, lets correct the SQL statement.  I was surprised by the result so I thought I'd test it against my own data and realised I've missed off the group by statement.
```sql
mysql> select community, count(*) from automation_devices;
+-----------+----------+
| community | count(*) |
+-----------+----------+
|           |      542 |
+-----------+----------+
1 row in set (0.00 sec)

mysql> select community, count(*) from automation_devices group by community;
+-----------+----------+
| community | count(*) |
+-----------+----------+
|           |       83 |
| <name>    |      459 |
+-----------+----------+
2 rows in set (0.00 sec)
```
Try using that second SQL statement and let me know results.  Also, if you know the name of the device that you are looking at as an example, replace _<name>_ with what you are looking for
```sql
select id, hostname, community from automation_devices where hostname like '%<name>%'
```

**Comment by jhonnyx82** [comment]
To run this test I deleted one of the devices that was in CACTI, created a test automation network to discover it and when I ran it. I can see that the community is in the automation_devices table entry

![image](https://user-images.githubusercontent.com/26431888/35755106-430f14be-0866-11e8-8f46-40cc92562e58.png)

Then I purged the discovery automation_devices table, I modified the automation discovery test adding the option :  **Automatically Add to Cacti** and when I ran again the discovery I could see that the device added to cacti is missing the Community

**Comment by netniV** [comment]
I looked at that section of code.  But with your backtrace, this makes things a bit easier.  It depends on whether $device is from the `host` table or the `automation_devices` table.  I really think we should make a mod to rename the `automation_devices` table to be inline with every other table's snmp options and I'm hoping @cigamit would agree with that assessment.

**Comment by netniV** [comment]
The `poller_automation.php` is setting everything as `snmp_community`, so is `automation_valid_snmp_device()` in `api_automation.php`.  The problem is that (also in `api_automation.php`) is `automation_add_device` that is using `community` not `snmp_community`.

This furthers my resolve that we should be renaming that column to avoid conflict/confusion.

**Comment by cigamit** [comment]
Totally agree with the renaming.  I've been trying to get some of the older plugins (especially thold) to use proper schema naming for ever.  The update in 1.1.32 attempted to handle all the snmp stuff in the core Cacti (excluding username and password due to numerous user scripts using those columns directly).  It appears however, that we missed this one in the automation table/files, which of course leads to errors.

As developers, we try to minimize variation so that we can get into the habit of assuming things when writing code, and then of course, as a consequence, we don't catch the fact that assumption is the mother of all screw ups until regression testing.  And as a small open source project, we often times skip that part of the release process.

Either way, we are making great progress here.

**Comment by cigamit** [comment]
Resolved.  Thanks for reporting.
