### ISSUE TITLE
Poller - Non-numeric value error

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1317]
```
2018/02/07 14:10:08 - POLLER: Poller[1] NOTE: Poller Int: '300', Cron Int: '300', Time Since Last: '67.34', Max Runtime '298', Poller Runs: '1' 
2018/02/07 14:10:06 - POLLER: Poller[1] -1517983802.369 seconds 
2018/02/07 14:10:06 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 631 CactiErrorHandler)(/lib/functions.php: 4429 cacti_debug_backtrace) 
2018/02/07 14:10:06 - ERROR PHP WARNING: A non-numeric value encountered in file: /var/www/html/cacti/poller.php on line: 631 2018/02/07 14:10:02 - SYSTEM STATS: Time:300.4434 Method:spine Processes:1 Threads:1 Hosts:3 HostsPerProcess:3 DataSources:7 RRDsProcessed:0 2018/02/07 14:10:01 - POLLER: Poller[1] Maximum runtime of 298 seconds exceeded. Exiting.
```
As taken from https://forums.cacti.net/viewtopic.php?f=21&t=58418&p=271074&sid=b9c9cf94da4a065506a4b9ec44fece92#p271074

Error message needs correcting to prevent the cacti_log() parameters from being non-numeric (maybe do calculation before logging?)

**Comment by cigamit** [comment]
Looked at the code, not sure how that is happening.  It's like the $loop_start is 0, which makes no sense.

**Comment by netniV** [comment]
I think it happens if a poller has never set a time ?  I'm not sure right now as I'm not looking at the code directly.

**Comment by cigamit** [comment]
I don't know.  It's set at the very top of the file.  So, it can not be bypassed.  Maybe the call can fail and return 0?  Have to check php.net.

**Comment by cigamit** [comment]
Check out that commit.  It has to be the reason.  Brand new database, and for some reason read_config_option() is not returning the default from the 'default' => 300 from the form data.  That would be a bug in the read_config_option() without a session variable.  When $_SESSION is not defined, it's supposed to use a global variable to store the 'default' settings where there is no setting in the database.

If this is the case, this bug is not resolved, and we have to look elsewhere.

**Comment by cigamit** [comment]
Any feedback from the forums.  I've done all I can on this.  I figure it's closed.  We need to determine if the default is not properly pulled from the default value when it's not set in the database though.

**Comment by netniV** [comment]
Updated the forum post, but don't know if it'll occur again.
