### ISSUE TITLE
Post upgrade 1.1.X page render time issues

### ISSUE THREAD

**Issue by elwesingollo** [Cacti/cacti#1320]
Hello,
after updating from 0.8.8f to 1.1.25 we are experiencing very long times for rendering the graph_view pages.
the server is DL360 G7 with 2 Xeon CPU 2.4 Gz Quadcore, 12 Gb Mem
RH EL 6.6 64 bit

top - 11:08:06 up 410 days, 17:46, 1 user, load average: 0.27, 0.15, 0.10
Tasks: 401 total, 1 running, 400 sleeping, 0 stopped, 0 zombie
Cpu(s): 0.1%us, 0.1%sy, 0.0%ni, 93.7%id, 6.0%wa, 0.0%hi, 0.0%si, 0.0%st
Mem: 12182516k total, 9442804k used, 2739712k free, 407176k buffers
Swap: 16777212k total, 1540200k used, 15237012k free, 6271924k cached

the database is located on a remote server:
DL360 G5 with 2 Xeon 3Ghz Dual Core CPUs and 12 GB mem
RH EL 5.6 32 bit (do not blame me for this: wink :))

top - 11:13:51 up 622 days, 22:54, 1 user, load average: 0.34, 0.28, 0.27
Tasks: 120 total, 1 running, 119 sleeping, 0 stopped, 0 zombie
Cpu(s): 0.8%us, 0.4%sy, 0.0%ni, 96.4%id, 2.2%wa, 0.0%hi, 0.1%si, 0.0%st
Mem: 3367648k total, 3242828k used, 124820k free, 62020k buffers
Swap: 2096472k total, 184k used, 2096288k free, 555056k cached

I checked the options to enable the image cache
Does anyone have a clue as to how to find the cause of this problem?
what kind of controls can I activate?

Edit:
theese are Mozilla network monitor, the network traffic is more than doubled..
0.8.8f
Image
![immagine](https://user-images.githubusercontent.com/20436175/35967197-6e9d20fe-0cc0-11e8-83bc-a166ac053d3d.png)

1.1.25
Image
![immagine](https://user-images.githubusercontent.com/20436175/35967210-7b008322-0cc0-11e8-98a7-ef682b7d4390.png)

Does anyone has a clue for this behaviour?
there is a way to solve this?

**Comment by netniV** [comment]
The most likely cause of this is the move to AJAX to download the images.  These are being created on the fly and as such may not be being cached.  @cigamit may have better input on this though.

**Comment by cigamit** [comment]
The timing has not changed too much, but the size of the transfer has.  This has to do with the base64 encoding of the image stream into ascii in order to make it safe inside of the json.

We don't really ever cache images except on the server using the Performance Boosting image cache, which helps with backend iops and core time and will reduce that time a bit.

@netniV, if you have some cycles, maybe you can attempt to simply perform a json encode of the array (without the base64 encode), and see if the image can be returned properly.  You will of course have to change the image src type from a base64 encoded to a pure image.

I'll commit to getting the other remote data collector ping issue addressed this morning before my work day starts.

**Comment by netniV** [comment]
My thoughts on that are

- keep as is, which requires base64 encoding, no way around that since the image may have control characters and other bits which cause JSON parsing or the request/response to fail.

- to separate out the image from the JSON and provide a data URI for the image.  You wouldn't be able to produce valid JSON/HTML with raw image data.  

- to use SVG's as we wouldn't need to base-64 encode but I'm not sure how PNG vs SVG in terms of size would be or if you can convert from PNG to SVG.  I have converted them the other way only so far.

**Comment by netniV** [comment]
I did find this interesting fact that (https://css-tricks.com/data-uris/#article-header-id-4):
> ...when measuring the performance of hundreds of thousands of mobile page views, that loading images using a data URI is on average 6x slower than using a binary source link such as an img tag with an src attribute!

**Comment by cigamit** [comment]
Well that sort of makes sense.  In this case, you would cache the image in the image in the boost image cache with some sort of reasonable name like |local_graph_id|.png and then pass that back with the json tag as the src attribute.  This way multiple people could share the same caching just like with boost cache.  What I would do is to combine that with the boost cache option.  So, if it's enabled, then pass back just the src tag and not the image data.  Make sense?  This way it's less of a heavy lift.  Also SVG seems very inefficient.  Much more data.

**Comment by netniV** [comment]
Yeah I figured that about SVG, though it is nice for simple graphics.  I think we would need to cache more than just on the local id, since it would need to be time based too? Or does boost around take care of that. I haven't a clue how boost works and I'm not even sure I have it enabled.

**Comment by cigamit** [comment]
Boost knows about timespans, custom timespans are not cached.  So, if you pick a non-standard timespan, caching is disabled.  Also, cached images live until their RRDfiles are updated either by boost, or the fact that there is new data.  So, it's magic.

**Comment by netniV** [comment]
Since the graph page can quite easily generate a lot of images for a custom range (I'm always zooming in) would that not mean there's a lot of uncached images or is that were we need to add the new logic to create them, but when boost kicks in its cleaning these out?

**Comment by cigamit** [comment]
I guess that is an option and a good one.  For zoom, or custom timespans, we would have to distinguish them from other cached images, and always give them a ttl of one poller pass, regardless of the hearbeat (poller rate).  So, that just means a few tweaks to the image caching algo.

**Comment by cigamit** [comment]
I've resolved this a while ago.  It was rendering twice for each graph.
