### ISSUE TITLE
spine 1.1.x (at least up to 1.1.34) sets "ignore_host" if "Downed Device Detection" is set to "None" but SNMP information is set and device is not responding to SNMP

### ISSUE THREAD

**Issue by feisenko** [Cacti/cacti#1324]
This behavior is different from cmd.php and spine 0.8.x. and also not logical.
Background: the Device SNMP information are set because they are correct for this device, but at the moment SNMP and PING is blocked by an other device in the network path and only HTTP access is possible, which is queried via PHP Script Server. 

Proposed solution to restore previous behavior:
poller.c (Version 1.1.34) Line 544: if (host->availability_method != AVAIL_PING) {
needs to be changed to:
 if ((host->availability_method != AVAIL_PING) && (host->availability_method != AVAIL_NONE)) {
so that get_system_information is not called, which is setting ignore_host to TRUE (in snmp.c line: 379) if the device does not respond to SNMP requests.

Best regards,
Franz

**Comment by netniV** [comment]
I'll take a look and see what effect the ignore_host has.  From what I've read here, I think you are right as it sounds like it's performing an SNMP check when it should not be.  If it then sets ignore_host which prevents all other checks, that seems wrong.

However, you need to raise this over on the spine repo, since it's a spine issue not a cacti one (gets confusing I know 👍 )

**Comment by feisenko** [comment]
moved to https://github.com/Cacti/spine/issues/48
