### ISSUE TITLE
Console->Users->(Edit) Permissions checkmark descriptions missing (1.35)

### ISSUE THREAD

**Issue by gmuellerfr** [Cacti/cacti#1334]
Hello,
today I've moved to 1.35 and discovered that the descriptions are missing in all themes except Sunrise.
I don't know, when this bug arised, because I seldom edit the user permissions.

![screenshot-2018-2-12 console - users - edit 1](https://user-images.githubusercontent.com/25848039/36102431-9d92ea8e-100c-11e8-8ee4-3674631d6c82.png)
![screenshot-2018-2-12 console - users - edit](https://user-images.githubusercontent.com/25848039/36102436-9ff69ac8-100c-11e8-8bf1-9db1b705670e.png)

Thank you for listening.
Guenter

**Comment by cigamit** [comment]
This is done in the theme css.  Just remove the .checkboxLabel css elements from the themes.

**Comment by cigamit** [comment]
Resolved in the develop branch.

**Comment by gmuellerfr** [comment]
Hello,
thank you for the remedy. Hope, you will remove it in the next release or is this a feature and not a bug?
Thank you for listening.
Guenter

**Comment by gmuellerfr** [comment]
Ok, you gave the answer while I was typing the question. :)
Thank you for listening.
Guenter

**Comment by cigamit** [comment]
No problem Guenter.  We want 1.1.36 to be the last of the branches.  We think we are pretty darn stable now.  So much so, we've been working on gui tweaks like this one.  Need more people to QA, otherwise, we will keep this 1.1.x thing going indefinitely.  It's looking better than it was a year ago, and way better than two.  Still not based upon a well recognized framework, but whatever.
