### ISSUE TITLE
first graph on second page

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1339]
In tree view, when changed to another page from 1st page 1st graph won't get loaded in 1.1.35
![cacti](https://user-images.githubusercontent.com/35136010/36153487-6b62b0d8-10f4-11e8-9afa-ebf033edfa8d.png)

**Comment by netniV** [comment]
I can confirm this bug.  Since I recently submitted changes for this page, I will see if my work has anything to do with this.

**Comment by netniV** [comment]
This issue appear to occur no matter what page you switch to.  Even if you switch back to the first page, you experience the same issue.

**Comment by netniV** [comment]
I think it has to do with the $.ajaxQ.abortAll(); being used in initializeGraphs() but @cigamit would know better than me about why that is there.  I can see it being used at the top of the function, but also inside the click event.

**Comment by netniV** [comment]
The following patch fixes things up for me on 1.1.35

```diff
diff --git a/include/layout.js b/include/layout.js
index b9227fd..a293352 100644
--- a/include/layout.js
+++ b/include/layout.js
@@ -2235,7 +2235,6 @@ function redrawGraph(graph_id) {
 }

 function initializeGraphs() {
-       $.ajaxQ.abortAll();
        $('a[id$="_mrtg"]').unbind('click').click(function(event) {
                event.preventDefault();
                event.stopPropagation();
```

**Comment by cigamit** [comment]
This is not the issue.  Confirmed the behavior, and remediated in layout.js.  I will make a commit shortly.

**Comment by cigamit** [comment]
This problem was caused due to an embedded javascript function in the page change that would initializeGraphs().  But there was already a $.ready() function on the page to do the same thing.  So, essentially the initializeGraphs() function was called twice.  That would have been okay, other than that that drove the .fail() section of our new javascript error handlers to fire, with a status code of 0, and an empty responsetText attribute, which caused a javascript error which in the end, was what caused the first graph to not render.

So, multi-layer issues, problem solved and another step forward.

**Comment by netniV** [comment]
I was going to say it was almost like we were calling it twice.  I'll check out the fix.
