### ISSUE TITLE
Unable to open Time Graph View in new tab

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1340]
Unable to open time graph view for a specific graph on new tab as it loads the same page. version 1.1.35

**Comment by netniV** [comment]
Can you please describe the steps you are taking that you would expect this functionality to work?

**Comment by chathurag** [comment]
As per attached diagram. Right click on the time graph view icon on the right to graph and select open in new tab. How ever that will not open time graph for the specific graph.
![cacti](https://user-images.githubusercontent.com/35136010/36156425-04f8f916-10fd-11e8-8248-984e172c63a2.png)

**Comment by netniV** [comment]
Thanks, I will take a look at this one tonight to see if I can spot the issue.  It does appear to be all in the same page, so could be an issue where a variable isn't passed in the URL but set in the post which results in the issue.

**Comment by cigamit** [comment]
You have to click directly over the graph area, then you will see on the zoom menu a 'Graph' option, and from there 'Open in new tab'.  This is not a bug.

**Comment by chathurag** [comment]
Hello,

By doing as @cigamit mentioned only opens the graph in new tab but not the time graph view of the specific graph

Please find the differences of normal graph (Image 1) and time graph view (Image 2) in new tab as follows.

![cacti1](https://user-images.githubusercontent.com/35136010/36240372-2d39fc46-1237-11e8-88f1-f150d19febf0.png)

![cacti2](https://user-images.githubusercontent.com/35136010/36240430-9a06e0b4-1237-11e8-8c1d-82b92ae8de82.png)

**Comment by netniV** [comment]
The issue is that the breadcrumbs do no have a link in them.  What happens is that they are late-bound via AJAX to have a click event that makes it work.  I'm not sure why that happens since looking through the code, I can't see a logic reason so far but there must have been a history one. I'm trialling a change on my test box to see what happens if we insert the HREF but currently there is no way to open the time view in a new tab.  

Interestingly enough, it also raises another bug I was going to report at some point where you can't refresh the time view without going back to the main graph selection.  A very similar but possibly slightly different issue.

**Comment by netniV** [comment]
The following is my Work In Progress patch:
```diff
diff --git a/include/layout.js b/include/layout.js
index b9227fd..5de5c5f 100644
--- a/include/layout.js
+++ b/include/layout.js
@@ -2236,7 +2236,12 @@ function redrawGraph(graph_id) {

 function initializeGraphs() {
        $.ajaxQ.abortAll();
-       $('a[id$="_mrtg"]').unbind('click').click(function(event) {
+       $a_mrtg = $('a[id$="_mrtg"]');
+       $a_mrtg.each(function() {
+               graph_id=$(this).attr('id').replace('graph_','').replace('_mrtg','');
+               $(this).attr('href',urlPath+'graph.php?local_graph_id='+graph_id);
+       });
+       $a_mrtg.unbind('click').click(function(event) {
                event.preventDefault();
                event.stopPropagation();
                graph_id=$(this).attr('id').replace('graph_','').replace('_mrtg','');
@@ -2259,7 +2264,15 @@ function initializeGraphs() {
                );
        });

-       $('a[id$="_csv"]').unbind('click').click(function(event) {
+       $a_csv = $('a[id$="_csv"]');
+       $a_csv.each(function() {
+               graph_id=$(this).attr('id').replace('graph_','').replace('_csv','');
+               $(this).attr('href',urlPath+
+                       'graph_xport.php?local_graph_id='+graph_id+
+                       '&rra_id=0&view_type=tree&graph_start='+getTimestampFromDate($('#date1').val())+
+                       '&graph_end='+getTimestampFromDate($('#date2').val()));
+       });
+       $a_csv.unbind('click').click(function(event) {
                event.preventDefault();
                event.stopPropagation();
                graph_id=$(this).attr('id').replace('graph_','').replace('_csv','');
@@ -2366,7 +2379,15 @@ function initializeGraphs() {
                realtimeGrapher();
        });

-       $('a[id$="_util"]').unbind('click').click(function(event) {
+       $a_util = $('a[id$="_util"]');
+       $a_util.each(function() {
+               graph_id=$(this).attr('id').replace('graph_','').replace('_util','');
+               $(this).attr('href',urlPath+
+                       'graph.php?action=zoom&local_graph_id='+graph_id+
+                       '&rra_id=0&graph_start='+getTimestampFromDate($('#date1').val())+
+                       '&graph_end='+getTimestampFromDate($('#date2').val()));
+       });
+       $a_util.unbind('click').click(function(event) {
                event.preventDefault();
                event.stopPropagation();
                graph_id=$(this).attr('id').replace('graph_','').replace('_util','');
@@ -2388,7 +2409,8 @@ function initializeGraphs() {
                );
        });

-       $('a[id$="_realtime"]').unbind('click').click(function(event) {
+       $a_real = $('a[id$="_realtime"]');
+       $a_real.unbind('click').click(function(event) {
                event.preventDefault();
                event.stopPropagation();
                graph_id=$(this).attr('id').replace('graph_','').replace('_realtime','');
```
Please note, this is working for me so far.  However, it does change things from a UI perspective because the links now are full relative links.  There is plenty of jQuery actions that are skipped for href items with a single # in them and these would technically no longer apply depending on whether they are triggered before or after the initialiseGraphs() function is called.

Single the page is reloaded whenever the timespan is changed, this makes the URL work.  We probably do not need to rebuild the URL in the click function that follows each "$a_blah.each()" but it would need to add the header=false to handle it.  

The click functions themselves have been left in because the graph_view page as a sidebar which does not get replaced using the functionality.  Whereas, if you remove the click handlers, the sidebar (tree) would be removed..

Feel free to test the page out and provide some feed back here but I suspect the inclusion of this into the main release code will need some decent testing to make sure it works properly.

**Comment by cigamit** [comment]
@netniV, I've asked @ronytomen to release 1.1.36 this weekend.  Don't know if it will be Saturday or Sunday though.

**Comment by netniV** [comment]
I'll take a look at adding the class.  I'm not sure why but there are no links specified when the actual breadcrumbs (small icons) are created.  They are only added after the fact.  I'll take a look tonight and do some more testing.

**Comment by cigamit** [comment]
look at the loadPage() in layout.js function.  It's some ugly stuff.  We've debated removing the breadcrumbs for years, but they are actually useful especially in the 1.x branch, though they add all sorts of complexity and bloat the functions.php.  Moving the $nav array to a table would help, but it's like way down on the list of things to do, like right at the bottom.

**Comment by chathurag** [comment]
@cigamit  I created new issue as because you closed this issue without accepting there is a bug. I was unaware that after closing that I can comment and you may re open the same.

**Comment by cigamit** [comment]
@chathurag, yea no problem.  When I first started using GitHub, I was not sure what the heck I was doing either.  It's been a breath of fresh air for the Cacti project though.  Thanks for contributing to it's success.

**Comment by cigamit** [comment]
@netniV, how close to a pull request are you?  We are doing another release this weekend.

**Comment by netniV** [comment]
Been working on some plugin stuff the past couple of days, but I'll finish this off today.

**Comment by cigamit** [comment]
Okay, this issue is resolved now.  I also disabled the right context menu where it made no sense and fixed a Realtime JavaScript issue.  Good to give that a real good look over.

**Comment by cigamit** [comment]
@chathurag, it's going to be easier to wait for 1.1.36 then attempt to patch your system.  I recommend you wait.  We are a day or so off from release.
