### ISSUE TITLE
Data Profile - Disabled fields shown temporarily as editable

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1357]
When editing a data profile via Presets -> Data Profiles -> Edit, the combo boxes for internal and heartbeat appear to be editable until you click on them. They then become properly disabled.  However, the consolidate function does disable on entry.

**Comment by cigamit** [comment]
Yea, this has to do with the jqueryui.  We have to check if the jqueryui element is set, for example:

`if ($(this).button('instance')) {`
`  $(this).button('disable');`
`}`

or

`if ($(this).selectmenu('instance')) {`
`  $(this).selectmenu('disable');`
`}`


This is done inconsistently in the user interface files in various sections.  Some are using 'widget' instead of 'instance', some are not doing it.  We should have a small project to sweep the code for these and use the proper syntax as shown above.

**Comment by cigamit** [comment]
In the mean time, this one is resolved.  Searching the code (base/lib/include nonrecursive) for "\.prop('disa", will be the fasted way to find them.  Feel free to open a ticket for 1.2.  This specific issue is resolved.
