### ISSUE TITLE
Allow adding a Non-Existing Data Source to an Existing Graph when the Template is Updated 

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/cacti#1364]
Probably the most annoying and troublesome bug I have come across since plunging into the 1.x branch.

Modify a graph template.
Add a gprint, line, area - any graph item which would use a data source
Select a data source
Save

Decide later:
Maybe that line should be an hrule, or a comment instead.
I have 50 items on this graph, quicker to change than delete and create new, move to top. Logic aside, lets change the first drop down to a  comment, type the comment, save it.
Delete the DS below using the way too small trash can item that should be a check box with an action menu or delete button like most other pages -- (I know i am not the only one to delete the wrong ds)

Graph is pretty. Success. Profit.
Now go and duplicate 20 other graph templates off that template

Behold:
Every new graph created from this template has this ghost data source. which screws up the poller since the ds may not exist on the device using said template.

The reason for modifying a graph template in this manner IMO is a moot point. If you change to an item type without a DS - remove the DS when saving.
Right?

**Comment by cigamit** [comment]
@chris-technicate, you are so accurate on this.  This flaw in the design is one of the reasons I added an 'Advanced' option to the GUI.  It was for people who 'knew' about this nasty side affect of modifying modifying a graph or data source.  We also added 'locking' to again add an extra step before you damaged your install.  But the core issue you spoke of still exists, let me think about that.

Further, we have to find a resolution to this and a few additional issues.  The problem goes deeper of course.  Some Cacti Data Input Methods will return several data source values at once, and they are then added to a single RRDfile.  Since historically, RRDtool has not done a very good job about adding a data source to an RRDfile, it makes this difficult.  That may be fixed in 1.7 though.  More research is required.  Cacti will ignore an extra value coming back from an data input method, but when you add a Data Source to a Graph, Graph Template, or a Data Template, it's a bad day.  It'll work, but be prepared to delete your existing RRDfiles first.  Cacti will re-create them, but then you have lost your historical data.  Not good.

This is one of the issues that the original author of Graphite called out when he created the whisper format.  He stored only a single data source per whisper file, making it a bit more rubbery.

I would have to give these issues quite a bit of thought as to how we would move Cacti to that same paradigm, or just to improve the templating.  Right now, my thoughts are elsewhere.  So, I'll look for a point solution to this issue, and then will open a design bug to tackle the rest when I have time to double back to this annoying design flaw.  However, if you look at the change of pace that we have been achieving with all the additional contributors, it should not be too long before we get down to tackling this issue.

**Comment by netniV** [comment]
Since RRDTool can add data to the files, would there not be a way to 'import' the old data (assuming that the intervals etc were still the same) ?

**Comment by cigamit** [comment]
@netniV, yea, I thought about that.  If we could assume that the web server had write access, we could do a lot of things from the GUI.

@chris-technicate, I love this comment yup: 
Delete the DS below using the way too small trash can item that should be a check box with an action menu or delete button like most other pages -- (I know i am not the only one to delete the wrong ds)

I was complaining the other day that that whole part of the template is so confusing to the average administrator for Cacti and what needed to be done about it.  I mused with removing it altogether, but it was there for people to be able to compensate for some of the issues related to a not fully formed state diagram for all possible actions when modifying a template.  Though most experienced Cacti administrators kind of know what they are doing, it drives re-installs, or database restores for newbies.

**Comment by cigamit** [comment]
I just checked 1.7.0.  Looks like adding a data source is not there, renaming yes, adding no.  Have to check the changelog.  I swear I saw that somewhere.  @gan-dalf added some functions to lib/rrd.php in the old 0.8.9 code, and I moved them into the 1.x branch, and this code would have allowed for the adding of a data source, but to my knowledge it has not been tested.
