### ISSUE TITLE
Posting tweets for threshold plugin

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1382]
Is it possible to post tweets to twitter (to previously configured account) for thold plugin from cacti as it is easy to generate sms notifications?

**Comment by netniV** [comment]
Currently there is no way to notify by any means other than email.  You would need to raise an issue on the thold plugin repository rather than here though because this is for core cacti.

https://github.com/cacti/plugin_thold

Either way, you should close this issue since it isn't a cacti-base issue.

**Comment by chathurag** [comment]
thank you I will post on thold
