### ISSUE TITLE
Last Month@Reporting does NOT honor time frame

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#1424]
I'm running Cacti 1.1.21. 

It worth mentioning that I had this report working for several months until I changed it to add another graph. 

I'm thinking that it may have got broken between earlier Cacti versions and the 1.1.21 but it kept working until I updated the report settings.

this is how the report settings look like

![image](https://user-images.githubusercontent.com/13456559/36816212-06f13a5c-1d42-11e8-9ac3-121d030f6b9e.png)

And this is why I get

![image](https://user-images.githubusercontent.com/13456559/36816265-2ef9813a-1d42-11e8-8e3d-196f363f4584.png)

Last 2 month option seems to work fine.

**Comment by jpobeda** [comment]
I think the problem might be that this a 28 days month and it's not displaying it in weeks.

First screen shows traffic in 2 days intervals.

**Comment by jpobeda** [comment]
Closing. Doesn't worth a special case for feb. Sorry.

**Comment by jpobeda** [comment]
I'm reopening this because I think if we select "Last Month" we should get the displayed graph in weeks to be consistent.

**Comment by jpobeda** [comment]
And the legend is not included either

![image](https://user-images.githubusercontent.com/13456559/36821542-48948d18-1d58-11e8-92e2-bbd0c3d6dbe4.png)

**Comment by cigamit** [comment]
The issue with legends not showing has been resolved in the 1.2 branch.  The display of week's instead of days is completely under RRDtools control and by us setting a month duration does not guarantee that RRDtool will do it the way we want it.  Might be better in RRDtool 1.7.  I have not checked the change log.  However, since the thumbnail vs. non-thumbnail is fixed in 1.2, I'm going to close this.
