### ISSUE TITLE
cli audit_database.php generate table error

### ISSUE THREAD

**Issue by rcalpha** [Cacti/cacti#1447]
When I run: php audit_database.php

It generate the following error in every entry:
===============================================
Notice: Undefined index: Tables_in_cacti in /export/www/cor/cacti-1.1.36.prod/cli/audit_database.php on line 139
---------------------------------------------------------------------------------------------
Checking Table: ''                                       - Does not Exist.  Possible Plugin
PHP Notice:  Undefined index: Tables_in_cacti in /export/www/cor/cacti-1.1.36.prod/cli/audit_database.php on line 139

===============================================

Reviewing the code, I'm attaching a possible patch

[audit_database.php.patch.txt](https://github.com/Cacti/cacti/files/1781604/audit_database.php.patch.txt)

**Comment by netniV** [comment]
Now that's an interesting bug and I can see what the issue is.  The name with Tables_In_ prefix will be the database name of the connection.  So I'm going to guess that you are using cacti2 as the database name.

So, your patch, would only work for you. 

The correct fix is to apply the database name from the connection details as it brings about a larger issue that the name is hardcoded currently.

**Comment by netniV** [comment]
I have a partial patch for this, but I'm not sure how @cigamit generated his db_inserts.  Therefore, I'll create a patch but he will probably need to fix up the inserts as they generate a warning about the table_columns and table_indexes tables.

**Comment by rcalpha** [comment]
Yes, the database is "cacti_2"

**Comment by netniV** [comment]
OK, well there is an updated cli/audit_database.php now, but it will fail self auditing until @cigamit has time to patch the inserts or I figured out what I need to change.

**Comment by cigamit** [comment]
Should be resolved now.  You can pull the cli script from develop.
