### ISSUE TITLE
Cacti version 1.1.36 - CSRF Secret

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#1451]
Hi @netniV , files are created into /tmp but the extension is missing:

ls -lrt /tmp/
-rw-------  1 apache apache       0 Mar  6 09:35 ccpt3ySRY

Cacti Log:
2018/03/06 09:35:04 - POLLER: Poller[Cacti-Poller] ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php':
2018/03/06 09:35:04 - POLLER: Poller[Cacti-Poller]  ERROR: PHP Source File '/usr/share/cacti/include/csrf/csrf-secret.php'  from Cache has an error whilst checking syntax (127) whilst executing:  /bin/php -l /tmp/ccpt3ySRY.php

thanks.

**Comment by netniV** [comment]
Do you have the latest poller.php from the develop branch?

**Comment by netniV** [comment]
Basically, that error should not occur because it uses the same `$tmpfile` throughout the code.  So if it's displayed in one place with the .php, they should all have it.

**Comment by anarkia1976** [comment]
Yes, i have the latest source. Files in tmp didn't have .php extension.

**Comment by netniV** [comment]
I just figured out what the problem is, and I'll provide a patch for it.  Basically, by using tempnam() to get a temporary name, it doesn't include the .php prefix.  However, tempname ALWAYS creates the file.  So, we need to either

- store the temporary name, then store the name plus the prefix, then remove both
- store the data in the temporary name only, since that would be removed.

**Comment by anarkia1976** [comment]
Ok now, thanks a lot for your effort.
