### ISSUE TITLE
Title of add_graphs.php being ignored

### ISSUE THREAD

**Issue by rojasneva** [Cacti/cacti#1453]
When I try to create a graph via cli using `add_graphs.php` with the argument `--graph-title='myTitle'` and `--graph-type=ds` (not sure if  graph-type is relevant) the title is never set.

From commit https://github.com/Cacti/cacti/commit/b26884cad0212af5919a2b6976b0a75801ee3e5c from @cigamit  I could see that now you're updating _title_cache_ field instead of the _title_ field in the _graph_templates_graph_ table, so when there is the call to the `update_graph_title_cache` method the previously `title_cache` set is overwritten.

I could submit a commit reverting all `'UPDATE graph_templates_graph SET title_cache = ? WHERE local_graph_id = ?'` and similar queries to `'UPDATE graph_templates_graph SET title = ? WHERE local_graph_id = ?'` but I'm afraid to break something else.

**Comment by cigamit** [comment]
Please create a pull request.  I'm a little off the reservation at the moment.  Busy time.

**Comment by cigamit** [comment]
Okay, I see the problem now.  If you have the allow the user to override the graph title checked, then we should keep the graph title.  So, for you, you have to make sure that the checkbox to the left of the Graph Template graph title is checked, and then apply the updated lib/functions.php from the develop branch.

So, this issue is resolved.  Thanks for your input!
