### ISSUE TITLE
Incorrect recovering of downed hosts with SNMPv3

### ISSUE THREAD

**Issue by begetan** [Cacti/cacti#1469]
We are using cacti for monitoring hosts by SNMPv3.  For some hosts connected via IPsec tunnel via unstable lines with bad ping (up to 300-400)  we found that host will never come back to Recovering and Up state.

Here is **System Utilities** -> **Log Administration** entry:
`2018/03/12 07:45:09 - CMDPHP WARNING: SNMP Error:'Timeout (500 ms)', Device:'192.168.253.21', OID:'.1.3.6.1.2.1.1.3.0'`

At the same time, if we open Console -> Device manualy, it is recognizing by the system.

![gw-hk-ok](https://user-images.githubusercontent.com/17225934/37280686-ccba8cd4-25ee-11e8-8bae-249206eae8bc.png)

At the time of "Down" state the tcpdump on remote host shows interaction. Device is responding correctly.

```
tcpdump -pni tun0 host 192.168.253.21
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on tun0, link-type RAW (Raw IP), capture size 65535 bytes
11:50:14.315883 IP 10.128.1.71.52392 > 192.168.253.21.161:  F=r U= E=  C= GetRequest(14)
11:50:14.315978 IP 192.168.253.21.161 > 10.128.1.71.52392:  F= U= E= 0x800x000x1F0x880x800x920x3C0x580x6C0x310xEF0x160x5A0x000x000x000x00 C= Report(32)  .1.3.6.1.6.3.15.1.1.4.0=4469
11:50:14.498854 IP 10.128.1.71.52392 > 192.168.253.21.161:  F=ar U=authOnlyUser E= 0x800x000x1F0x880x800x920x3C0x580x6C0x310xEF0x160x5A0x000x000x000x00 C= GetRequest(28)  .1.3.6.1.2.1.1.3.0
11:50:14.498922 IP 192.168.253.21.161 > 10.128.1.71.52392:  F=a U=authOnlyUser E= 0x800x000x1F0x880x800x920x3C0x580x6C0x310xEF0x160x5A0x000x000x000x00 C= Report(32)  .1.3.6.1.6.3.15.1.1.2.0=7835
11:50:17.501865 IP 10.128.1.71.52392 > 192.168.253.21.161:  F=ar U=authOnlyUser E= 0x800x000x1F0x880x800x920x3C0x580x6C0x310xEF0x160x5A0x000x000x000x00 C= GetRequest(28)  .1.3.6.1.2.1.1.3.0
11:50:17.501980 IP 192.168.253.21.161 > 10.128.1.71.52392:  F=a U=authOnlyUser E= 0x800x000x1F0x880x800x920x3C0x580x6C0x310xEF0x160x5A0x000x000x000x00 C= Report(32)  .1.3.6.1.6.3.15.1.1.2.0=7836
```

SNMP walk from the Cacti host is working fine also!

I suppose there is an issue in handling SNMP queries in main poller cycle. Since no complains on this issue from other users, I think this is SNMPv3 related topic.

It's hard to reproduce the ussue, because I don't know exactly how to move host to Faulty down state.
It is appears on version 1.1.29 - 1.1.36

Here is current version on Ubuntu 17.10
```
dpkg -l | grep cacti
ii  cacti                              1.1.36+ds1-1                         all          web interface for graphing of monitoring systems
rc  cacti-spine                        1.1.29-1                             amd64        Multi-Threading poller for cacti
```

**Comment by cigamit** [comment]
What method are you using for your availability check.  Need more information.  Likely using a bad availability check.  Update your spine to latest as well.

**Comment by begetan** [comment]
@cigamit  I've tried different methods for check - SNMP, ping (icmp, udp) - there is no difference.

Right now I have one downed host for troubleshooting.  Usually removing and recreating can solve this problem, but I want to fix it generally.  If I recreating host before deleting old one, it also stacks in the same state and shows the same ping latency: Current = 561.98

It was default timeout 400 msec before. Due to network issue latency has increased to 561 msec, so probably host was marked as down. Since that moment host not going to recovering state. I set up timeouts for 3000 msecs so timeout is not an issue. 

I've upgraded cacti-spin to 1.1.35-1.  - the latest from ubuntu bionic repository.
Please feel free to ask any kind of diagnostic.

**Comment by cigamit** [comment]
Well, you will have to get information from the log's into this ticket.  If your snmpget's timeout during data retrieval, the host will be ignored.  But the ping in the important thing.  You need to put a high enough timeout and retries so that if you have a bad connection.  I generally use SNMP Uptime for everything that has that counter and I specifically avoid UDP ping, which is tricky at best.  ICMP is good, but when you have huge numbers of devices and using spine with threads, it causes a lot of interrupt chatter with the threads since ICMP responses interrupt all threads.

**Comment by begetan** [comment]
When trying to configure downed host I found that it's behavior tight with another host on completely different location.I found a relation in configuration - both hosts had the same SNMP engine id. 

There are empty values SNMP Engine ID (v3) for SNMP Engine ID (v3) in Cacti.  Could you explain please how Cacti handles SNMP engine ID, especially in case of collision?

**Comment by cigamit** [comment]
Cacti stores the engine id in the host table.  When using spine, we first open a session using the SNMP details including the engine id, and if that session is able to be created, we just collect the data.

If you have two devices with the same engine id, we really don't check for that.  If you think that we should, speak up.

**Comment by cigamit** [comment]
One more thing to add.
By default, Net-SNMP will attempt to detect the Engine ID of the host during setup of the Net-SNMP session.  When you force it through setting, it will attempt to communicate with the device using the EngineID you specified.

Right now, if you are using php-snmp, the EngineID is NOT supported, though we have worked around this by calling the binaries directly in these cases.  However, if you want to simplify things then you should consider removing php-snmp.  We will be working with the PHP Group to enhance php-snmp moving forward, but you won't see it to a mainline Linux distribution for some time due to the lag of the various Linux distributions in adopting newer PHP releases.
