### ISSUE TITLE
div tags found in settings

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1514]
in cacti 1.1.37 div tags found in mail/dns settings.

![cacti](https://user-images.githubusercontent.com/35136010/38228005-a6a4a48a-371e-11e8-9d1a-da30b9d500b4.png)

**Comment by YangSheghui** [comment]
Hello, friend! Please see https://github.com/Cacti/cacti/issues/1504, The problem has been solved.

**Comment by chathurag** [comment]
@YangSheghui How can we solve it? You only mentioned that you solved it?

**Comment by pautiina** [comment]
@YangSheghui you must update code from develop branch or wait for release for you system

**Comment by netniV** [comment]
@chathurag The latest development code is v1.2 which is still going through major development and I would not advise jumping straight to that for a production system at this time.  Due to the nature of the issue and that of #1513, and #1504 there may be a hotfix of 1.1.38 produced to allow production systems to display these properly.  At the end of the day, they are display issues though, not functionality issues.

**Comment by cigamit** [comment]
We hope to have a fix for this issue over the weekend.  It has been fixed in develop.  @ronytomen will cherry pick the commits for a 1.1.38 release.
