### ISSUE TITLE
Value above RRD maximum value

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1523]
When a value goes above the maximum held in the RRD file, this can result in data not being shown.  How easy or hard would it be to verify that a value wasn't above expected maximums and raise a warning if it was?

(see https://forums.cacti.net/viewtopic.php?f=12&t=58500&p=272104#p272104)

**Comment by cigamit** [comment]
I created an audit page to be able to bring into Cacti all the rrdtool info data.  With that in place, you could audit the actual peak values for the rrdfiles and perform such a comparison.  To date, we have been assuming that the data template is king, and we all know that people tweak things, which is why the audit function/page was created, but never published by the way.  If we can rely on the values in the data template, we could make quick work of this.  Maybe we simply do the following:

1) Add maximum and minimum columns to the poller item table
2) Do the compare in lib/poller.php and log as appropriate.
3) Update the push_out* functions to include the maximum and minimum columns
4) Do NOT force a re-population of the poller cache on upgrade.  If users want the auditing, they can run the CLI at their leisure.

We used to re-populate on upgrade and it was a disaster for larger sites when performed interactively.  This does not seem too difficult.

**Comment by cigamit** [comment]
Been giving this some thought.  We can perform a check during dsstat runs to report values above the maximum value.

**Comment by cigamit** [comment]
Closed as this is fixed in the 1.3 branch.
