### ISSUE TITLE
"Management -> Graphs -> Device" drop-down items

### ISSUE THREAD

**Issue by okeozkilic** [Cacti/cacti#1525]
Management -> Graphs
Device drop-down box shows only limited number of items (30) when using a web theme other than "Classic".

I can confirm that this situation exists in v1.1.36 and v1.1.37.
Tried on Linux and Windows using browsers Vivaldi, Chrome and Firefox.

**Comment by netniV** [comment]
This is by design.

**Comment by okeozkilic** [comment]
Please correct me if I am wrong. If I have 100 monitored devices, I will never be able to see all 100 of my devices in the drop-down in question, unless I pick "Classic" web theme.

**Comment by netniV** [comment]
In themes other than Classic, the drop down is an autocomplete drop down so as you type the list automatically filters. This keeps the UI responsive especially if you have over a thousand devices.

**Comment by okeozkilic** [comment]
Before going any further, I just want to make some things clear on my side. I am using Cacti for more than 8 years and I like the software and totally appreciate the effort. I am not trying to point my finger at a feature and tell something like "hey guys I found a bug in your nice software please fix it". 

I always used Cacti with the "Classic" interface and I see nothing wrong with it. I decided the change my theme to something else and ended up with this issue. This issue of mine is totally easy to fix. I go back to my good old "Classic" view and everything's going to be fine. 

This is the first time that I posted an issue on this site and the answers that I got made me feel like I am pointing at something totally unimportant. I really want to improve this software with this tiny discussion of mine and I personally think that the devil is in the details. 

If this really is a feature, I believe that it should also be valid for the the "Classic" view. Furthermore, I will not have more that 1000 devices but I will have about 150 and 30 list limit seems to be a little bit less than Cacti can handle.

I am not trying to be arrogant and I apologize if I offended anyone.

**Comment by netniV** [comment]
Sorry, was in a rush last night as normally I give far more 'fluffy' answers.  So, you will be pleased to know I'm going to write this with a bit more care this time 👍 

<hr> 

There are differences between the "Classic" and more modern themes.  The classic theme maintains the way that Cacti has always been.  As such, it doesn't always have some of the more dynamic elements in the same way (user settings via the top right, dynamic filtering on drop downs, etc).  

On the point about the number of devices, I agree you may only have a handful but the interface needs to be written with large installations in mind.  I am currently monitoring only 132 devices with 1800+ graphs and around the same in datasources.  That number is growing and will continue to grow.  However, I am also aware that there are datacentre's that have many more than that.  If I have 10 graphs per device, imagine what a large datacenter installation would have as they would be graphing UPS Power / Load, Device Power, CPU, Network, Disk, Memory, Temperature, etc.

<hr> 

Like yourself, when I first started using the modern themes, it bugged me. I didn't see all the rows for all devices so I increased the defaults within the default settings and my user settings to be 1000 instead of 30.  Unfortunately, I then found that the site was a lot less responsive (might have even timed out at times) so quickly dialled that back to a level I found acceptable.  Additionally, I then found out, that if you started typing in the combo boxes, you can see the devices filtering in the drop down but again I didn't like the defaults so I adjusted this and never looked back.

The settings you can adjusts are under Console -> Settings -> Visuals.  My current settings are for 100 rows per page and 1000 autocomplete rows.  As the autocomplete is only returning a small value (id,name), then it's not a massive hit.  However, when things start scaling up I'd definitely have to reduce that because of the database queries involved.

Oh and whilst you are in there tweaking your settings, you will notice that there is an option to completely enable or disable autocomplete.  I've never noticed that before as I always have it on but you will see there is explicit text stating that autocomplete is not used in the classic theme.  

Finally, if you feel that I've managed to address your questions/issue, feel free to close this.  If you find as you are using cacti you have additional issues unless it's directly related, open them as separate issues.  

<hr>

If sometimes myself or one of the other group members seem short in our reply, it's not because we are trying to dismiss you, rather that we do this in our spare time so sometimes we answer quickly as that usually helps point someone in the right direction.  To give you two examples:

- It might mean we have around five minutes to scan through 18 different issues that have been updated (as I did last night because my wife was making a cake for a baby shower and things kept going wrong so we only got to bed at 4am!).  

- Where as a month ago, my wife was very kindly supporting me by not complaining as I spent 10 hours a night over two weeks starting with a single issue that grew into others, trying to get a plugin to work just right (damn you RouterConfigs! but I really appreciate that we are lucky to have people willing to do that testing with us so that it is far more stable and reliable). 

Hopefully after reading my long waffle you'll be feeling a bit better about your experience with Cacti as we aim to try and have a positive user experience with it.  It's one of the main reasons I became a massive contributor to the project because I had mostly great experience (just got to stop finding those pesky bugs).  If you are happy with it, you are more likely to mention it to someone else.

Like me, if you feel that some feature or UX (UI experience) isn't quite right, you are encouraged to raise it as an issue/question.  Some will be shot down in flames using our spare rocket launchers (not really they just are closed with a reason as to why it wouldn't work), others may float around a while, the good ones get taken on board and applied.  

My view is that Themes are like football teams. Everyone favours a different one for different reasons, but i'll not hide that I'm not a massive fan of the classic theme as it reminds me of things I left behind 15 years ago 🏇 👍 😸

**Comment by cigamit** [comment]
Well that was fast ;)  I have a few things to say.  I'll chime in in just a few minutes.

**Comment by okeozkilic** [comment]
Thank you for the answers/clarifications guys.
