### ISSUE TITLE
Update Fontawesome from 4.7 to 5.0.10

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#1527]
Is it possible to upgrade awesome font? New version has more than 300 new icons. I would like to use it in my plugins and in old version missing few icons.

Thank you

**Comment by netniV** [comment]
It could be done.  It will need care though because FA changed from a single prefix of 'fa' to four prefixes in v5.0.  Not an impossible job, but it would need a change in most pages.   We can potentially get around it with their 'shim' for the time being but again that would need testing.  I think that would be up to @ronytomen as to which milestone to aim for on that one.

**Comment by cigamit** [comment]
We need a license check as I know they were planning on making some changes in the 5.x release.  Email is out for checking that.  It's likely a nit as long as the classes are close.  I've been waiting for this too.  So, once we get approval, it should go quickly.

**Comment by cigamit** [comment]
Looks like the license check went well.  Does anyone want to take a crack at a pull request?

**Comment by cigamit** [comment]
Wasn't too bad.  Open a separate ticket if you find issues.
