### ISSUE TITLE
User Admin generates SQL error if user is not part of any groups

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1590]
![123](https://user-images.githubusercontent.com/31933126/39408721-49a13434-4c0d-11e8-8e14-08c662fc7019.png)

What are these errors? Can you tell me?

Thanks

**Comment by netniV** [comment]
The device is added to the error, which you see because you've blocked it out on the image above.  The SQL error is by the SQL handler which knows nothing about devices as it's generic across the whole application.  

The error in blue seem to be related to editing a user and having no policies applied.  The poller output is a different issue where your poller didn't complete in time (or process all items).  If you search here or the forums (forums.cacti.net) you'll find plenty of posts on how to handle that.

For now, I'm going to rename this ticket to match the SQL errors.  I suspect that the user you are using is not part of any groups when you are trying to edit a graph etc.

**Comment by cigamit** [comment]
I have tried to reproduce this to no avail.

**Comment by cigamit** [comment]
Just figured it out.  Should be resolved now.
