### ISSUE TITLE
Login - Keep me signed in

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#1624]
Keep me signed in option in Login does not work as it get automatic logouts

**Comment by cigamit** [comment]
What Cacti release?

**Comment by chathurag** [comment]
1.2.0

**Comment by eschoeller** [comment]
I have experienced problems with this off and on for some time, haven't had the chance to troubleshoot it. I figured it probably had something to do with having multiple Cacti instances and not setting $cacti_session_name differently between them.

**Comment by netniV** [comment]
It usual is.  The main reason being that one tab will kill off the session which affects the rest.  So, even though a realtime tab will expect to just refresh, it’ll find the session gone and be logged out just like all the others.

In truth, the logic should probably be looked at so that a timestamp is used of last activity, rather than just a timeout.  That way, ra realtime tab can keep the session going.  There are security implications to that as it would override the default logic for logging a user out after a set period of inactivity on those other tabs just because you have one realtime tab.

**Comment by chathurag** [comment]
But in usual case if this option is selected program should not ask the password again. Try other popular websites such as facebook.

**Comment by cigamit** [comment]
This is the behavior and it has worked for some time.  I suspect this issue was due to a CSRF issue.  CSRF has been addressed.  Update the latest develop branch and let us know if it's reproducible after that.

**Comment by cigamit** [comment]
It's true that you should have separate session names per Cacti install if you have more than one per host.

**Comment by cigamit** [comment]
Resolved.
