### ISSUE TITLE
 POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 4, Graphs

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#1664]
What do these warnings mean?

![cacti0](https://user-images.githubusercontent.com/31933126/41347084-2eaae6e2-6f3b-11e8-87c3-35d2a08e6153.png)

**Comment by netniV** [comment]
From my understanding, that normally means that the poller did not get a response (either positive or negative) from trying to query that device/script.  Most of these seem to be traffic graphs, but can you confirm the template you are using?

**Comment by pautiina** [comment]
Maybe just need run: cli/poller_output_empty.php

**Comment by tyit** [comment]
@netniV 
It was always good to issue these warnings on these two days. The template is good.

**Comment by tyit** [comment]
@pautiina 
![cactiapi](https://user-images.githubusercontent.com/31933126/41385816-7b4a0b5c-6fb0-11e8-87d0-43672f570390.png)
Did I run this or did it out

**Comment by tyit** [comment]
![cacti6](https://user-images.githubusercontent.com/31933126/41396244-d6bff46a-6fe2-11e8-88eb-3408157eef7f.png)

**Comment by tyit** [comment]
@pautiina  
The warning still exists. What should I do next?

**Comment by pautiina** [comment]
I ran out of ideas. Perhaps you have incorrectly set the time in crontab?

**Comment by tyit** [comment]
![cacti](https://user-images.githubusercontent.com/31933126/41631730-cc1de58c-7468-11e8-8719-4e0ee6d80135.png)

**Comment by netniV** [comment]
So, out of the 263 data sources, 2 seem to be failing.  If you look in the Clog tab, you'll see what those two are because the Clog will automatically parse the numbers into the data source names (you've blurred them out above presumably as they are name you don't wish us to see).

What I would then do is see what fields/queries those two data sources are trying to run.  To do that, take the names and look at the Console -> Utilities -> System Utilities -> View Poller Output

Take the Script command, copy and then run at command line.  that should hopefully show you what output the script is getting trying to perform that query.

**Comment by hellspawndf** [comment]
I have the same problem... 
 **POLLER: Poller[Main Poller] WARNING: Poller Output Table not Empty. Issues: 371, <bla bla bla> Additional Issues Remain. Only showing first 20**

I had Cacti running for a long time, more than 3 years, same hosts (more actually, in my current installation I deleted some hosts I no longer needed to monitor), no problem at all. Thing started go south when I migrated from SLES to Ubuntu. I have less than 50 devices monitored by now.

Here is what I have done by now:

- Migrated to a server with more RAM and better CPU;
- Gave up on using PHP 7.2 on Ubuntu and switched to PHP 5.6;
- Switched from apt default installation and installed Cacti 1.1.38 from source;
-  Since nothing changed, I installed  Cacti 1.2.0 from source;
- Since it could be an upgrade issue, I finally gave up migrating and started a fresh enviroment, adding the hosts and Cacti configuration from scratch;
- Disabled all plugins;
- Changed some Mysql settings, specially max_heap_table_size and tmp_table_size;
- Upgraded monitor plugin to develop version;
- Tried spine, both Ubuntu default apt version and develop version. Different error in clog, but even larger gaps on graphs.
- Tried all sorts of Poller settings.

Still no luck, keep geting random Poller Output table not empty and gaps in graphs :(
Completely ran out of ideas. Can you please help?

**Comment by netniV** [comment]
Set your logging levels to MEDIUM which will show poller stats, plus the output of the various data sources it is querying.  That should help you identify what is causing you an issue.  Also, look at the STATS lines in your log file, this shows how many things are being polled and how long it's taking.

**Comment by netniV** [comment]
Also, when you switch from CMD.PHP to Spine, you need to make sure that you have the correct settings against the poller.  In 1.2, there are some new options against individual pollers, not just as a global setting.  This are migrated as part of the source upgrade (depending on when you pulled the sources).

**Comment by hellspawndf** [comment]
Thanks, netniV. What should I see? Couldn't find anything worth mentioning.

One thing I noticed: on the device list, current and average ping time for the devices that show _Poller Output Table not Empty_ are 100000

**Comment by netniV** [comment]
You notice the time since last poll are showing less than a second?  That would suggest that you have something spawning multiple pollers at the same time.

**Comment by hellspawndf** [comment]
Man, I feel so stupid right now. Got caught between "all from source" in SLES and "apt rulz the world" in Ubuntu. I have been strugling with this for weeks, and you finally killed it!

When I installed Cacti from apt, it created an /etc/cron.d/cacti calling the poller. As I removed Cacti with "apt-get remove --purge" I thought anything like it was done and manually add a line on my /etc/crontab.

No matter which poller I tried or  how many "Maximum Concurrent Poller Processes" I set I could never (and never would) solve my problem.

Thanks very much, netniV! You are a life saver!!
