### ISSUE TITLE
Data Query Cisco WLC Interface Assoc Query Issue

### ISSUE THREAD

**Issue by xn85turbo** [Cacti/cacti#1681]
I imported the template cacti_host_template_cisco_wlc_-_5508.xml from "Errors importing templates with deprecated hashes #1244" that was attached on 2-7-18 and all seems well when I imported without error. I replaced the "Cisco_WLC_Radios.php" from the same post. When adding a device and trying to create graphs I do not get any output from Data Query [Cisco WLC Interface Assoc Query]. All other queries return data so I can create graphs.

No Items Found
This Data Query returned 0 rows, perhaps there was a problem executing this Data Query.You can run this Data Query in debug mode From there you can get more information.

When I run debug mode I can see output of 8 devices.
Total: 0.100000, Delta: 0.100000, Executing script for list of indexes '/bin/php -q /usr/local/share/cacti/scripts/Cisco_WLC_Interfaces_Assoc.php '<IP>' '<community>' '2' 'index'', Index Count: 8

Graphs not Working:

CPU
Associations

Graphs Working:

WLC Memory Usage
Tempature
Utliization
Rouge Alerts
WLC Station Authentication Algorithm
WLC Station CCX
WLC Station Cipher
WLC Station EAP Type
WLC Station Policy
WLC Station Protocol
WLC Station Status
WLAN Associations
Power Levels

Graphs Missing; I guess they are from the Cisco_WLC_Interfaces_Assoc.php:

Noise
Interference
Channels
and what ever else that I am forgeting from that list.

I am using CentOS 7.4

Apache-2.4.6
php-7.2.6
MariaDB-10.2.15

**Comment by xn85turbo** [comment]
More information to assist.

Cisco WLC Versions;

Software	Model N.	
8.3.140.0	AIR-CT5520-K9
7.6.130.37 AIR-CT5508-K9
8.0.140.0	AIR-CT5508-K9
7.4.110.0	AIR-CT5508-K9

When I hit cancel it seems to be hanging on the associations "Data Query [Cisco WLC AP Assoc Query]". When I add all the other graphs individually they add just fine.

**Comment by cigamit** [comment]
Have you attempted to contact the author of this template?  Have you asked for help on the forums?

**Comment by netniV** [comment]
The other thing I would do is an SNMPWALK to the remote device from the cacti server command line for oid `11.3.6.1.4.1.14179.2.2.13.1.1`, the chances are it isn't actually responding with data to you.  

If there is no data returned, check that you have configured the SNMP on the remote device and against the device settings in cacti.

Since this is a 3rd party template issue, please post on the forums (https://forums.cacti.net).  If it is later determined that there is a core issue (unlikely due to the other graphs working) then we could re-open this.
