### ISSUE TITLE
No Graph when exceeding 30G bandwidth

### ISSUE THREAD

**Issue by Tand33h** [Cacti/cacti#1712]
Good day!

This is to report the issue that I encountered about the Cacti Application. The outbound graph is not display when it is reach 30G of data traffic.
The equipment polling the data is Cisco ASR9010.
![image](https://user-images.githubusercontent.com/41322584/42804978-252cbd36-89dd-11e8-8994-5b38b3e9f69b.png)

**Comment by Tand33h** [comment]
Hi netniV,

I already did search within the forum but I cant find the answer that is why I post it. May I ask for your help if you can share the link for the answer. Thanks.

**Comment by pautiina** [comment]
You need tune  your red file by rrdtool. 
https://forums.cacti.net/about30269.html

**Comment by Tand33h** [comment]
Hi Pautiina,

I will try this recommendation. Hope it will work. Thank you!

**Comment by cigamit** [comment]
It will work.  You can use the Data Source Info Debug to see the max values.  Likely what happened is that your interface returns an invalid ifHighSpeed, which is what we use to set the RRDfile maximum value.  Contact your equipment vendor to have them set the 'correct' value.  If that vendor is Net-SNMP, simply open a ticket with them.  Bond interfaces are ugly sometimes and have been known to have invalid ifHighSpeed in the past.  Hopefully Net-SNMP guys have fixed this in a more recent release.

Since this is a well known problem, I'm simply going to close this ticket.  The Cacti Forums have litterally dozens of "how to fix this" articles on this subject.
