### ISSUE TITLE
[1.2.0] Customize popup window timeout

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1764]
Would it be possible to change the 5 seconds sets by default to smallest values (1 or 2 seconds) for this kind of popups ?
![image](https://user-images.githubusercontent.com/35721406/43366135-adae0250-9338-11e8-92a2-f63bede8eaf0.png)

In fact it would be for all notification.

**Comment by cigamit** [comment]
I don't really want to bring the timeout down too far.  We have it as a popup with a timer to give you an opportunity to read the message, or to be present long enough for you to stop it by pressing pause.  However, in some cases, we may wish to not even show the message.  For example, only show when there is an error.  Will have to give that some thought.

**Comment by cigamit** [comment]
Yup, I'll be looking at it in possibly an hour or so.  Have some things to take care of fist.

**Comment by cigamit** [comment]
You did not attach the SQL dump.  You will need to do that.

**Comment by jackouille-ch** [comment]
Sorry, has been sent just now per email

**Comment by netniV** [comment]
We introduced this because previously it was not clear at all if an action had actually occurred.  This led to issues where things appear to be working but do not.  By knowing you should see the dialog at the end of the operation, you know that if you haven't seen one the operation either hasn't begun, or is still running.

See https://github.com/Cacti/cacti/issues/1366 and https://github.com/Cacti/cacti/issues/1366
