### ISSUE TITLE
[1.2.0] Defines in global_array.php are in wrong location

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/cacti#1794]
Hi I got he following log entries, any idea?
![image](https://user-images.githubusercontent.com/35721406/43710913-5db22292-9971-11e8-9b5c-5b6a4e5bdaea.png)

**Comment by netniV** [comment]
This is an issue we identified late last night but hadn't recorded yet.  The problem comes in that the global_arrays include file is being performed more than once.  There are a number of ways to tackle this problem, but the simplest will be to add the following at the top of the file beneath the "<?php":

```php
if (!defined('CACTI_INCLUDE_GLOBAL_ARRAYS')) {
        define('CACTI_INCLUDE_GLOBAL_ARRAYS','included');
```
and then add a single curly bracket at the bottom of the file:
```
}
```

Note, this is a `quick fix` so may not be what's in the next update but if you are replacing your files, you shouldn't notice anything.

**Comment by jackouille-ch** [comment]
ok done, waiting for further logs entries...

**Comment by netniV** [comment]
Yeah I already seen that on my system.  I'm going to more thoroughly test this but the reason is that the include/global.php file is using include_once() rather than require_once() and as such, there are includes not being included.

**Comment by netniV** [comment]
```
PHP Fatal error:  require_once(): Failed opening required '/global_arrays.php' (include_path='.:/usr/share/php') in global.php
```
This is what happens when you change it to require once 👍

**Comment by netniV** [comment]
Actually the above error was my own fault.  Rushing too much, I'm going to properly test this out and come back to you with a proper fix.

**Comment by netniV** [comment]
It seems that global_arrays() is a bit of a special case.  This gets included directly by various functions and the reason for this is to not have to add a `global $array1, $array2, $array3, etc` to functions that heavily use them.  

This does to me, seem to raise an issue of whether there could be issues of one part changing a global array but another not seeing that because it is redefining it locally.

For the sake of restoring things as they were, reset your global_arrays.php to the one you downloaded and then apply the following patch:

```diff
diff --git a/include/global_arrays.php b/include/global_arrays.php
index 96208c0f..6804cb82 100644
--- a/include/global_arrays.php
+++ b/include/global_arrays.php
@@ -1685,11 +1685,6 @@ $i18n_weekdays_short = array(
        'Sat'   => __x('A textual representation of a day, three letters', 'Sat')
 );

-define('DB_STATUS_ERROR'  , 0);
-define('DB_STATUS_WARNING', 1);
-define('DB_STATUS_SUCCESS', 2);
-define('DB_STATUS_SKIPPED', 3);
-
 $database_statuses = array(
        0 => __('[Fail]'),
        1 => __('[Warning]'),
diff --git a/include/global_constants.php b/include/global_constants.php
index 71659ba0..c7b9b5fe 100644
--- a/include/global_constants.php
+++ b/include/global_constants.php
@@ -416,6 +416,11 @@ define('EINPROGRESS',     115);
 define('EREMOTEIO',       121);
 define('ECANCELED',       125);

+define('DB_STATUS_ERROR'  , 0);
+define('DB_STATUS_WARNING', 1);
+define('DB_STATUS_SUCCESS', 2);
+define('DB_STATUS_SKIPPED', 3);
+
 if (!defined('PASSWORD_DEFAULT')) {
        define('PASSWORD_DEFAULT', 1);
 }
```

Turns out I'd put these defines in the wrong place.

**Comment by jackouille-ch** [comment]
Maybe something's missing on my side:
root@cacti2:/usr/share/cacti# diff --git a/include/global_arrays.php b/include/global_arrays.php
diff: unrecognized option '--git'
diff: Try 'diff --help' for more information.
root@cacti2:/usr/share/cacti#

**Comment by netniV** [comment]
Just pull down the latest code, this has now been added.

**Comment by jackouille-ch** [comment]
Ok used the latest release from today:
![image](https://user-images.githubusercontent.com/35721406/43726249-ec13f056-999e-11e8-8dc4-1406785f46ce.png)
It works better now but some new errors have appeared, opening tickets for it.

**Comment by netniV** [comment]
We investigating some more issues that the latest develop has brought to light.  Let us work through them and we'll come back to you once we have identified the reasons.

**Comment by cigamit** [comment]
This is resolved now.

**Comment by jackouille-ch** [comment]
Yes, thanks
