### ISSUE TITLE
[1.1.37] Failed to search on logs

### ISSUE THREAD

**Issue by jpobeda** [Cacti/cacti#1801]
I don't know how to explain it but... I found Mactrack disabled and went to the logs to find the date/time and when filtered by "mactrack" or "MACTRACK" I got these odd messages

![chrome_2018-08-07_08-49-48](https://user-images.githubusercontent.com/13456559/43740454-5a39387c-9a1f-11e8-8cff-9dda6db5eb61.png)

![chrome_2018-08-07_08-47-30](https://user-images.githubusercontent.com/13456559/43740459-5d18802a-9a1f-11e8-888d-5539a2c9c89d.png)

If I type "mac track" or "MAC TRACK" in these pop-up windows don't come up. I tried a few random searches to spot a pattern but nothing so far.

If you need further details please let me know.

**Comment by netniV** [comment]
Make a note of where the cacti.log is up to, then try and enter the term and see if any new entries appears.  Best to use the command line rather than the gui for viewing the log just to be sure

**Comment by jpobeda** [comment]
I don't follow .. can you please be more specific? what do you want me to run from cli?

The issue only comes up when I try to filter the research using that word, if I clear the filter and search something else it works fine.

**Comment by cigamit** [comment]
There were some changes related to how regular expressions were handled that have been fixed in 1.2.  I suspect that is the problem @jpobeda .  Check the debug log and see what is being passed to the backend for the variable rfilter.  It should be an base64 encoded string.  Then on the backend, it should be auto decoded and handled properly.  My guess is the detection logic was broken due to the variable being double decoded.  The validate functions auto-decode, but @netniV had added something to decode in the main file, just remove that.  Take a look at this commit.

https://github.com/Cacti/cacti/commit/5435503e4ad24bc4c04d7e00aeaac71a0dfc32e0#diff-ae42e87f97ae6ca1d0d9de86104583e1

**Comment by jpobeda** [comment]
So the base64 seems to be fine in the url, if you decode 'bWFjdHJhY2s' gives you 'mactrack'
`/cactidev/clog.php?rfilter=bWFjdHJhY2s%3D&reverse=1&refresh=5&message_type=-1&tail_lines=500&filename=cacti.log&`

Also tried filtering 'clog' and got another strange result
Again, URL looks fine, if you decode 'Y2xvZw', gives you 'clog' BUT on the search field it gest replaced by 'rZ'
`/cactidev/clog.php?rfilter=Y2xvZw%3D%3D&reverse=1&refresh=5&message_type=-1&tail_lines=500&filename=cacti.log&`

See it in action here:
![2018-08-07_13-39-33](https://user-images.githubusercontent.com/13456559/43749272-84d1dc10-9a47-11e8-9a9a-f4802e41d369.gif)


I checked on test vm I've got running 1.1.38 and that part of the code didn't make it to 1.1.38 version by the looks of it and the issue is still present. T

ested on 1.2.x version and works ok.

**Comment by cigamit** [comment]
lib/clog_webapi.php lines 109-111, delete them.

**Comment by cigamit** [comment]
look for the same thing in utilities.php, remove them too.

**Comment by jpobeda** [comment]
Jebus! I was looking at 1.2 code that's why I couldn't find it. All good now, thanks.

**Comment by jpobeda** [comment]
OK, lines 884-886

**Comment by jpobeda** [comment]
Thanks for the help

**Comment by cigamit** [comment]
Well, we seem to keep chipping away at this thing, bug's all along the way.  Need less bugs more features if that is possible.
