### ISSUE TITLE
Poller issue and gaps in graph in1.1.38

### ISSUE THREAD

**Issue by capricorn800** [Cacti/cacti#1887]
I have installed version 1.1.38. I am seeing gaps in graph. Also below error.
 POLLER: Poller[1] WARNING: Poller Output Table not Empty.  Issues: 12, DS[9, 14, 14, 9, 10, 10, 11, 11, 12, 12, 13, 13]

MariaDB [cacti]> select * from poller_output;
Empty set (0.00 sec)

I am also seeing the attached picture if that has something to do with it.

Data Collectors -> Main Poller -> Status Unknow/Down. 
I am trying to upload the pic as well.

The new graph shows up after long time. This was not like this in previous versions.

**Comment by netniV** [comment]
Change your log settings to be medium and see what output is being returned.  The chances are you are polling from or to a different server that has not been configured properly for Cacti to poll.

**Comment by capricorn800** [comment]
I believe your answer is related to poller error I am getting.
I changed the poller from cmd.php to spine and then I was not getting Poller error. Everything was fine for few hours but now something the graphs doesnt appear on the main page like blank and if I go into the graph I can see them. I am checking the log but no error. Now I opened the page again and I can see the graph on the main page.

What about this?

Data Collectors -> Main Poller -> Status Unknow/Down.
I am trying to upload the pic but dont find the place where I can upload it.

**Comment by netniV** [comment]
Just simply paste it into the text box.

**Comment by capricorn800** [comment]
![image](https://user-images.githubusercontent.com/42100004/44990056-270b3f00-af90-11e8-9721-22976c1283fa.png)

**Comment by capricorn800** [comment]
Just saw this message:
09/03/2018 18:30:01 - POLLER: Poller[1] WARNING: There are '2' detected as overrunning a polling process, please investigate

**Comment by capricorn800** [comment]
Just saw the same behaviour again. The main page of the graph was not showing anything. I went into Time view graph and was able to see the graph. Move around different tabs and then the graph is showing fine again.

**Comment by cigamit** [comment]
Likely your cron is not setup properly.  Go under poller and see what the cron interval and poller interval are.  Ensure that your poller interval is the smallest data source profile you are using.  So, if you are using the 30 second data source profile, the poller interval needs to be 30 seconds.  The cron interval needs to match the GUI too.  Could you also have a floating clock (in other words is this a VM)?

**Comment by capricorn800** [comment]
My Cron Interval and poller interval is set to Everyone 5 minutes in GUI and I have the below in /etc/cron.d/cacti

*/5 * * * *     cacti   /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1

Its a physical machine.

**Comment by cigamit** [comment]
There is then some issue with your data collector.  Could it be that php is running out of memory?  Have you checked your memory_limit in php.ini?  You should setup you php.ini error_log = /tmp/php.error and look for errors.  What would appear to be happening is that php is crashing for some reason, which causes Cacti to detect overrunning processes.  You should careful review the log also to see what is happening with "SYSTEM STATS:" around the overrun time.

If this was anything other than some setup issue, we would be seeing more of this issue here.  I would like to suggest that you obtain support on this issue from the forums.  If you can find a concrete bug, then please re-open another issue here, but I think your issue is environment related.
