### ISSUE TITLE
yearly graph only show six month

### ISSUE THREAD

**Issue by EduGonzalez** [Cacti/cacti#1918]
Hi, 
I`am using Cacti a few years ago. I noticed in the yearly graphs only show information about the last six month. How can I configure it to show me information about the last year completely?

![image](https://user-images.githubusercontent.com/7471085/45383448-3e25de80-b5d9-11e8-9d79-d7b874564472.png)

This is my RRA configuration:
![image](https://user-images.githubusercontent.com/7471085/45383479-54339f00-b5d9-11e8-9f81-db970ffc2280.png)

The poller interval is "every 1 minute".

Can you help me?

regards

**Comment by netniV** [comment]
Can’t do the math right now but it is likely that your timespan x number of steps doesn’t cover two years.  At least that is the calculation I think it is but I just woke up so I might have that wrong.

**Comment by EduGonzalez** [comment]
Can you show me the right configuration?
If I add a new RRA and associate it with the data templates, that can  break my database? They are running on production environment

**Comment by cigamit** [comment]
@EduGonzalez, you have likely upgraded from an earlier version of Cacti where someone created a Data Source Profile (it wasn't called that before), that included both the 1 minute and 5 Minute RRA's as having the number of steps of 1.

This was done incorrectly (by someone who likely had no idea what they were doing), and it is the principal reason why we moved to Data Source Profiles, which remove a lot of confusion around managing Cacti RRA settings, and has also made support multiple Poller Intervals a breeze relatively speaking.  I know that little of this information helps you out though.

My suggestion is that you create a new Data Source Profile that truly represents your historical data gathering needs and migrate all your graphs to that profile.  Of course this is like saying "start over" though to the average user.

With enough technical experience, you could retain your historical data, and that will likely require someone to assist you (since you already posted here with a question that to a seasoned Cacti person tells us that you don't exactly understand Cacti's principals from top to bottom) with technical skills as to how to take data from old RRDfiles, and feed it into new RRDfiles automatically.

We don't provide or perform consulting services here, but you may be able to goto the Cacti Forums and find someone who has the requisite technical skills to help you out of this situation.

**Comment by cigamit** [comment]
See the Data Template pages below for another clue.

![datasourceprofiles](https://user-images.githubusercontent.com/957322/45461771-7c4efb00-b6ca-11e8-99d6-aa9c951622dd.png)

**Comment by cigamit** [comment]
See the image below for another hint.

![datatemplatepage](https://user-images.githubusercontent.com/957322/45461803-95f04280-b6ca-11e8-80a8-4a2912eb104f.png)
