### ISSUE TITLE
Cacti graphs are broken and Thold not working properly

### ISSUE THREAD

**Issue by mail3dexter** [Cacti/cacti#1963]
Hello,

I have recently created 2 new Cacti boxes with version 1.1.38.
RRD data migration, MySQL database migration all went well from 0.8.8a to 1.1.38
However, I am seeing that intermittently, my graphs are broken.
As in, for 1 particular polling interval, it doesn't poll and fails somewhere.
Now, I was having thold plugin with 0.8.8a which I had removed after upgrading as thold is now part of base cacti.

Due to a specific internal failure (which happens once and not continuously), thold is alerting falsely.
My polling interval is 5 mins and thold is set to alert if it fails for 10 mins i.e. 2 runs.
Even for 1 failure, it is alerting and spamming.

Can someone help me in solving these 2 problems?
I tried to Rebuild Poller Cache on both of them but no luck.

From the logs, I can see this line before this happens:
PCOMMAND Device[9] WARNING: Recache Event Detected for Device

**Comment by netniV** [comment]
Thold is NOT part of Core, it is a separate plugin but it, as with any other 0.8 plugin will become disabled because they are not compatible with 1.x without changes.  You can download the latest version of thold from the github repo

https://github.com/cacti/plugin_thold/

I believe there is a known recache issue on 1.1.x, which I believe we have resolved in the 1.2 development branch.  There is also a potential reindex problem in prior to 1.2 which we believe we have tackled this weekend. 1.2 is currently in development about to hit beta, so if you are going to do an upgrade / testing the latest versions, I would recommend jumping straight to 1.2.  1.2 also has some fixes for database upgrade problems that have been resolved  relating to upgrades of systems prior to 1.x.

**Comment by mail3dexter** [comment]
Yes my bad, I had used the same thold plugin which you had mentioned.

I do not have to jump to the development branch for now as my boxes are used for production.

I would go back to 0.8.8 since there is no stable version available in 1.1.x 😢

**Comment by netniV** [comment]
Potentially, tbh I haven't investigated it that far.  I just know there was a recent commit that corrected it.

**Comment by netniV** [comment]
Oh and I'm using 1.2 in production.  But then I can fix my own issues 👍 I would like to say though, I haven't had to fix anything on my production box.

**Comment by cigamit** [comment]
Let's move this discussion to the forums or to the thold issue tracker.  Belongs in the forums though.
