### ISSUE TITLE
[1.1.38] enable Devices on cacti 

### ISSUE THREAD

**Issue by Son-CygnusX-1** [Cacti/cacti#2014]
hi everyone,
I have a problem, i can not enable Devices Local Linux Machine, status: unknown
clog.cacti:
10/04/2018 10:18:54 - CMDPHP PHP ERROR WARNING Backtrace: (/host.php: 62 form_actions)(/host.php: 228 poller_update_poller_cache_from_buffer)(/lib/utility.php: 541 sizeof)(CactiErrorHandler)(/lib/functions.php: 4585 cacti_debug_backtrace)
--
10/04/2018 10:18:54 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /var/www/cacti/lib/utility.php on line: 541

**Comment by netniV** [comment]
Can you provide the following information:

- OS
- Cacti Version
- If applicable:
   - Backtrace
   - Plugin name/version

Also, are there any errors in the web server log and/or cacti log?

**Comment by Son-CygnusX-1** [comment]
Information:
- Ubuntu 18.04 
- php 7.2
- Cacti 1.1.38

**Comment by netniV** [comment]
OK, so PHP 7.2 and Cacti 1.1.38 are not compatible.  You'll need to drop down to 7.1 or 5.7 to maintain compatibility.  The error you are getting is because PHP 7.2 will not accept FALSE to sizeof() or count() any more without generating a warning.  As you've already noticed there was a bug in the `poller_update_poller_cache_from_buffer`

Secondly, the device in question is probably enabled, but you are just not getting any SNMP information from the device.  Make sure you have have set the SNMP version and options, you can also set a Downed Device Detection too.

**Comment by Son-CygnusX-1** [comment]
thanks you so much! i will try to fix it now.
