### ISSUE TITLE
Installer - Log filenames should include version and there should only be one

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#2025]
When the installer creates a log file the name should include the version of Cacti, this way the logs are automatically separated for each install/upgrade.

Secondary, the installer should create one log file.  It appears to create 2 log files right now:
- `install-complete.log`
- `install.log`

The files appear to be the same log message, just different and I'm not sure what they mean, values between the square brackets.  This should be one log and double spaces should be removed from the lines.

**Comment by netniV** [comment]
There should be no log files unless you enable the logging option via the DB.  They are meant for developer debug only.

**Comment by netniV** [comment]
The logs are designed for developer-use only.  Due to the amount of logs that can be generated, there is a double write because one is for the 'section' that is being records, the other is combined with everything being records.  

For logging levels, it works based on the Cacti Poller Verbosity flags.  So, it utilises the global logging level, coupled with the sections logging level.  Which ever is greater, is used and checked against before logging the output.

This all enables a great deal of flexibility in being able to track down bugs in the installer, as we can raise the debugging level for individual sections.  We can see what is happening for one section or utilise the complete log to see more.  Whilst you could use `grep` to produce similar effects, it was far more efficient this way.

**Comment by netniV** [comment]
So, we are dropping the highlander model, but I will make it so that unless the primary "log_install" flag is set, then no files are output.
