### ISSUE TITLE
[1.2.0 beta 1] docs/build.sh uses bash syntax while declaring /bin/sh

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#2104]
During my build of cacti 1.2.0 beta 1 for Debian I noticed the following:
```
cd docs ; ./build.sh
./build.sh: 11: [: unexpected operator
Generating TXT documentation...
Generating HTML documentation...
Generating PDF documentation...
./build.sh: 79: [: NO: unexpected operator
Generation of documentation completed successfully
```
This is due to the fact that the == is bash specific. Changing it to = resolved this issue.

```
paul@testavoira ~/packages/cacti/cacti $ cat debian/patches/valid-sh.patch 
Description: script sh-bangs to /bin/sh but uses bash
Author: Paul Gevers <elbrus@debian.org>

Index: cacti/docs/build.sh
===================================================================
--- cacti.orig/docs/build.sh
+++ cacti/docs/build.sh
@@ -8,7 +8,7 @@
 
 # Set distro option - removes build sources
 DISTRO="NO"
-if [ "${1}" == "--distro" ]
+if [ "${1}" = "--distro" ]
 then
        DISTRO="YES"
 fi
@@ -76,7 +76,7 @@ then
 fi
 
 # Remove build stuff if distro option set
-if [ "${DISTRO}" == "YES" ]
+if [ "${DISTRO}" = "YES" ]
 then
        rm -Rf build build.sh
 fi
```

**Comment by ronytomen** [comment]
This would be my fault.  

I do have a question concerning why this is an issue for Debian. Are you building packages from the repositories?  If so, I’m assuming it is for unstable?

**Comment by ronytomen** [comment]
Also, documentation has been moved out of Cacti main repository into the Documentation repository. The Beta 2 release tarball correctly has the built HTML documentation, there is not need to run the `build.sh` script for documentation.

**Comment by paulgevers** [comment]
Please see issue #310 for my rationale to run the script. Finding the source there, I though that that issue was closed.

**Comment by paulgevers** [comment]
> If so, I’m assuming it is for unstable?

Currently I am targeting experimental. There has been requests to make it available ASAP for Ubuntu 18.04 via my ppa as well.

**Comment by ronytomen** [comment]
As far as packaging from the distros, the release tar file should be considered the source.

Now, I do understand the rational for wanting to build from repository source for targeting `experimental`.  I have concerns about this generally, because we will and have broken things badly in the `develop` "unstable" branch in the past.  While we try not to, things like database corruption issues and other catastrophic issues can persist in `develop` until they are analyzed and resolved.

That being said, tell me what will help you more easily package Cacti for distribution and we can work towards that common goal!

**Comment by ronytomen** [comment]
Also, fixed the Bash versus Shell syntax problem in the documentation repository build script.
