### ISSUE TITLE
[1.2.0 Beta 2] Multiple poller_replicate processes

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#2120]
I upgraded from Beta 1 to Beta 2. I happened to notice that I had two poller_replicate processes kick off for the same remote data collector. I have a feeling the first one didn't finish during the poller cycle it was called from, and then a subsequent poller cycle started up and believed that the same replication needed to happen so it fired off another poller_replicate process. Eventually (I believe after the 2nd try) the replication finished and this didn't continue to cascade onto further cycles. And I'm not sure if this is by design, but maybe poller_replicate needs to determine if it's being run for the same poller ID already.

**Comment by netniV** [comment]
I believe that there is an issue already for this. Thomas Urban is the one who reported it if I recall correctly. But your information will help to explain things a bit more.

**Comment by cigamit** [comment]
Technically, there can be more than one, but it's highly unlikely.  There are two possible cases:

1) A database is blocked due to a locking operation (like a manually running database backup that locks the entire database), and poller processes stack up since crontab is not database locking aware.
2) A gui Full Sync happens at the same time the poller runs.

We can not fix the first issue, though I recommend if you do run database backups, do it in a non-locking way.

**Comment by eschoeller** [comment]
OK. I'll mention that to my db admin to see what they say.

**Comment by cigamit** [comment]
We should a database focused process interlock.  It's something that has been done for other plugins, just not in the core so much.  But ilet's say that the database is on NFS and NFS hangs, you might get a multitude of these processes stacking up due to the pollers stacking up.  Another reason I never put MySQL tables on network storage.

**Comment by vancefan** [comment]
I got the similar problem, my cacti system have 3 pollers, data collector can only running on main poller, when I association to other pollers, it can only work for no more than one hour, then there is no data collected. 

When I try to edit the device, it shows: ERROR: Device[2247] not found. Please perform Full Sync!
![image](https://user-images.githubusercontent.com/15649628/48386611-7c509300-e72d-11e8-91d7-e83433104c02.png)

For the latest 1.2.0 Beta 2, I don't find any Sync button in the collect page.

This case bother me for nearly a month, cacti have the devices exceed 1 thousand, now I got same data loss since there is only one poller working,  and I can't roll back to my previous version. 
By the way, I don't have any database backup mention in the previous comment.
Please instruct how to investigate and fix the issue.

**Comment by netniV** [comment]
With the latest develop version, I can see Full Sync on the Data Collectors page:
![image](https://user-images.githubusercontent.com/9052188/48400993-d9454c80-e71f-11e8-898d-37ec65b3736a.png)

**Comment by vancefan** [comment]
Yes, but Full Sync is not work.

It still asking for full sync.
![image](https://user-images.githubusercontent.com/15649628/48419948-2c58e700-e794-11e8-92e3-7d25abdd9674.png)

**Comment by cigamit** [comment]
@vancefan, Looks to me you have a database connectivity issue.  Make sure you test the connections from the Data Collectors to ensure that you have good connections to the remote databases.  You can do this from the Data Collectors -> Edit interface.

**Comment by cigamit** [comment]
@vancefan, you also have to make sure that the Remote Data Collector hostnames are the hostnames of the remote databases as well.  If it's set to 'localhost', then it will not work.

**Comment by cigamit** [comment]
@eschoeller, there was an issue with the earlier beta X that might have caused this to happen.  Don't think it will happen now.  If it does, please open a new ticket with detailed process list information including the start time of the process.

**Comment by max6491** [comment]
after upgrading to 1.2.2 i am still having the same issue that was reported 

"ERROR: Device[2] not found. Please perform Full Sync!"
