### ISSUE TITLE
[1.2.0 beta2] Undefined variable: output_disabled in file: <path>data_input.php

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#2138]
[The Debian CI results](https://ci.debian.net/data/autopkgtest/testing/amd64/c/cacti/1237434/log.gz) for the first Debian package of 1.2.0-beta2 show the following (multiple times):
```
2018/10/30 23:22:10 - ERROR PHP NOTICE: Undefined variable: output_disabled in file: /usr/share/cacti/site/data_input.php  on line: 701
```
Probably worth looking into.

**Comment by netniV** [comment]
Thanks Paul, I'll take a look tomorrow.

**Comment by netniV** [comment]
So there are two fields that get set `output_disabled` and `save_alt_message`.  Both of these were set inside an if/then/else block, with no default predefined.  I'm not sure which way the default should be so I've opted for false since that is what is set if no results are returned on the previous query.

This has now been committed to the development code.
