### ISSUE TITLE
Device with SNMP "not in use" is still able to discover SNMP devices, etc.

### ISSUE THREAD

**Issue by groentebroer** [Cacti/cacti#215]
When a device has SNMP configured "not in use", you can still add SNMP data queries, (for example SNMP - interface statistics) which will also give results.

Creating graphs voor SNMP data queries is possible, but the RRD files are never created, (I think because at that stage the SNMP device settings is checked as expected).

But I should not be able to create any SNMP related graphs when "not in use" right?

**Comment by cigamit** [comment]
Good point.  Let me toy with that for a minute.

**Comment by cigamit** [comment]
Well, this might be harder than expected since we have some data queries that are script based, and those scripts can include SNMP calls based upon replacement variables.  So, this one is not an easy fix.  I'll fix the easy one, but these more difficult ones, it would appear to be a lot of effort with little gain.  Still thinking about it.

**Comment by cigamit** [comment]
Resolved this one as far as I will take it for now.
