### ISSUE TITLE
cacti 1.2.0 beta2 weird phenomen with Available Disk Space Template

### ISSUE THREAD

**Issue by Axel577** [Cacti/cacti#2170]
Hey guys,
There is a windows server with two local disks.
When I add disk one (100GB), I get that graph:
![grafik](https://user-images.githubusercontent.com/28043745/48625641-17589f80-e9b0-11e8-8650-c2a2c966d561.png)
That's correct.
When I add the second disk(60TB), I get that graph:
![grafik](https://user-images.githubusercontent.com/28043745/48625698-38b98b80-e9b0-11e8-8e57-30d380e84093.png)
So first of all, I'm wondering where do those colors come from? And second, total and used values aren't correct. It says total 36T, used 56 T. In real, the disk has an amount of 60 T, used are 40T.

Can someone explain that phenomen to me?

It's the same graph template.
![grafik](https://user-images.githubusercontent.com/28043745/48625842-a2399a00-e9b0-11e8-8bc1-bd1bc7243aa8.png)

**Comment by netniV** [comment]
If you put the device into debug mode, you should be able to see the results in the cacti.log which show what value was returned.  

30TB   = 32212254720
32-bit <  2147483647

So, technically, anything about 2 terabytes could result in a strange result on windows because I'm sure it doesn't return 64-bit counters via SNMP only 32-bit ones.

**Comment by cigamit** [comment]
I suggest you move away from Microsoft's snmpd implementation and install NetSNMP.  Once NetSNMP is installed, there should be a snmpd.conf option called: realStorageUnits.  Set this setting to 0, and then you should be able to support very large disks.

This issue is due to Microsoft being in the stone age when it comes to snmpd.  In fact, their WMI tool also remains in the stone age when it comes to these traditional metrics.

**Comment by cigamit** [comment]
@Axel577, since this is more a Windows issue than a bug closing.  See my earlier comments.
