### ISSUE TITLE
When querying SNMP, prevent duplicate timeout errors from appearing

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#2188]
realtime is graphing but the log displays:

CMDPHP  PHP ERROR WARNING Backtrace:   (/cmd_realtime.php[201]:cacti_snmp_session_get(),  /lib/snmp.php[473]:SNMP->get(), CactiErrorHandler())
--
2018/11/28 10:45:14 - ERROR PHP WARNING: SNMP::get(): Fatal error:  Timeout in file: /var/www/localhost/htdocs/cacti/lib/snmp.php  on line:  473
2018/11/28 10:45:13 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd_realtime.php[201]:cacti_snmp_session_get(),  /lib/snmp.php[473]:SNMP->get(), CactiErrorHandler())
2018/11/28 10:45:13 - ERROR PHP WARNING: SNMP::get(): Fatal error:  Timeout in file: /var/www/localhost/htdocs/cacti/lib/snmp.php  on line:  473
2018/11/28 10:45:04 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd_realtime.php[201]:cacti_snmp_session_get(),  /lib/snmp.php[473]:SNMP->get(), CactiErrorHandler())
2018/11/28 10:45:04 - ERROR PHP WARNING: SNMP::get(): Fatal error:  Timeout in file: /var/www/localhost/htdocs/cacti/lib/snmp.php  on line:  473
2018/11/28 10:45:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/cmd_realtime.php[201]:cacti_snmp_session_get(),  /lib/snmp.php[473]:SNMP->get(), CactiErrorHandler())
2018/11/28 10:45:03 - ERROR PHP WARNING: SNMP::get(): Fatal error:  Timeout in file: /var/www/localhost/htdocs/cacti/lib/snmp.php  on line:  473

**Comment by netniV** [comment]
That will be because your autocomplete rows and number of rows to display in a table are both configured to the same value.  Autocomplete boxes, however, allow you to type and find other entries.  It prevents them slowing large systems down by listing every device in the source code unnecessarily.

**Comment by majed17** [comment]
Well I would disagree that it is unnecessary, As that would force me to remember names of unnecessary things

**Comment by netniV** [comment]
Most people can narrow down by typing at most a couple of letters vs experiencing a non-response page... I'm guessing most people would prefer the former.

**Comment by netniV** [comment]
I noticed that you commented this does not occur in Beta 2.  I'm not aware of any change between Beta 2 and Beta 4 that would affect the above.  The only thing we have done is taken steps to properly record a timeout when it occurs so it's likely that you are now correctly seeing an issue where it was hidden before.

That said, I've made a minor change to the code to suppress extra error messages from appearing so that it isn't recorded twice.  If you update to Beta 4 again, download the latest lib/snmp.php and it should resolve things for you.

**Comment by netniV** [comment]
OK so that message basically reports that spine is unable to write to the cacti.log file so it will not continue (thus preventing you issues with not getting proper errors reported).  To run spine, use `sudo -u <poller user> /path/to/spine`.  

The likely hood is that you are running with three accounts, your login user, your website user (eg apache or www or www-data) and your poller user (eg cacti or cactiuser).  When you run spine, you are running it as your login user which likely doesn't have the permission to write directly to the cacti log file.

**Comment by netniV** [comment]
To be clear, I had thought of adding an option to report to `stdout` if the log was not available (eg, when run as a login user), but the changes are, without using the -u on sudo, you wouldn't have permissions to the RRA files either so it's worth the restriction to ensure proper file access.

**Comment by majed17** [comment]
Well thanks that solved the problem!

**Comment by cigamit** [comment]
I'm going to have to re-open this one.  We capture this exception, but it should not be fatal.  It should have been ignored in our IgnoreHandler, and it wasn't being.  So, I'll be updating lib/snmp.php shortly I'll need you to test again with this and your PHP version.

**Comment by cigamit** [comment]
Please test with this update.

https://github.com/Cacti/cacti/commit/6f96ed1c26921fbda1ec7d73b6e73e85308952bd

**Comment by majed17** [comment]
I'd like to change the values but in the first file, 
end of mib is on line 4265

**Comment by cigamit** [comment]
Yea, you have to do that on 1.2, or better yet develop.

**Comment by majed17** [comment]
Well i have 1.2 and that is why i asked, anyway i risked and did the changes, and nothing new is in the logs just poller cycles running as usual. anything else needed to be done?

**Comment by cigamit** [comment]
Nope, we are good.
