### ISSUE TITLE
Cacti Gaps in Graphs

### ISSUE THREAD

**Issue by don1406** [Cacti/cacti#2208]
Hi,

I have Cacti version 1.1.38.
In my graphs (almost every graph, even localhost) there are gaps.
It has maybe something to do with cron ??
I have attached some screenshots.
Does anyone know what i have to do to resolve this issue?

Thanks for your help!

Donovan
![cacti gap 1](https://user-images.githubusercontent.com/34776452/49790221-fe80a700-fd2d-11e8-96ad-a693d542c0fc.PNG)
![gap 2](https://user-images.githubusercontent.com/34776452/49790222-fe80a700-fd2d-11e8-8e35-c86b1937ee16.PNG)

**Comment by cigamit** [comment]
This issue should be handled in the forums.  I'll close here, but you should carefully check your cacti log file for errors and poller overruns.  Also, with regard to the gaps, you should check your timeout's as, for example, if the ping times out, you will not get valid data.  I suspect since the ping value is so low, that you may be having problems with your poller completing on time.  Using the spine poller is the preferred method of data collection.

Once Cacti 1.2 is released, you should also reduce your full sync frequency to a lower amount, if you are running multiple data collectors as well as most of the sync is handled upon making changes to the Cacti database.
