### ISSUE TITLE
When will Cacti 1.2 be released officially on cacti.net

### ISSUE THREAD

**Issue by chathurag** [Cacti/cacti#2216]
When is cacti 1.2.0 release in cacti.net?

**Comment by netniV** [comment]
We are hoping to have it ready for the new year.  Whilst the core code has been done and very few issues have been raised since Beta 4, there is documentation and other things to update including the Microsoft Windows(TM)-based installer.

Anyone following the documentation repo will notice quite a few changes over the past week.

**Comment by cigamit** [comment]
Happily closing, though, we will have to do a 1.2.1 next weekend due to all the little bugs we have found.  Watch develop in the mean time, we don't plan on adding any big features until we get 1.2.1 out the door.

**Comment by cigamit** [comment]
That was 8 months of blood sweat and tears.  Good band too.
