### ISSUE TITLE
Custom Watermark for diferent tree/branches

### ISSUE THREAD

**Issue by DoubleBeast** [Cacti/cacti#2222]
Hello everyone, i was thinking in the possibility of adding diferent watermark depending on the tree/branches of each device, it seems usefull when you manage diferent companies or departaments and want to have specific watermarks, i really don´t know if this is viable but will left it here for your consideration.

**Comment by cigamit** [comment]
Not very viable, and probably not something we would add in at this time. Its not a feature that would benefit everyone, just a very small amount of use cases.

While moving the Watermark from a global setting to Graph Template or even individual Graph setting would be feasible.  Tying that back to a Tree / Branch would be difficult at best, as graphs have no knowledge on what tree it is on during generation.  You would be moving it to a "Run Time" setting where the display layer would have to pass data to say what branch / tree we are currently generating for since a graph can even feasibly belong to multiple trees / branches.  Also, image caching would throw a few issues in the way also.

**Comment by netniV** [comment]
There is a more viable option of putting it at the site level (since each device can have a site associated to it).  However, that is not likely to satisfy your requirements if you are producing graphs for specific interfaces used by specific customers.  

Again, as @cigamit 	said, this is very much a "nice to have" feature that most users will not take advantage of.  So, even if we put it to the feature request list (by taking it as an enhancement), it's not likely to be a feature implemented for a while.

**Comment by DoubleBeast** [comment]
thanks for the response guys, it sound like a lot of work with very low benefits and as you say it could be helpful to very few people, i will close this, thanks again.
