### ISSUE TITLE
Installation wizard does not detect RRDtool version correctly

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/cacti#2282]
The rrdtool version detection used for the installation wizard is not correctly detecting/setting 1.7.0.  however in the Technical Support page, the version detection is working.  Yes, on Windows ;)

![image](https://user-images.githubusercontent.com/5741811/50789655-d21c6400-12b4-11e9-8d55-29151796eab6.png)

![image](https://user-images.githubusercontent.com/5741811/50789662-d6e11800-12b4-11e9-9d4e-19811913d80d.png)

**Comment by cigamit** [comment]
Interesting.

**Comment by cigamit** [comment]
Windows does not leverage standard error to standard output redirects.  Problem solved.

**Comment by netniV** [comment]
Actually, windows does use standard redirects so I'm confused why this is an issue.  I am often using 2>&1 when running a command so I would recommend that we research this further.

https://support.microsoft.com/en-gb/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout

**Comment by BSOD2600** [comment]
This is still an issue with the latest 1.2.5 dev branch.

![image](https://user-images.githubusercontent.com/5741811/60938996-00422700-a28b-11e9-8f7a-6bec08f2017d.png)

**Comment by netniV** [comment]
I will try and get a windows environment setup tonight.

**Comment by netniV** [comment]
I have found the issue with this.  The installer will always try and upgrade to the highest supported RRDTool version from now on regardless of what was previously defined in the settings.   Also, ensured that all areas are using the same RRDTool version detection code rather than one using an array and another using the output value which may not be a valid setting any more.

Patch to follow.
