### ISSUE TITLE
Add Graph template to SNMP Data query documentation no longer applicable

### ISSUE THREAD

**Issue by rfc4711** [Cacti/cacti#2286]
Documentation on release 1.x suggests that a graph template can be created on a new Data query

https://docs.cacti.net/manual:100:3a_advanced_topics.3a_snmp_data_queries#walkthrougha_new_snmp_data_query

however in release 1.1.38 the user is presented only with a choice of pre-existing graph templates which may not match the new SNMP_XML query.

Did the workflow change for a graph template to be existing before a data query can be added? If yes the documentation needs to be corrected. In the associated data Templates there are also no "Suggested Values" available from the XML input definitions.

**Comment by cigamit** [comment]
We are trying to update the documentation.  Could use some help.  We all have day jobs besides this little hobby.

**Comment by DoubleBeast** [comment]
what kind of help do you need, i´m not a programer so the code is out of my reach but let my know if i can help with the documentation.

**Comment by cigamit** [comment]
That would be awesome.  So, if you want to help, there are a few walkthroughs that are very dated.  What you can do it recreate the images for the walkthroughs using the modern theme.  If you use the GitHub GUI, you can clone the documentation repository, and then you can browse the images directory and you will see all the images that are in the old 'Classic' theme.  

So, we need to update those to the new modern theme, and maybe, since we changed the topic of RRA's to Data Source Profiles, modify the text and the images slightly.

I use windows and the snipping tool plus paint if I need to draw squares around text for emphasis.  If you are using a Mac, they would be different tools, but it's essentially the same process.  The images are created at the 1280 x 720 resolution with the browser at either 100% or 90% zoom.  Try to match that.

Once you have the images and text updated, just submit a pull request. It'll require you to get a GitHub account, but that should not be a big deal.  Thanks again for offering to help.

**Comment by DoubleBeast** [comment]
Great @cigamit i will take a look to that tonight.

**Comment by netniV** [comment]
@DoubleBeast I know it's been almost a year, but did you get to this?

**Comment by netniV** [comment]
Closing this issue for now.  If any documentation is provided, it will be a pull request on the documentation repo rather than here anyway.
