### ISSUE TITLE
Upgrade 1.2.0 to 1.2.1 errors

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#2316]
root@ctcv-cacti2:/var/www/html/cacti/cli# php upgrade_database.php --forcever=1.2.0
Upgrading from v1.2.0
Upgrading from v1.2.0 (DB 1.2.0) to v1.2.1
xx
################################
[Fail]       -   DB Exec Failed!, Error 1054: Unknown column 'deleted' in 'where clause'
+------------------------------+
UPDATE host SET deleted='' WHERE deleted IS NULL
################################

################################
[Fail]       -   DB Exec Failed!, Error 1054: Unknown column 'deleted' in 'host'
+------------------------------+
ALTER TABLE host MODIFY COLUMN deleted char(3) NOT NULL default ''
################################

**Comment by netniV** [comment]
We will need to check that the cacti.sql file has the updated field, thanks for pointing that out.  But you should always run upgrade_database.php --forcever=<previous release> when you are updating on develop.  That ensures that any database upgrades are applied.  As you were running the 1.2 beta, you still needed to do that again for the 1.2 release (using 1.1.38 as the previous version).

**Comment by smiles1969** [comment]
So you are saying ANY time I pull down new code run that upgrade regardless if there is a change to cacti.sql? I can certainly do that, but it doesn't make sense to me. If cacti.sql contains the schema for the database, and there are no changes to it, how does the db schema change?

**Comment by netniV** [comment]
Not quite what I was getting at.  

If you do want to use git on production servers, you should use the release/<version> branches. That way when you upgrade between the releases, it's a full upgrade.

Develop is cutting edge and whilst we love people to run it and report any issues, it is a special case.  This is because the code and database are in constant flux.   Best thing to do is keep an eye out for updates to both the cacti.sql and the install/upgrades folder.  If either changes, run the upgrade_database.php script (especially if it's changes to the latest version file).

Personally, my production ones are on develop and I use the above check to know when to run the upgrade again.  For customer sites that I maintain, I use the release branches on my own repo so that I can apply specific site fixes if I need to.

With development code we are not always updating the cacti.sql file or the audit code.  This is normally done when the development code updating the database is submitted but not always as there could be other bits coming too.  It is normally re-done right before release but we unfortunately failed to do that for the 1.2 code as it got overlooked.
