### ISSUE TITLE
Core should use plugin hooks instead of direct and/or hard coded plugin functionality

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2318]
Just found two hardcode about detect/use plugin function under cacti/lib.
Beside current cacti PIA, Can we use 'hook' methodology to callback 'thold' and 'maint'?

```php
lib/api_automation.php:2808:            if (api_plugin_is_enabled('thold')) {
lib/snmpagent.php:325:  if (api_plugin_is_enabled('maint')) {
```

**Comment by netniV** [comment]
How do you mean callback?

**Comment by ddb4github** [comment]
From most cacti code.  Cacti core call plugin function by api_plugin_hook or api_plugin_hook_function.
So I prefer to "Cacti core" keep this clean behavior

**Comment by netniV** [comment]
I see what you are referring to.  I would agree with this though it would have to be as a feature request since it's a change in functionality not technically a bug.  

We would need to synchronise the versions between THold and Cacti core.  THold has been undergoing a review and upgrade at the moment so it may be worth raising a corresponding issue on the THold repo and linking these two together.

That way, @TheWitness who has been updating THold can get the hooks in place and then when we come to develop 1.3, this can be implemented as a feature request.
