### ISSUE TITLE
Unable to see all data sources in Graph Item editor

### ISSUE THREAD

**Issue by F-i-f** [Cacti/cacti#2361]
I have a cacti instance running the latest (1.2.1) on Fedora 29 using the system provided packages.
I cannot see all my data sources in the graph item editor.
To reproduce:
- Open the Cacti Console
- Click on Management > Graphs
- Click/edit a non-template graph.
- Select one of the graphs items
- You are now in the graph item editor ( /cacti/graphs_items.php?action=item_edit&id=XXX&host_id=XXX&local_graph_id=XXX )
- Under graph items > data source, the pop-up does not list all possible data sources.
- Changing the host or template does not help.

For the graph I'm trying to create, I have 48 possible data sources for the given host/template, but only the first 30 data sources are showing up.

**Comment by netniV** [comment]
That is by design.  Check your system settings for the option to adjust how many appear.  Having too many appear at once causes the browser to become unresponsive.  You can start typing characters of a datasource that you do know of and it should filter down listing showing entries including the one you want.

I have suggested that we look into an enhancement to this if you check out https://github.com/Cacti/cacti/issues/2190
