### ISSUE TITLE
[1.2.1] A settings change duplicate entries in the database

### ISSUE THREAD

**Issue by DavidLiedke** [Cacti/cacti#2403]
**Describe the bug**
A settings change copy a lot of "settings" table entries in the same table. 

**To Reproduce**
1. Go to 'Configuration --> Settings"
2. Make a configuration change for example: log level medium --> low
3. Click Save
4. Control the setting
5. You will see nothing changed in the GUI

**Screenshots**
**Before the change:**
![firefox_2019-02-12_13-52-46](https://user-images.githubusercontent.com/25581728/52636863-05fb3280-2ece-11e9-9af8-f91c20063dac.png)

Search "log_verbosity" in the settings table:
![firefox_2019-02-12_13-55-13](https://user-images.githubusercontent.com/25581728/52636890-14494e80-2ece-11e9-9ee0-98b36a82dd0d.png)

**After the change:**
![firefox_2019-02-12_14-00-03](https://user-images.githubusercontent.com/25581728/52637079-90dc2d00-2ece-11e9-9bec-6b1404dc8096.png)

Search "log_verbosity" in the settings table:
![firefox_2019-02-12_14-00-21](https://user-images.githubusercontent.com/25581728/52637087-933e8700-2ece-11e9-8e6c-57b2cda890ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 65

**Server**
 - OS: openSUSE 15.0
 - DB: MariaDB 10.2.15
 - PHP: 7.2.5

**Comment by netniV** [comment]
Can you run 'show create table settings\G` ?

**Comment by netniV** [comment]
When I attempted this, I got errors:
```sql
> insert into settings values ('log_verbosity','10');
ERROR 1062 (23000): Duplicate entry 'log_verbosity' for key 'PRIMARY'
```
So, if you have duplicates, that suggests that your table isn't being defined properly as:

```sql
Create Table: CREATE TABLE `settings` (
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `value` varchar(4096) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by DavidLiedke** [comment]
MariaDB [cacti]> show create table settings\G
*************************** 1. row ***************************
       Table: settings
Create Table: CREATE TABLE `settings` (
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `value` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
1 row in set (0,00 sec)

**Comment by DavidLiedke** [comment]
Now i have seen in my old database backups that this behavior happends after the upgrade from 1.2.0 to 1.2.1. Each day my database backup getting bigger.

**Comment by netniV** [comment]
The weird part here is that you are missing the primary key.  That should have been there since before 1.0.0.  You will likely need to remove the duplicate entries before you can apply the primary key

**Comment by netniV** [comment]
If you have the latest development code, run the cli audit to see if it finds any more discrepancies.

**Comment by DavidLiedke** [comment]
Thanks. I will give you an feedback asap.

**Comment by DavidLiedke** [comment]
I´ve copied the develop branch to a second location and connected it to my database. Restore a database backup without the duplicates and run the script in the cli folder. I had a lot of other tables with missing entries in the database. What I do not understand is why I have these missing entries. Because i had no errors or something else during the cacti upgrades.

At the moment it looks good.

@netniV Thanks for your help 👍

**Comment by netniV** [comment]
In the past, the installer was a bit lax on upgrading.  If it failed, it carried on unless it was catastrophic and may have mentioned it failed but it wasn't really obvious.  One thing I did when i re-wrote the installer, was to give every database interaction a status, and that status is checked after each upgrade section.  Then I collapsed any section that was successful so you can clearly see those that don't work.

Now, I think in your case, because you have been keeping up to date with all past upgrades, you only ran the 1.2.0 upgrades from 1.1.38 or 1.1.37 which would have been successful as they were only adding a column or two.  If you were to run an upgrade from the 0.8.8 code to 1.2.x now, whatever caused your structure to misalign would actually suspend the upgrade under the new installer and require you to correct the issue.

It's also why since the beginning of January we had a larger increase in the number of tickets as more people attempted the upgrade and found either database or configuration issues that were previously overlooked.  Issues from CLI PHP modules that were never enabled to these DB ones were likely historically always there causing minor issues in the background that were hardly if at all noticed.

Hopefully, they will bring a lot more stability too.
