### ISSUE TITLE
cacti 1.1.7 smtp mail issue

### ISSUE THREAD

**Issue by khansa-abdalla** [Cacti/cacti#2425]
I'm facing the problem with sending email 

![image](https://user-images.githubusercontent.com/34414291/52942905-99bc7b00-3374-11e9-92d1-49187dbade6b.png)

I follow related issues but I can not find that section of code in lib/functions.php as described in https://github.com/Cacti/cacti/issues/1155#issuecomment-354068135

**Comment by netniV** [comment]
The code has changed quite a lot since the 1.1.7 days as the PHPMAiler class has been updated, more functionality was put into the mailer function, etc.  So, back dating that work to the 1.1.7 isn't something that we would do.  

Once thing you need to ensure is that apache is allowed to make network connections or using SMTP will always fail.
