### ISSUE TITLE
Reinstate missing plugin hooks for 'custom_logout_message' and 'custom_denied'

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2426]
In 0.8.8x,  Cacti auto-logout will forward to:
```
  If "Web Server Auth"
    hook: custom_logout_message
    Or buildin  "logout message", reminder "close browser to end session"
  else
    index page
```
Since 1.x,  Cacti auto-logout will forward to:
```
  if timeout
    buildin  "logout message", reminder "close your browser or login again"
  else If "Web Server Auth"
    hook: custom_logout_message
    Or buildin  "logout message", reminder "close your browser or login again"
  else
    index page
```
Issue:
1.  Keep consistency between similar behavior and hook,   So "timeout-->logout message" should support hook:custom_logout_message too
2.  Does "Web Server Auth"  support re-login? To-Be-Verified. 
3.  Current "Permission Denied" UI is more like "Logout/Login", prefer to support a new hook like 'custom_denied_message'

``` Text
2019-02-18 original issue body
-------------------------------------------------------------------------------------------------
lib/auth.php miss to support hook 'custom_logout_message' like logout.php
Actually, lib/auth.php should redirect to permission_denied.php if authentication failure.

Steps to reproduce the behavior:
0. Register something to hook: custom_logout_message
1. Access User(edit)->Permission(tab), 
2. Unselect a permission of test page, and click save.
3. Directly access test page by browser URL bar
4. See error message

Expectation:  redirect to permission_denied.php to support custom_logout_message```

**Comment by netniV** [comment]
In 1.3, the permission_denied.php file will likely disappear as I had already had plans to make the dialog an inline display rather than separate file.

In 1.2 and below, the permission_denied.php is only used by `graph.php` and `graph_view.php`, the realm permissions are handled by include/auth.php

custom_logout_message is used by logout.php, and is specific to being logged out of the system.  That is only hooked if the authentication method is set to 2 (Web server auth).

**Comment by ddb4github** [comment]
> In 1.3, the permission_denied.php file will likely disappear as I had already had plans to make the dialog an inline display rather than separate file.

dialog might be not safety if someone directly access unauthorized page from URL bar. e.g. from browser history/bookmark/....
dialog should be valid under click->jQuery->ajax load mode

> In 1.2 and below, the permission_denied.php is only used by `graph.php` and `graph_view.php`, the realm permissions are handled by include/auth.php

Prefer to combine them as one file/function

> custom_logout_message is used by logout.php, and is specific to being logged out of the system. That is only hooked if the authentication method is set to 2 (Web server auth).

Refer updated issue body

**Comment by netniV** [comment]
When I say dialog, I do mean functionalised, so that the permission denied is displayed and the page content suppressed.  It's the output that to me looks like a dialog so bad terminology on my part.

I think the idea of providing a custom_denied message can be useful for your own look/feel to it using the same RESKIN options that can be used on logout and having login operate the same way too.

**Comment by ddb4github** [comment]
Yea:thumbsup:,  Both custom_denied(for denied) and custom_logout_message(for timeout)

**Comment by cigamit** [comment]
Can you do a pull request on this.  Should be strait forward.

**Comment by netniV** [comment]
There is a re-jig required for it, I will take it as an enhancement because there are a number of changes related that I was looking at (but we ripped back out because it was too close to the beta release).

**Comment by cigamit** [comment]
Marking as a bug since these hooks were removed some time ago.  Marking resolved after the last change.  Discussing raise_message() for ajax based permission denied.  So, keeping open for the moment.
