### ISSUE TITLE
Allow Data Source repairs from the Data Source Debug and Data Source Info pages

### ISSUE THREAD

**Issue by cigamit** [Cacti/cacti#2500]
**Is your feature request related to a problem? Please describe.**
Currently Cacti provides you a repair command to run to correct various RRDfile issues.  However, you can not run those commands from the Website.

**Describe the solution you'd like**
Allow Cacti to run those commands automatically from the GUI if the RRDfiles are writable.

**Additional Context**
May requires some minor changes to the RRDproxy.

**Comment by jdcoats** [comment]
@cigamit Since I added this commit I see these every polling cycle for all of the graphs for my local cacti host. What does this mean? I deleted all of the graphs for this host and recreated and It still does it every 2-3 polling cycles.
![Screen Shot 03-11-19 at 09 17 AM](https://user-images.githubusercontent.com/42470924/54126956-13c5aa00-43df-11e9-99fb-1dc9ca65e352.PNG)

**Comment by netniV** [comment]
Have you checked your logging levels? Do you have anything in debug mode?

**Comment by jdcoats** [comment]
nothing in debug mode
![Screen Shot 03-11-19 at 12 06 PM](https://user-images.githubusercontent.com/42470924/54138744-78403380-43f6-11e9-8948-30dad68873fc.PNG)

**Comment by cigamit** [comment]
There was a followup change ot lib/rrd.php.  There was some debug code left in the first commit.  Just grab the latest lib/rrd.php

**Comment by jdcoats** [comment]
thanks, that did it
