### ISSUE TITLE
Installer is not consistent between MySQL Settings checking and final step Warning

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#2509]
1.  Under: install/install.php?data={"Step":"2","Eula":true}
     Recommended value are 'utf8_general_ci' and 'utf8'
![image](https://user-images.githubusercontent.com/17589018/54251240-92f2e380-4581-11e9-85c1-820b422939fc.png)

2.  Under: install/install.php?data={"Step":"8","Eula":true}
     Recommended(Warning Required) are changed to 'utf8mb4_unicode_ci' and 'utf8mb4'
![image](https://user-images.githubusercontent.com/17589018/54251365-f2e98a00-4581-11e9-85d3-3f9a0d7983fc.png)

**Comment by ddb4github** [comment]
After change  to:
[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_unicode_ci

Step#2 still show "recommended"  with 'utf8_general_ci', and final step warning is removed:
![image](https://user-images.githubusercontent.com/17589018/54251576-a5215180-4582-11e9-979e-ee6c83dc29e6.png)

![image](https://user-images.githubusercontent.com/17589018/54251610-c08c5c80-4582-11e9-9ae6-747daa13be48.png)

**Comment by cigamit** [comment]
This is a good point.  In general, utf8 is fine for most localities except China which some forms require the utf8mb4.  You might want to consider utf8mb4 as it only add one additional character.  The 'mb4' is a bit misleading.  However, we could do better on the language here as it's not catastrophic with that rare occasion of the very few languages that break the utf8 barrier.

**Comment by netniV** [comment]
There was a reason we switched over to mb4 rather than just plain utf8 and I agree as I think it was for those extended Unicode characters that are 4-byte in length (such as china already mentioned).  It was also to be more consistent on some of the SQL statements because there were issues (see https://github.com/Cacti/cacti/issues/1034 and https://github.com/Cacti/cacti/issues/1707)

Now, the reason you are seeing utf8 and not utf8mb4 in the recommendations list is I think because of your MySQL version being less than 5.6.  Unfortunately, the text at the top of the page has (currently) no variation based on the version of MySQL so assumes the default value of utf8mb4_unicode_Ci.

There is also a reason for using the unicode over general too and that was to do with properly sorting text fields if I remember rightly.  The problem is, it was a year ago we decided to implement that change for 1.2 and I can't totally recall all the reasons, only that it was the minimum to make things work for everyone.

**Comment by netniV** [comment]
It was also because we had some strange errors reported where SQL statements would fail for no apparently reason and it ended up being down to the collation and a mismatch between what was being used by Cacti and plugins.

**Comment by cigamit** [comment]
That's odd, it appears that maybe utf8mb4 is supported in MariaDB5.5.  We should mark that as a bug.

**Comment by netniV** [comment]
It was only from 5.5.3 that utf8mb4 was first introduced I think.  So, we should probably be more specific on the version checks.  We should probably raise the minimum MySQL level to match that.

**Comment by cigamit** [comment]
Resolved.  STRONGLY recommending 5.5.3+
