### ISSUE TITLE
Upgrade stuck after database upgrade

### ISSUE THREAD

**Issue by lambchopper71** [Cacti/cacti#2521]
The database upgrade fails due to issue #2482 after attempting to upgrade from 0.8.8f  Once the installer stopped on the database error, I can't get past it.

I made the change referenced in issue #2482 to the1_1_343.php file, and ran it from the CLI, but the installer will not pass this page.  Exiting the browser and going back in sends me to the same screen.

**Expected behavior**
The database to upgrade and the installer to complete

**Laptop (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Server Running Cacti:**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by netniV** [comment]
You can't just run the 1_1_34.php from the command line.  I would suggest updating the version back to 1.3.1 then running through the upgrade process again.

```sql
update version set cacti = '1.1.31';
```

**Comment by cigamit** [comment]
We will be shortly be moving into the next phase of the 1.2.3 release, that is to test the various install and upgrade scenarios.  I had noted some irregularities yesterday which we fixed last night.

**Comment by lambchopper71** [comment]
Thank you. Ultimately I had to rip and replace the install.

Any idea why the debian packages are still 0.8.8F? I'm no developer, the
package manager installation is much smoother for me.

**Comment by lambchopper71** [comment]
I ultimately did a rip and replace, but where would I set that? I still
have to run through the upgrade process again.

**Comment by Givo29** [comment]
I also faced this problem while updating cacti recently. In order to start the install again I dropped the cacti database and recreated it. Hopefully you have backed up the database before the upgrade via `mysqldump` so you can simply put it back in after you create the database again. Before you start the installation process make sure you have fixed the problem in `1_1_34.php` and I also found one or two issues in `1_0_0.php` that you may need to fix.

**Comment by netniV** [comment]
> Thank you. Ultimately I had to rip and replace the install. Any idea why the debian packages are still 0.8.8F? I'm no developer, the package manager installation is much smoother for me.

That would depend on your base OS and the repositories you have enabled.  @paulgevers kindly handles the Debian/Ubuntu packages for us.

> I also faced this problem while updating cacti recently. In order to start the install again I dropped the cacti database and recreated it. 

Are you saying that once you updated to the latest versions, the installer no longer blocked you?

**Comment by netniV** [comment]
@lambchopper71 @Givo29 - sorry the above were for you two (just forgot to tag you).

**Comment by Givo29** [comment]
@netniV Well... sort of. Since I was not only migrating it to a new server but also upgrading it from `0.8.8` to `1.2.2` what I was doing was going through a normal install seen [here](https://lintut.com/setup-cacti-on-rhel-and-centos-7x-system/). But instead of importing the `cacti.sql` file normally I dumped it from the old system and imported that one. Then as I said there is a few errors in `1_0_0.php` and `1_1_34.php` that have to be fixed and the installation should go through fine. I found that if it does produce an error on the upgrade the best way to restart it was to dump the cacti database and re-import the sql file. The errors in the two `php` files have all been fixed in the devel branch (I made pull requests for two out of the three) but they haven't yet been fixed in the version thats downloaded via `yum`.

**Comment by paulgevers** [comment]
As the Debian maintainer I can only say, don't mix the package with installs from the Cacti site, I would not know how to do it correctly. Some hints are on the FAQ: https://docs.cacti.net/faq?&#debian_and_ubuntu

So if you need to run a new cacti on such an old server, I suggest you set it up from scratch instead of upgrading.

**Comment by netniV** [comment]
For reference, Paul is correct in that swapping between website releases, github commits and package installs should be done with extreme care and a decent amount of knowledge.

In your case, because you installed the yum version, I imagine that would still be 1.2.2 without the fixes.  I'm sure that when the package updates to 1.2.3, those two files you updated manually should get replaced by the package version anyway, so shouldn't be an issue for you in these circumstances, but the debian packages do move some files/folders around to meet with their structured layout of packages.  

Since the fixes are in place and you managed to successfully upgrade, I'm going to remove the blocker label and mark resolved.  One thing you may find is that the paths on the new system are not the same as the old when importing your old SQL file so there could be hidden issues if you have not been through the SQL file and corrected those ahead of time.

**Comment by Givo29** [comment]
@netniV Well sure I was able to upgrade but I wasn't the one that created this issue. I still have no idea if @lambchopper71 was able to complete his upgrade

**Comment by lambchopper71** [comment]
@Givo29 @netniV I haven't tried upgrading to 1.x yet.  I've been tied up with other projects.  I reinstalled back to 0.8.8f which is what's currently in the Ubuntu repositories.  Also, just dropping the database didn't work for me.  It took me a while to figure out that to reinstall 0.8.8f, I had to reset the character set of MySQL.  The upgrade I guess changed that.
