### ISSUE TITLE
Missing configuration defaults prevent installations/upgrades without showing reason

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2555]
**Describe the bug**
Unable to finish any installer when using Nginx. For Remote poller, it says:
        Sorry, we could not process your last action.
        Error:
        200 OK
        Reason:
        The response to the last action was unexpected. 

User cannot continue installation (inactive Next button). Main site installer won't finish on nginx as well, but differently: it fails on DB. Both Central and Remote have been  tested on: gentoo, pretty stable, and Ubuntu 18.04 Server.

**To Reproduce**
Try using Nginx.

**Expected behavior**
Nginx as http server should work correctly.

**Comment by netniV** [comment]
This isn't actually an Nginx error but a PHP one.  You are likely getting a NOTICE or WARNING appearing which is messing up the JSON response.  Can you take a a look at your apache error logs or use the developer tools to see what the response back from the server is.

**Comment by stefanbrudny** [comment]
Right, here is the notice:

2019/03/23 03:00:58 [error] 20217#0: *82 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: rdatabase_retries in /var/www/cacti-dm10/install/functions.php on line 94" while reading response header from upstream, client: 192.168.10.1, server: localhost, request: "POST /install/step_json.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dm10", referrer: "http://dm10/install/install.php?data={%22Step%22:%223%22,%22Eula%22:true}"

**Comment by netniV** [comment]
Yes, I totally agree that should be handled better.  

The problem here is that the code predefines all the $database_xxx fields, but does not define any of the $rdatabase_xxx fields so that if you are not using the $rdatabase_xxx fields to connect back to a main poller that can be detected using isset($rdatabase_name) or $config['poller_id'] being greater than zero.

I will add a check if the remote poller name is set, but one of the fields is not to throw an error (with the exception of retries that will just get set to 0). I will also update the config.php.dist which is missing this config variable so if others are copying that, they know of it's presence.

What should happen is that we should be predefining the $rdatabase_xxx fields and then checking to see if the values mean we should connect to the main poller.  That is something we will correct in 1.3 since it will need some testing.

**Comment by netniV** [comment]
Actually, I decided to implement defaults anyway once I started looking into it, so it will now generate message (only in english since no translation code is loaded yet).

```
config.php is missing rdatabase_default, rdatabase_username, rdatabase_password
```

These are the defaults that are now set if the field is missing for $database_xxx and $rdatabase_xxx:

field | default or error | field | default or error
--- | --- | --- | ---
type | 'mysql' | retries | 5
default | error | ssl | false
hostname | error | ssl_key | blank
username | error | ssl_cert | blank
password | error | ssl_ca | blank
port | 3306
