### ISSUE TITLE
Cacti 1.2.2: Multi Poller: misleading Remote cacti databse on remote poller installation

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#2557]
**Describe the bug**
Right after Remote Poller installation: remote database connection indicates *local* poller database (local meaning local for remote poller). It is automatically propagated from config file / installation.

Actually, It is correct but misleading, since user has just got installed and logged into Remote poller. But for the moment it is not remote, it is local to Remote poller. 

The name should clearly reflect what is the purpose of the database configuration in the Remote poller interface.

I am guessing this was already an issue and it was tried to be resolved, as code includes an message preventing entering "localhost" here...

**To Reproduce**
Login to Remote Poller interface and to the Central Cacti. Open same view for remote poller, reshuffle tabs and try to not get lost which is which. 

**Expected behavior**
Remote Poller should have clear indication of "self" configuration and "central" configuration.

**Comment by netniV** [comment]
This is more a documentation issue.  Please feel free to write the appropriate documentation and submit it as a pull request to https://github.com/cacti/documentation/

**Comment by stefanbrudny** [comment]
I will happily describe the process and prepare some outstanding docs, but only for items I see as worth it :-) It is  wrong and useless to document features which are misleading, unless you were the responsible and / or have good justification.

This is misleading and this will be changed at some point, as users will complain. This is not documented and it will remain it as nobody cares about the crap. 

I will happilly wait another ~ 12 years for the change ;-p

**Comment by netniV** [comment]
Didn't your mother ever tell you, if you want something doing, it's quicker to do it yourself.

And I would not say that the above is misleading, it's just that the written code is  not the way you would prefer.  If the documentation helps, that can only be a good thing.  

Additionally, you can always prepare any code changes you believe may benefit others and it will be reviewed.  Before I was part of team, I had plenty shot down, but I was at least polite about it.

**Comment by stefanbrudny** [comment]
You are missing the point.
We are equal in this project in terms of time dedicated. Developers are responsible for how the code works and the featureset and users provide feedback. I am user and not going to participate as dev. 

I may fill some gaps in docs (this 4 days-long effort was for that, but now I am somewhat demotivated) but please stop asking for documenting stupid things, similarly like I do not ask devs to implement stupid features.  

Overall, looking from perspective of installation of 200k+ CPE, I find the application components are incomplete, suited for small to avg scale only, and deeply unbalanced (some are ok, but some bring the installation maxes down to 5-10k CPEs). 

If you have that many testers at this scale, feel free to drop this account.

I'll skip the part about your mother.

**Comment by netniV** [comment]
> You are missing the point
Actually I'm not.

> I am user and not going to participate as dev.

We have many users who have participated in either development or documentation or donations.  It is not unreasonable to ask and is in fact how I become one of the main developers of the project.  Some are even helping out with a new translation service we have tried to implement to again make things better.

> We are equal in this project in terms of time dedicated. Developers are responsible for how the code works and the featureset and users provide feedback. 

This is like saying that in terms of time dedicated, you are equal with the pilot of a plane when you go on holiday and board it.  The responsibilities and time invested are different and it's kinda arrogant to say they are the same.

As developers, we do this in our own free time after doing a full days work, taking that time from our friends and family to develop what you are using.  We do what we can, when we can and try to make things so asking you to participate in helping us make things better shouldn't be offensive.  And that continues all year round across both the core project and it's plugins.

As a user, you do put time and effort into using our software and we love that people do, Generally though, the time dedicated solely to improving it outside of the day job is rarely the same.  Providing feedback is always welcome, and we work with both users and package distributors to make positive changes too but where 20 minutes is spent giving feedback can lead to several days of diagnosis, development and testing. 

> Overall, looking from perspective of installation of 200k+ CPE, I find the application components are incomplete, suited for small to avg scale only, and deeply unbalanced (some are ok, but some bring the installation maxes down to 5-10k CPEs).

Cacti, like any software, can suffer from things that slow done in unexpected ways which larger systems show up. We have people that have scaled higher but as scale is always an ongoing issue when changing code, having more people who can provide positive feedback is always desired.

> please stop asking for documenting stupid things, similarly like I do not ask devs to implement stupid features.

At this point I will just say that your attitude, to be frank, stinks and it's not often that I will take the time to say that to someone.  You can either help, or you can't, there is no need for such attitude.  The code is unlikely to change on the naming because it would be a breaking change (though it is under consideration).  In the mean time, documenting how it actually works is the best way forward so people don't get as easily confused as you did.

> I may fill some gaps in docs (this 4 days-long effort was for that, but now I am somewhat demotivated) but 

I am presuming that the 4 days you spent was in setting up Cacti to monitor your systems.  The documentation wasn't as helpful as it could have been (and it's even worse if you look at any documentation from older than last year).  Hence it would be useful to get some of what you found documented!

I don't expect this to continue on as a debate, because it detracts from the issue.  If you do decide to help us out, then we will gratefully accept that assistance.  If you paste the URL of this issue in the body of a pull request, GitHub will even automatically link it back here for others to see as well which will no doubt help them too.
