### ISSUE TITLE
[1.2.2-1.2.4] - on updating check log file permission failed

### ISSUE THREAD

**Issue by pautiina** [Cacti/cacti#2600]
**Describe the bug**
When updating, there is an error checking the rights to write the log file

**To Reproduce**
1. update code from github (develop branch)
2. Open browser
3. Click next
4. install page always reload 

**Expected behavior**
I wanted to complete the installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/11805503/55313025-7dc9f000-546f-11e9-9546-beb8346f1cbe.png)

**Desktop (please complete the following information):**
 - OS: [FreeBSD]
 - Browser [Opera]
 - Version [58.0.3135.118]

**Additional context**
[root@noc /var/www/cacti]# ls -al /var/log/cacti.log
-rw-rw-rw-  1 www  www  864687682  1 апр.  11:16 /var/log/cacti.log
[root@noc /var/www/cacti]#

**Comment by netniV** [comment]
The reason the way that we check for permissions.  If someone/something were to remove the cacti.log file, cacti would not be able to recreate it and all logging would fail.  

It is better to create a directory with the log file and allow the web user access to the full folder, as this also allows for log recycling from within Cacti. 

The above error appears because of that recycling/recreating process is not possible.

**Comment by pautiina** [comment]
Thanks.
Changed to the standard path - and the installation continued.
I'm not sure that this is not a bug, since I like to keep all logs in one directory - this gives many advantages.

**Comment by netniV** [comment]
It's definitely not a bug, it's by design.  Annoying to you as it might be 👍 

I would ordinarily agree with keeping single log files in a single directory.  However, since being able to create/write to the log file is an important part of what cacti does (especially when there's issues) then ensuring we have the access is also important.  In normal circumstances, Cacti also operates it's own log rotation policy too and that requires the extra permissions.

To many users thought they were running without ANY problems purely cause the file was uncreateable/unupdateable (I may be make new words up here)!

**Comment by lbiffle** [comment]
I’m a bit confused.  We’ve dealt with appropriate permissions for log files/dirs since the 70s.  Are you saying that I have to use your specified path for log files, or the system isn’t going to let me finish my install?  If so, will you share that path with me?  And, also consider documenting this, please?

**Comment by netniV** [comment]
The issue is that when admins are setting paths to the log files, they often ensure the permissions for the active log file.  At some point, they rotate logs, remove them and Cacti can no longer log anything but since there are no errors as there are no logs, many thought they didn't have a problem.

So, the directory containing the log file is checked to ensure that a brand new log file can be created by Cacti in the event that the file is rotated/removed and needs recreating.  That is what the installer is checking for.
