### ISSUE TITLE
Spine 1.2.3 zip archive  is not complete...

### ISSUE THREAD

**Issue by carboxste** [Cacti/cacti#2616]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment]
Several things to note:

1. You have only provided a title and no actual detail
2. You have opened this in the Cacti repo, rather than the spine one which you can find at:
   https://github.com/cacti/spine/
3. Thanks for letting us know!
4. I will now close this and await a more detailed report over on that repo
