### ISSUE TITLE
[Cacti 1.2.3] Action Duplicate Graph

### ISSUE THREAD

**Issue by jvickya** [Cacti/cacti#2714]
Hi,
I'm using cacti 1.2.3, but I can not find action Duplicate in Graph Management 
Please support.

Thanks,
![image](https://user-images.githubusercontent.com/51222755/58682155-b3208a80-8399-11e9-9db7-501152d30752.png)

**Comment by netniV** [comment]
I dont believe there is an option to duplicate a graph since you would normally only have a graph with a single source. So creating an identical one is pointless.  A graph template or data source could be duplicated.

The only exception to this would possible be if you turned on the advanced mode, though that isn't normally recommended.

**Comment by jvickya** [comment]
How to turn on advanced mode?

**Comment by cigamit** [comment]
It's under Console > Configuration > Settings > General > Graph Permission Method.

**Comment by jvickya** [comment]
Thank you so much.

**Comment by sthasanto** [comment]
Hi, I'm getting this error in my cacti while creating duplicate graphs
ERROR PHP ERROR: Call to undefined function duplicate_graph() in file: /var/www/html/cacti-1.1.4/graphs.php on line: 531

**Comment by netniV** [comment]
You need to upgrade.
