### ISSUE TITLE
Strip domain name from basic authentication when its present

### ISSUE THREAD

**Issue by ycaoxa** [Cacti/cacti#2732]
user1 ,user1@Domain considered as the same user in most of authentication system . For now in Cacti, they are treated as two different users if want to login using them.

Suggest add fix in auth_login.php:
$dompos = strpos($username, "@");
if ($dompos != 0)
{      $username = substr($username,0,$dompos);
}

**Comment by netniV** [comment]
We specifically do not do this because of LDAP integration.  There may be many user1's at different points of a domain within a given realm, eg.  user1@domain.com user1@sub.domain.com or user1@yet.another.domain.com

For that reason alone, most authentication systems that I have dealt with require more than just the name.

**Comment by cigamit** [comment]
In the near term, we should trim this, but I see it as an obvious way to support multiple auth domains.  However, I expect that the user account is still just user1.  So, some thought needs to be given to this more long team.  This impacts basic auth only.
