### ISSUE TITLE
Lack of index.php in Cacti's log directory enable remote browse of the directory

### ISSUE THREAD

**Issue by TheWitness** [Cacti/cacti#2758]
**Describe the bug**
The Cacti log directory does not include an index.php.  Therefore, the directory can be directly browsed using a browser.  This is a bad practice.

**To Reproduce**
1. Login to Cacti
2. Point the browser to cacti/log
3. View the data in the log directory on the server

**Expected behavior**
Directory browsing should be blocked.

**Comment by bmfmancini** [comment]
Thats a good find however I think another issue is that you could browse directly to 
xyz.com/cacti/log/cacti.log and view the whole log file in the browser 
perhaps this could be better locked down?

**Comment by bmfmancini** [comment]
May I suggest 

# Deny access to .htaccess
<Files .htaccess>
Order allow,deny
Deny from all
</Files>


<FilesMatch "\.(log)$">
Order allow,deny
Deny from all

</FilesMatch>

As the default .htaccess file

**Comment by bmfmancini** [comment]
just submitted a pull request with these changes I have tested them on 1.2.4 and apache2
this would require AllowOverride All  in the apache config

**Comment by ddb4github** [comment]
BTW, lots of dir missed index.php, e.g. include/vendor/phpgettext/, include/vendor/phpseclib/, .....

**Comment by cigamit** [comment]
Instead of blindly adding htaccess files everywhere, a better idea would be to create a Security Document that informs everyone which directories they should be blocking at a server level.  Maybe with examples for the major HTTP engines out there.

htaccess files do absolutely nothing for those people not using Apache (Nginx, IIS, Lighttpd, etc...).  Even with Apache, it is better to block these in your conf instead.

From https://cwiki.apache.org/confluence/display/HTTPD/Htaccess

> The use of .htaccess files is discouraged as they can have a detrimental effect on server performance. Only use them when necessary.

If we really have to go down this route, then I recommend 1 htaccess file in the root instead of 1 in every directory we want to block.

**Comment by netniV** [comment]
I would agree with the idea to document the security recommendations.  Currently, we have:

```
log/.htaccess
cli/.htaccess
rra/.htaccess
cache/spikekill/.htaccess
cache/mibcache/.htaccess
cache/realtime/.htaccess
cache/boost/.htaccess
```

As @cigamit pointed out, these will do nothing for nginx or IIS so if they aren't already in the cacti/documentation repo, they should be.

**Comment by cigamit** [comment]
Okay, I've added the redirects in include/vendor.  The rest can be covered in a documentation bug for now.

**Comment by netniV** [comment]
So, I used Cigamits post above to create a new documentation issue.  For now, this part will be marked as resolved.
