### ISSUE TITLE
error mail in /var/log/mail.log 

### ISSUE THREAD

**Issue by rifanriansyah** [Cacti/cacti#2852]
please help me 

how to configuration sendmail in cacti version 1.1.38

![as](https://user-images.githubusercontent.com/53414308/62023604-d2059680-b1fb-11e9-8bed-3e750022c2a8.jpg)
![ass](https://user-images.githubusercontent.com/53414308/62023613-d92ca480-b1fb-11e9-94ad-ac2421407856.jpg)

me

**Comment by netniV** [comment]
If you are looking for the mail settings in cacti, these are under Console -> Configuration -> Settings.  If you are looking for how to configure sendmail to work with Cacti, that's not an area we normally cover but our forums may be offer some assistance otherwise you'd need that old reliable friend called Google.

**Comment by rifanriansyah** [comment]
but email not sending to reciver why 
![333](https://user-images.githubusercontent.com/53414308/62024533-95d43500-b1ff-11e9-819b-114213a534fe.jpg)

please help me sir netniV

**Comment by cigamit** [comment]
We can't tell you why, as I said before, you will need to look at sendmails log and determine why yourself.  Google any error messages you find, there are lots of pages out there to help you.

**Comment by rifanriansyah** [comment]
thank sir, i can looking for my error in embah google 

thank you for help

**Comment by rifanriansyah** [comment]
how to creating message in cacti for send mail sir ?

**Comment by netniV** [comment]
You already do by utilising the Test Email button.  This sends an email to the administrator address.
