### ISSUE TITLE
Clarification of  ping results ( Percentage of Loss)

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#2861]
Hey guys 

I am seeing something weird with some ping results where the packet loss percentage is off

Example 

Pinging to a host with 20 packets per poll if 1 packet drops that would be a minimum of 5% loss 
however Advanced ping sometimes reports results lower than this which would not be mathematically possible unless I am missing something here 

If I am right  that would mean the default amount of ping should be 100 to show at minimum 1% 

![image](https://user-images.githubusercontent.com/13388748/62234533-dadf9f00-b398-11e9-8e17-162ed63f2271.png)

Here is the way I have the data source setup which is the default

![image](https://user-images.githubusercontent.com/13388748/62234818-74a74c00-b399-11e9-84a5-277146b1bb47.png)

Can someone confirm if I have this right ?

As always thanks !

**Comment by cigamit** [comment]
The ping results you are talking about does not come from the Cacti built in ping, but from ss_fping.php, which executes the OS' real ping command, or even possibly the lib/ping.php.  It's been a while since I used that.

So, additionally, the spine data collector has a script timeout setting to prevent long running scripts from causing harm to data collection.  You should check to ensure that that timeout is sufficient for the ss_fping.php to run.  You can also change from the nifty popen to the traditional popen if you like.  It's a compile time option.  Have you seen any errors in you Cacti error log?  Have you been able to run spine in read-only mode to see what might be coming from the standard error log?  Is spine setuid() and owned by root?

Also, last word, and then I'm going to close this, just like the previous poster, issues like this should first be vetted on the forums.  So, I'll close this issue.  Please continue the discussion on the forums.
