### ISSUE TITLE
Cacti plugins monitor，thold，mactrack，syslog，flowview can translate very well,But plugin hmib can not translate,why?

### ISSUE THREAD

**Issue by flying-bigbird** [Cacti/cacti#2870]
Cacti plugins for monitor、mactrack、netflow、syslog can translate very well but plugin hmib can not translated .The method is the same.I would like to know how cacti extracts the Po file?
po file path:/hmib/locales/po/ chinese_china_simplified.po
mo file path:/hmib/locales/LC_MESSAGES/chinese_china_simplified.mo
Both files are download from Github,like other plugin ,No error!

I found when i put the hmib translate file (mo file) to the /var/www/html/local/LC_MESSAGES ,The plugin hmib can translate,but cacti core can not translate ! WHY??

**Comment by netniV** [comment]
Because you've overriden the core cacti location.  The path to hmib's translation files should be:

- [cacti]/plugins/hmib/locales/LC_MESSAGES/<language>.mo
- [cacti]/plugins/hmib/locales/po/<language>.po
- [cacti]/plugins/hmib/locales/po/cacti.pot

Note, the language is the short code reference not full name and for other plugins you simply replace hmib with the plugin name.

**Comment by cigamit** [comment]
Please open this one up in the hmib plugin area.  However, if you would like to contribute to a translation, goto https://translate.cacti.net, sign up and start translating to your language of choice.
