### ISSUE TITLE
 Import Template ERROR

### ISSUE THREAD

**Issue by tyit** [Cacti/cacti#2897]
![image](https://user-images.githubusercontent.com/31933126/63073386-2aa69480-bf5b-11e9-9659-69ee0e3dc1f8.png)

![image](https://user-images.githubusercontent.com/31933126/63073377-224e5980-bf5b-11e9-9e98-b23f75b7bcbd.png)

![image](https://user-images.githubusercontent.com/31933126/63073439-62add780-bf5b-11e9-970c-75c3b6db1cb0.png)

![image](https://user-images.githubusercontent.com/31933126/63073466-83762d00-bf5b-11e9-810c-54d625d9a220.png)

![image](https://user-images.githubusercontent.com/31933126/63073455-748f7a80-bf5b-11e9-8cb1-2ceb9df786e3.png)

![image](https://user-images.githubusercontent.com/31933126/63073531-cd5f1300-bf5b-11e9-9f6f-6f90d047dbe8.png)

![image](https://user-images.githubusercontent.com/31933126/63073604-2038ca80-bf5c-11e9-9f17-ec90a3fb8d14.png)

**Comment by cigamit** [comment]
This looks like an nginx configuration issue.

**Comment by tyit** [comment]
Hi 
Configuration according to this
https://github.com/Cacti/documentation/blob/develop/Install-Under-CentOS_LEMP.md
![image](https://user-images.githubusercontent.com/31933126/63153756-b1ce3800-c041-11e9-8070-42765fa8e970.png)
![image](https://user-images.githubusercontent.com/31933126/63153765-ba267300-c041-11e9-9703-9f8d6dac4d20.png)
![image](https://user-images.githubusercontent.com/31933126/63154175-9d3e6f80-c042-11e9-872a-20838db37ca6.png)

**Comment by netniV** [comment]
The REQUEST_URI will be unavailable to the command line so you can't do that.  Any CLI programs are contained within the `cli/` folder for the core.  Some plugins may have cli programs within their directories.

**Comment by cigamit** [comment]
I'm going to close for lack of feedback.  If you have additional questions, or have not resolved this on your own, then you can continue to comment.  I think we've seen issues like this for NGINX before, but they end up being configuration bugs.  If you follow the NGINX installation guide, and it turns out missing a step, please open a pull request for that section of the documentation.

Here are the current install instructions for NGINX: https://github.com/Cacti/documentation/blob/develop/Install-Under-CentOS_LEMP.md
