### ISSUE TITLE
Callback type forms do not render the form display value correctly in 1.2.6

### ISSUE THREAD

**Issue by majed17** [Cacti/cacti#2899]
Peace, there is a bug in 1.2.6, the location displays: [arg1:location] and even if you select the right location and save it still displays the bug!

**Comment by cigamit** [comment]
grab the most recent version of 1.2.x, this issue was resolved a few days ago.

**Comment by majed17** [comment]
just did, problem still present

**Comment by netniV** [comment]
Did you obtain the 1.2.x branch, not develop?

**Comment by majed17** [comment]
of course

**Comment by majed17** [comment]
and in data collection information the time zone displayed is |arg1:timezone|

**Comment by netniV** [comment]
Wait, switch the language to english, does it appear correctly?

**Comment by majed17** [comment]
i'll have to disappoint you, it's english

**Comment by netniV** [comment]
Can you supply a screenshot?

**Comment by j66h** [comment]
I can...

Timezone and location set and saved successfully.
Reentered web page. placeholders shown instead of configured values.

![Data Collector Timezone](https://user-images.githubusercontent.com/54892435/64419425-2b839f80-d09d-11e9-8f97-6e06cfbe6e7d.png)
![Device-location](https://user-images.githubusercontent.com/54892435/64419428-2de5f980-d09d-11e9-8ce1-1f00158d5229.png)

**Comment by cigamit** [comment]
I'm able to verify that it's broken under the Site Timezone setting.  It's good and repeatable and related to the drop callback function.  Should have it fixed in a jiffy.
