### ISSUE TITLE
When URL_PATH is blank, it should assume that it is '/'

### ISSUE THREAD

**Issue by ibatten** [Cacti/cacti#2908]
**Describe the bug**

Consider a configuration where nginx is set up with:

server {
   ...
   server_name cacti.dom.ain;
   ...
   root /usr/share/cacti/site;
}

Under <= 1.1.38 (I believe) you could do upgrades with $url_path set to ''.  It now appears to need '/', and goes badly wrong (extensive attempts to fetch cacti.domain/install/install/thing.js, note double install) unless this is corrected.

[[ I have been trying to get onto the 1.2 train for some months, on and off.  I finally built a replica system and systematically fixed all the load problems I was seeing with symlinks, until I could get to a stage where it was more obvious what the problem was ]]

**To Reproduce**

Set url_path to '' in config.php.  Attempt to perform an upgrade.

**Expected behavior**

A better error message, or simply set it to '/' if it is ''.

**Screenshots**

**Desktop (please complete the following information):**

Desktop Safari latest or Chrome latest on MacOS.  Server is Debian 10 out of the box.  I doubt either matters much.

**Comment by netniV** [comment]
Part of me wonders on the reprocussions of setting it to / when blank if the site is in a subdirectory, such as /cacti/.  With the blank, most web-based main folder pages would include based on the current directory of the url which would be right.  Making that a / suddenly changes that functionality.

However, I think i am going to implement it since the URL path should ALWAYS be defined to properly identify the root location of the website.

**Comment by netniV** [comment]
So, I have now changed this to obey the following rules:

- Default to '/cacti/' [existing]
- Allow override from config.php [existing]
- If now blank assume '/' [new]

So, this keeps existing functionality whilst correcting a misconfiguration in the config.php.  If no urlpath is defined in the config.php then '/config/' is still retained as the default and as long as you set it, then the path will be used.
