### ISSUE TITLE
AES Support for SNMPv3

### ISSUE THREAD

**Issue by andermat8** [Cacti/cacti#3072]
Running Cacti 1.2.5 on Windows Server 2012 and notice when using snmpv3 with AES we don't receive the if-alias information when we click on Create graphs for this Device.  We can fool it by changing to v1 or v2 and re-indexing and then switch back but this only works if we have a device setup for both v2 and v3.  Found this in the forum stating Cacti doesn't support V3 but that was back in 2017:

https://forums.cacti.net/viewtopic.php?f=6&t=33216&p=280062&hilit=AES#p280062

**Comment by netniV** [comment]
We did introduce support for snmp v3.  Have you tested that snmpwalk works with snmp v3 against your devices?

**Comment by andermat8** [comment]
I attempted to walk a device using AES but because Cacti uses Net-SNMP 5.5, which only supports DES, it will not walk.  Net-SNMP 5.8 does support AES so wondering when 5.8 will get baked into Cacti.

**Comment by netniV** [comment]
Net-SNMP is actually an OS level library, and we only utilise what is installed to the OS.  So, if you were to update your Net-SNMP library, you should be able to utilise AES I believe.

**Comment by cigamit** [comment]
Net-SNMP only supports AES upto 128 bit.  If you are using a Cisco devices that support AES 512, it cannot be supported using Net-SNMP currently due to AES 512 not being part of the SNMP specification.  There are many articles on this.

If you are using a Net-SNMP binary, you have to ensure that it's the OpenSSH enabled binary, which historically has been a separate install.  It's also likely that the php-snmp module included with PHP, may not be compiled with OpenSSH support.  So, I don't really think this is a Cacti issue.

**Comment by cigamit** [comment]
No feedback.

**Comment by cigamit** [comment]
@netniV, you might want to check with @BSOD2600 to see if he is packaging the ssl version of Net-SNMP in his packages.  If that's the case, and he is not using php-snmp, then AES should be supportable upto 128 bit.
