### ISSUE TITLE
Please ship the source of the documentation (and translations)

### ISSUE THREAD

**Issue by paulgevers** [Cacti/cacti#310]
Distributions like Debian want to build packages from source, where the source typically is described as the preferred form for modification. In the 1.0.x packages of Cacti, the source for the documentation is included in the git archive, but not in the released tar-ball. Can the source of the documentation please be provided in a released format? To be clear, I am not requesting it to be in the standard tar ball, but either a source tar-ball or separate "missing source files" tar ball would also suffice.

Additionally, the translations of cacti are shared in binary format (.mo) files, even in the git archive. This makes (automated) modification rather difficult. Could you please also provide (text based) sources for those?

**Comment by browniebraun** [comment]
Hi Paul, 
Regarding the translation files I already had a short discussion with one of the other devs just a few days ago, because I was missing our .po files as well. The current state of all translations is in such an early state that I am not sure if it would be better to leave them out and to store and handle them separately. 
Btw I'm currently working on the German translation which will be most probably the first that will be complete. But I have to make a few code changes switching from __() / __n() to __x()/__xn() function to add meaningful comments that will automatically added to our catalogue (.pot). Otherwise many translators will run into the same issue like I currently do, because it is not always easy to translate, especially a single,  English word correctly without knowing the right context.

Regards
-Andi

**Comment by paulgevers** [comment]
@browniebraun I'll be interested in providing Dutch translations once that is available.

**Comment by jpobeda** [comment]
I'm working on spanish translation, I'm about 40% but yes, sometimes the lack of context makes it harder.

**Comment by browniebraun** [comment]
I'm really happy to hear that. Current files are from 2010 (unreleased Cacti 0.9 prototype) and totally outdated. Most items do not match anymore. Some sentences needs to be updated in Cacti by removing embedded HTML tags, too. Instead of those, wildcards should be used like '%sCacti Webpage%s'.

Regards
-Andi

**Comment by jpobeda** [comment]
Is there any sort of convention you're using ? eg: not translating plugin names or features or something else that only makes sense in english like everything related to protocols or standards. Wildcardrs could also be useful to tag what to not translate. I know it's not the time for translation, still a long way to go but would you recommend to stop working on the current cacti.pot or carry on?

**Comment by browniebraun** [comment]
Good point, to be honest I haven't thought about that yet. :| I do not know if something like "TCP Port" will be translated into something totally different in Chinese or Japanese for example. In German it would also be "TCP Port". But I'm open for a discussion, suggestions and or hints how we could solve that in a good and universal way. Inserting a string replace function being executed first to remove a list of special placeholders would be doable, too. At the moment only sprintf related placeholders %s (string) and %d (decimal) should be in use. I wrote most parts years ago, so I really got rusty. :)
Don't stop with your translation. Once the template file (.pot) will be updated, changes can be merged to the different catalogs (.po).

**Comment by jpobeda** [comment]
I'd translate "TCP Port" into "Puerto TCP" because it makes sense in spanish, at least in my country is how we talk about it BUT what would happen if we translate web gui errors into every language how would you and other devs provide support to it in different languages? You'd be obliged to ask for debug or cacti logs instead of screenshots, for example.

Just brainstorming, sorry.

**Comment by browniebraun** [comment]
Web GUI errors should be translated as well. I would never expect that a tool localized to my area will display error messages in a different language. The only exception would be the Cacti log. Language as well as date format should stay unchanged in that case. Same to the different CLI tools. 
Thx god, we are having a great and active community behind Cacti, so that most probably there will be someone who can answer in a different language if a user is having trouble with English. Although I believe that most of us devs are able to answer at a minimum in two different languages, English is preferred.

**Comment by cigamit** [comment]
Please follow the instructions here:

https://github.com/Cacti/cacti/wiki/How-to-Create-a-Translation

Thanks!

**Comment by paulgevers** [comment]
@cigamit the original bug was mostly about the documentation (not about the translations), see also the title of the bug. Have you, or can you, address(ed) the original issue

**Comment by cigamit** [comment]
Okay, got it.  Re-opening and assigning to Rony.

**Comment by cigamit** [comment]
Tony, is this issue resolved yet?

**Comment by netniV** [comment]
It would be good if we could have a list for people willing to double check translations, especially at a release point.  That way we can ask for any translation changes prior to the actual release.

**Comment by netniV** [comment]
@paulgevers After re-reading this, I wondered if you would benefit from the using the Git Tags? Each release gets a tag to identify the release which would include the source translation files and documentation.  That comes in a downloadable archive form too.

I think long term the plan is that the documentation repo would be used to generate documentation and that would be marked with the same release tag too. Though @ronytomen may have other plans ;-)

**Comment by netniV** [comment]
I would say it's a source release, though there are parts that @ronytomen does (such as manipulating the dcumentation, removing some stuff) that goes into the release published on site.  As a one of the devs though, I only ever use the git sources (but then I know what I'm doing .. at least a tiny bit 👍 ).  I think things like the source language files etc may be another thing that gets removed to save space.

**Comment by netniV** [comment]
I'll do a full compare later and let you know.

**Comment by ronytomen** [comment]
I have to chime in here!

No, do not use the Github tagged releases. Official releases are only on https://www.cacti.net.

As far as documentation is concerned, we are moving to documentation written in markdown located in the documentation repository.

I have not worked out details at this time, so there is no further information.

This issue is not resolved.

**Comment by cigamit** [comment]
I've added several languages for the 1.2 beta3 release.  Google has done a marvelous job in performing the translations, but many are marked fuzzy.  We will need some information in the beta3 notes from people in these countries, or who speak the languages to remove the fuzzy markers if the translations are good.

**Comment by netniV** [comment]
I will make this as closed for now.  1.2 was released already.

If there is any further requests needed, I suggest opening a new issue that we can track against 1.3
