### ISSUE TITLE
Navigation pane requires mouse hover to enable scrolling

### ISSUE THREAD

**Issue by CapitalF** [Cacti/cacti#318]
In the new Modern theme (at least), Mouse-wheel scrolling on the left-side navigation pane does not accept mouse-wheel input until the scroll bar appears, which is delayed by 500-750ms and triggered by mouse-over. This is highly undesirable behavior. There is no justification to hide the frame scroller in the first place.

Cacti 1.0.3 on Linux. Browser used is Chromium on Linux.

**Comment by cigamit** [comment]
This is by design.  If you would like a different behavior, you are free to create a theme as this behavior is in the theme.  If you would like to share your new theme, you can submit a pull request and we will consider merging it.

If you would like to change the delay only instead of creating an entire new theme, please also create a pull request.
