### ISSUE TITLE
First Try 1.2.9: Web Upgrade Wizard hang as screenshot

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3183]
**Describe the bug**
First Try 1.2.9: WebInstaller hang as screenshot

**To Reproduce**
1. Prepare 1.2.8 workable env
2. Overwrite disk files by 1.2.x branch
3. Access Cacti from web browser to start upgrade wizard
4. Next..Next..Next
5. See error as screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/17589018/72244907-3d1c1b80-362a-11ea-9f32-9fe57cbd3ef5.png)

**Comment by j66h** [comment]
Same with me. Update from 1.2.8 which was installed from 1.2.x branch of 12/1/2019.
Didn't find 1_2_9.php in cacti/install/upgrades directory. Shouldn't that be created? Or is that, what background.php does at the beginning?

Have to admit: forgot to put MySQL credentials in config.php. Did this, after background.php was started first time. Do not know, if this has caused this...

downloaded 1.2.9 from 1.2.x branch yesterday (02/13/2019).

**Comment by netniV** [comment]
The upgrade files are included and used automatically if present but are only present when there is a database update needed. 

I will check this out later as it’s worrying to be suddenly broken. Are there any errors in the Apache error logs or cacti ones ?

**Comment by j66h** [comment]
Nothing interesting in cacti logs.
Following is from cacti.log:
`14.01.2020 06:46:10 - INSTALL: always: Spawning background process: c:/php/php.exe "D:/inetpub/wwwroot/cacti/install/background.php" 1578980770.7172
14.01.2020 06:46:13 - INSTALL: Checking arguments
14.01.2020 06:46:13 - INSTALL: always: Setting PHP Option max_execution_time = 0
14.01.2020 06:46:13 - INSTALL: always: Setting PHP Option memory_limit = -1
14.01.2020 06:47:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 06:52:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 06:57:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 07:02:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 07:07:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 07:11:11 - INSTALL: always: Spawning background process: c:/php/php.exe "D:/inetpub/wwwroot/cacti/install/background.php" 1578982271.5377
14.01.2020 07:11:14 - INSTALL: Checking arguments
14.01.2020 07:11:14 - INSTALL: always: Setting PHP Option max_execution_time = 0
14.01.2020 07:11:14 - INSTALL: always: Setting PHP Option memory_limit = -1
14.01.2020 07:12:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
14.01.2020 07:17:43 - SYSTEM WARNING: Poller 1 is Disabled, graphing or other activities are running
`

install-complete.log and install.general.log just include "spawning background" and "Setting PHP Option" messages like in cacti.log above.

No Apache, IIS instead.  ;-)
Nothing in eventlog. But I did not activate transaction.log.

Back on 1.2.8 now. Couldn't wait longer.

What I did additionally, since this was some kind of regular "update cacti" session:
- update MySQL to 8.0.19
- update php to 7.3.13
- update cygwin
But no windows updates.
I'm on Server 2016.

**Comment by netniV** [comment]
OK, thanks for the extra info.  There have been several reports with the installer not working so i think its been broken by a patch.

**Comment by cigamit** [comment]
This is resolved now.  Test with the latest 1.2.x branch.

**Comment by netniV** [comment]
This issue relates to #3183 and has now been resolved.

**Comment by j66h** [comment]
Updated to 1.2.9 again. Went smooth. Few polling cycles and one boost update later everything ok.
Thanxs a lot for all your effort. Bye, Jörg
