### ISSUE TITLE
Cacti 1.2.9: call to undefined function in api_device.php

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3257]
2020/02/11 17:01:27 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
Using a home made plugin, I do a call to api_device_save, the call was working in cacti 1.2.8, but now on 1.2.9 it crash with the following error:

2020/02/11 17:01:27 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function poller_push_to_remote_db_connect() in  /usr/share/cacti/lib/api_device.php:732 Stack trace: #0  /usr/share/cacti/plugins/linkdiscovery/findhosts.php(717):  api_device_save() #1  /usr/share/cacti/plugins/linkdiscovery/findhosts.php(518):  linkdiscovery_save_data() #2  /usr/share/cacti/plugins/linkdiscovery/findhosts.php(398):  CDP_Discovery() #3 {main} thrown in file:  /usr/share/cacti/lib/api_device.php on line: 732

The problem is that this line has been removed on 1.2.9:
include_once($config['base_path'] . '/lib/poller.php');

In position 25

**Comment by TheWitness** [comment]
Add it to the linkdiscovery plugin.

**Comment by arno-st** [comment]
Well I have a great respect for what the team did to maintain cacti, but here I think your joking!
You wrote a lot of documentation on how to write cacti part, code format and so on.
And now you telling me to make an API to work I have to include some code, that I don't need, into my code ?

Frankly don't you think an api should work when called, without having to add any kind of other source for it ?
I'm not making a call to database.php to use any dB function, it's all included, so why should I for an API!

Going your way that mean I have to include every php code into my plugin to make sure cacti is working!
I use open street map on one of my plugin, I include the code I'm using not every code called from the one I need.

Non sense

Even more since it was include until 1.2.8!


Arno

**Comment by netniV** [comment]
It was removed due to another issue.  If you look through the changelog it should be in there.

**Comment by netniV** [comment]
I'm going to close this as there are always some api libraries that can be included multiple times to ensure fresh data, etc.  Most API calls don't need that, and you only include the library once, but there are some that do at the moment.

I agree, I would rather have a situation were things were included once and all dependancies with it.  But that's why quite a few programs still have many library includes, not just one.

**Comment by ddb4github** [comment]
Just once cent:
   All api `push_out_host` and `api_device_save` user should include lib/poller.php by self

**Comment by TheWitness** [comment]
I've added lib/poller.php to global.php.  So, that should make everyone happy now.

**Comment by netniV** [comment]
Wasn't that removed for a reason?

**Comment by cigamit** [comment]
It had been included in several library files, which is a practice we were trying to get away from.  However, there are still quite a few instances of that.  In 1.3, I think we should drop include_once() entirely from the lib directory.

**Comment by ddb4github** [comment]
Update more impacted API:
   All api `push_out_host` , **`api_data_source_remove_multi`**, and `api_device_save` caller should include lib/poller.php by self
 
  I guess:
 * lib/poller.php introduce several  new `*remote*` functions
 * Some other non-poller.php-api use these `*remote*` function
 * But those non-poller.php-api `caller` do not include lib/poller.php

1.2.8 work well because lib/api_device.php include lib/poller.php, and most Cacti API caller directly or indirectly has included lib/api_device.php

**Comment by TheWitness** [comment]
We moved lib/poller.php to global.php a few days ago.  So, this will be resolved in 1.2.10.

**Comment by ddb4github** [comment]
> We moved lib/poller.php to global.php a few days ago. So, this will be resolved in 1.2.10.
Known,  Thanks
