### ISSUE TITLE
add postgresql despite mysql as db backend 

### ISSUE THREAD

**Issue by ravermeister** [Cacti/cacti#3306]
**Is your feature request related to a problem? Please describe.**
If I want to use cacti, I'm forced to use mysql

**Describe the solution you'd like**
I would like to see the possibility to use postgresql as database backend

**Describe alternatives you've considered**
Using the E.L.K stack, but that's no real alternative

**Additional context**
-

**Comment by TheWitness** [comment]
I think it would have to be PostgreSQL 9.5+ since before that release, it did not support UPSERT.  Love that description of the problem BTW.  There is MariaDB of course.  I would suggest that you first work on a cacti.sql.postgresql, then you will have to look at the MySQL'ism's such as from within the code and document them in comments here as to what needs to be changed.

If you want PostgreSQL support, you are going to have to assist.  Continue to post comments here, and then at some point we will look at incorporating.  It'll be a lot of work, but it was done one time in the past, and we sidelined it for various reasons.

**Comment by TheWitness** [comment]
BTW, I find ELK frustrating as well as stream protocols.  They are all heavy on data.  In stream protocols, every packet needs to pretty much include all the meta information about the object, which makes the protocol inefficient.  But hey, it's great for some things.

**Comment by netniV** [comment]
Do we have any commitment on supplying this?  If not, I would recommend we close the issue since we will not be doing this internally 👍

**Comment by cigamit** [comment]
Yes, we can close this.  Not gonna happen, we are too invested in a few MySQL features that Postgresql just completely lacks or has a subpar implementation of (Memory tables for one, its more of a hack in PG).  I can't live without my Active / Active cluster either.

**Comment by ravermeister** [comment]
> Yes, we can close this. Not gonna happen, we are too invested in a few MySQL features that Postgresql just completely lacks or has a subpar implementation of (Memory tables for one, its more of a hack in PG). I can't live without my Active / Active cluster either.

Hi, no problem was just an idea. For in memory db's l would prefer sqlite anyway... 

And clustering is possible via e.g bucardo
https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling

I personally only use pg_bouncer as connection pooling.

Anyway just close the issue 🙂✌️

**Comment by netniV** [comment]
I like MSSQL as it's what I grew up on, but I haven't convinced anyone to go that route yet either ;-)

And if we start abstracting from MySQL, we could run the risk of slowing things down rather than keeping things speedy.  I'm sure since I've mentioned MS, and you have PS, and they have MySQL/MariaDB already... someone's gonna chirp up about Oracle/NoSQL/DB3 (j/k don't think that even exists any more)
