### ISSUE TITLE
Calendar can not work in cacti 1.2.10 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3345]
**Describe the bug**
The calendar can not work in cacti 1.2.10 

**To Reproduce**
1. Install Cacti 1.2.10 
2. Go to Graph - preview mode
3. Choose calendar and change date and time, no response -- failed. 

**Expected behavior**
Calendar can work well 

**Desktop (please complete the following information):**
 - OS: rhel7.7 x64 
 - Browser: FF 73.01 
 - Version: Cacti 1.2.10

**Comment by TheWitness** [comment]
@yingbaiibm, it was not too clear what you were reporting, though I did find an issue where you hit the refresh button with the datetimepicker open, which results in some bad behavior.  Please retest, and if the issue is different, be more specific on how you think it should work vs. how it is actually working noting that you must press the 'Refresh' button.
