### ISSUE TITLE
When viewing graph previews, clicking Go or Refresh prevents calendars from working

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/cacti#3505]
## To Reproduce

1. Go to  Graph - preview page 

2. Choose calendar and click refresh,  calendar can work well -- ok 
3. Choose calendar and click go, after that calendar can not work well, no response. '

## Desktop (please complete the following information)

- OS: rhel 7 x64

- Browser FF 

- Version  Cacti 1.2.11

**Comment by yingbaiibm** [comment]
<img width="918" alt="Screen Shot 2020-04-26 at 10 40 40 AM" src="https://user-images.githubusercontent.com/47589910/80296567-07e9a280-87af-11ea-92f6-4c9077b1b83d.png">

<img width="987" alt="Screen Shot 2020-04-26 at 10 40 59 AM" src="https://user-images.githubusercontent.com/47589910/80296572-0fa94700-87af-11ea-8d2a-34d2e10de5a7.png">


<img width="870" alt="Screen Shot 2020-04-26 at 10 41 34 AM" src="https://user-images.githubusercontent.com/47589910/80296581-159f2800-87af-11ea-9d58-497ddb025ef6.png">

**Comment by ddb4github** [comment]
Until Cacti 1.2.4,  datepicker box can be auto-hide when click anywhere on page.
The latest 1.2.x branch, datepicker box can not be easily hide.
![image](https://user-images.githubusercontent.com/17589018/81920841-56e76280-960c-11ea-971d-7e6c6305e299.png)
### Reproduce Steps
1. Click any date input field, popup datepicker
2. Refresh page by ajax mode, exception "Click 'Refresh' Button". For example
    - No touching, waiting for auto-refresh (From cacti 1.2.4 - 1.2.13)
    - Select Device, Graphs, .... field fields (From cacti 1.2.10 - 1.2.13)
    - Click Go, Clear(both  two 'Clear') button (From cacti 1.2.10 - 1.2.13)
3.  See error, datepicker lost header/bottom as above screenshot.

### Workaround
#### Until Cacti 1.2.4( not test 1.2.5 - 1.2.9)
 - Click anywhere on page, datepicker hide, issue workaround
#### Since Cacti 1.2.10, even 1.2.x(today)
1. Click date field or 'cal' icon again, to show a complete datepicker box.
2. Press `esc` key, or click 'cal' icon again, or click `Refresh` button
3. datepicker hide, issue workaround

**Comment by TheWitness** [comment]
Okay, I'm made additional changes.  The reason that the document click was removed was due to the nature of the number of elements causing slow page response.  We need to limit the number of elements that receive the click event.
