### ISSUE TITLE
Browser reload backward from graph.php to graph_view.php

### ISSUE THREAD

**Issue by ddb4github** [Cacti/cacti#3524]
# Describe the bug
Browser reload backward from graph.php to graph_view.php

## To Reproduce
Steps to reproduce the behavior (tested under `modern` theme):
1. Go to top Graphs tab, select `Tree` or `Preview` mode
2. Select a graph and click `cog` icon on right of graph
3. Check browser, still be graph_view.php.
4. Click browser `reload` button
5. See error, browser backward to previous page.

If open 'cog' link in new browser tab/window, no this issue.

## Expected behavior
Keep same behavior between"Open `cog` link in current tab/window and new tab/window

**Comment by netniV** [comment]
Technically, you are losing one state of history.  By refreshing, you no longer need to go backwards - but I agree that is confusing.  It comes down to the long battle we have had over the URL being used, primarily because we pass in a variable to say we want to exclude headers, but when refreshing, you don't want that.

Hopefully, in 1.3, that will go away as I have already had ideas on how to combat that but it needs some proper time to test it and see what the fallout will be.

**Comment by netniV** [comment]
I've marked the issue as a duplicate because we have long known that back and forward buttons are not always working properly.

**Comment by TheWitness** [comment]
Yea, there is a chance this will be revisited in 1.3, but not for the moment.  Since this is duplicate, I'm just going to close for now.

**Comment by netniV** [comment]
This has actually be addressed in 1.3 (develop) branch. Please feel free to check it out and let me know if you find anything untoward with it.
