### ISSUE TITLE
Error viewing graphs in tree mode

### ISSUE THREAD

**Issue by turtlefr** [Cacti/cacti#3546]
After upgrading to 1.2.12 I now get this logged, and a server side error:
020/05/09 19:03:03 - CMDPHP Validation Error, Variable:thumbnails, Value:on Backtrace: (/graph_view.php[221]:top_graph_header(), /lib/functions.php[3289]:include_once(), /include/top_graph_header.php[55]:grow_dhtml_trees(), /lib/html_tree.php[95]:html_validate_tree_vars(), /lib/html_tree.php[855]:validate_store_request_vars(), /lib/html_utility.php[702]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

<img width="387" alt="Capture d’écran 2020-05-09 à 19 22 50" src="https://user-images.githubusercontent.com/15179749/81480507-87a15380-922a-11ea-8387-a6cc8cfbec60.png">

php 7.2 on Ubuntu 18.04 
This is only a problem with Tree view. List and Preview view work fine.

**Comment by netniV** [comment]
This would be a variable used on a URL which isn't in our defined list of expected variables.  We will look into this and correct it if we can find it in our code.  There is a possibility that if using external links, they include variables that aren't expected and you can hide these developer warnings via the system option.

**Comment by TheWitness** [comment]
I'm not able to reproduce.  @turtlefr, can you explain what navigation steps you are taking?  This would only happen if there is a JavaScript error on the page preventing the default actions.  This could be caused by a Plugin.  Are you using any Plugins?

Even if you are not, before you test, goto the Browsers debug window, and open the Debug windows console and watch it for errors.  If you find any.  Post images.

**Comment by TheWitness** [comment]
@turtlefr, bump!

**Comment by turtlefr** [comment]
I'm sorry to be late answering.

Here's what I did:
- removing the cache: Concole > System utilities > Rebuild Resource Cache and Rebuild Poller Cache
- server reboot
- purge browser cache (firefox and Chrome)

Now I don't have the error anymore.
