### ISSUE TITLE
Field added to host table not saved

### ISSUE THREAD

**Issue by arno-st** [Cacti/cacti#3561]
Hello,
I add some field (7 to be precise) to my host table with config_form api, I also add the column to the DB.

But when I go tho a device, the field are here, but on a save, it's not send 3 of them in the html post, so can't get it back to my api_device_new to save it

Why is that and how to see where is the problem.
The 3 I'm missing are of the kind checkbox (so bool value)

Thank for your help

**Comment by netniV** [comment]
Is this code available for testing?

**Comment by arno-st** [comment]
Yes of curse:
https://github.com/arno-st/ciscotools/tree/develop

But i think I find what happing.
The check box is only send the post if the value is enable, and if it's disable the value is not present.

**Comment by netniV** [comment]
If you are using our form controls, I believe it should be always present.  However, if the value is not changed from it's original value (which a defaulted checkbox may not be) then the value might not be sent since the database default should therefore be used.  That's my speculation without any testing.

**Comment by TheWitness** [comment]
In the past, if a checkbox did not exist in post, we would assume the value would be '', otherwise, the value is 'on'.  Hope that helps.

**Comment by arno-st** [comment]
That was what I find, and it make sense.

Thanks

**Comment by netniV** [comment]
It actually comes partly down to browser implementation that too we have found.
