### ISSUE TITLE
Change wording for the 21st century, but let's not forget our past

### ISSUE THREAD

**Issue by YongBoLiu** [Cacti/cacti#3730]
# Describe the bug

As more and more care about the culturally insensitive, we need to replace the 'whitelist' to 'allowlist', 'slave' to 'compute' or 'server' in filenames, GUI and logs.

[yboliu@oc8636837557 cacti]$ find . -name "*white*"
./cli/input_whitelist.php
[yboliu@oc8636837557 cacti]$ grep -Ri slave . -l
./include/vendor/cldr-to-gettext-plural-rules/src/cldr-data/main/en-US/languages.json
./poller_automation.php

## To Reproduce

1. Go to cacti installed directory. Check the filename, and log code in poller_automation.php

2. See the culturally insensitive terminology.

## Expected behavior

 No 'whitelist', 'slave' in filenames, GUI and logs.

## Desktop (please complete the following information)

Linux

**Comment by cigamit** [comment]
We will discuss this internally.  It's not technically a bug though (things aren't broken), its more of GUI/Documentation IMO.

**input_whitelist.php** - Its more than just the filename, whitelist is used throughout multiple files.
**'poller_automation.php'** - I would change Master to Main, and Slave to Child.

Any files in vendor are third party and will have to be changed upstream first.

**Comment by riversdev0** [comment]
*I am not a project maintainer. I do not take part in decisions. The following statements are my own, and not those of the Cacti team.*

I don't mean to be blunt here, but while 'slave' may not be culturally sensitive, it does accurately define what the role is.  &lt;sarcasm&gt;Therefore, instead of renaming it, we should consider deprecating the feature altogether.&lt;/sarcasm&gt;

**Comment by TheWitness** [comment]
I kind of agree, as in western culture anyway, the first slaves were 'white', Slavic's. So, let's do the change.  But let's not kid ourselves though, the oppressors have always oppressed.  It only matter's, the color, when politics are involved.  The Egyptians did not care, nor the Romans, nor any other culture.  There is an old saying that history was always written by the victors.  Though we may change the words, if we forget the meaning, history will repeat itself.

**Comment by netniV** [comment]
If we are to undertake such a task, I believe it should be a project in its own right to identify all the areas that this would affect and whilst if that actually involves code changes, these will have to be tested.  

If there are only a handful of things that need changing, we can do this.  However, I think when it comes to documentation we may have to include a cross reference of previous terminology so that as people migrate forward they can understand what has changed in name only (as no functionality should change).

For the most part, I always referred to Poller 1 as the Main Poller and the rest as Remote Pollers. But others would prefer other terminology, hence the need to identify what there is, and what we will change it to.  Once we have that identified, I would suggest posting it for user consumption to see what people feel and get a general consensus.

**Comment by bmfmancini** [comment]
I would be happy to make any edits to documentation

I can do a grep against the repo for any words containing the insensitive
wording

**Comment by TheWitness** [comment]
@bmfmancini, change anything slave to 'child'.  Master is fine.  I am the "master" of the house, when the wife is away anyway ;)

**Comment by TheWitness** [comment]
Stet that: masters and workers.

**Comment by YongBoLiu** [comment]
Thank you all. The word is better, the world is better.
