### ISSUE TITLE
Ping.pl does not work under Windows

### ISSUE THREAD

**Issue by ted0net** [Cacti/cacti#3754]
Unfortunately the ping.pl program is written for the output from a *nix ping command. The output from a Windows ping command is not really similar enough for ping.pl to work properly. I'll take a stab at writing a Windows-centric version of ping.pl, but I'm not very good at Perl. I'm posting this issue in case anyone else is interested.

**Comment by netniV** [comment]
ping.pl is only designed for linux.  The biggest clue to this is:

```perl
open(PROCESS, "$pingcmd 2>&1 | grep -E [.....]
```
which basically runs the linux grep command in regeex mode.  If this supported windows, the regex would be outside of the ping command and/or findstr would be used for the regex filter.

I think the simple fix would be to detect windows and then use `findstr /r` over `grep -E` but that would need some testing.  Since that could break other systems and it's really an enhancement, can you PR target develop branch?  (There should be no difference between the 1.2.x and 1.3.x versions of that command currently.

**Comment by TheWitness** [comment]
Pull requests are always welcomed.  I'm not sure how popular Perl is on Windows though.  IMHO, Microsoft should just include: perl, php, and Python in their default distribution (one that's not crippled of course).

**Comment by TheWitness** [comment]
I don't think we are going to do this one.
