### ISSUE TITLE
Bugs in Cacti version 1.0.4. and version 1.0.5 (development).   Add function...

### ISSUE THREAD

**Issue by PonomarenkoVladimir** [Cacti/cacti#377]
1.  No label in Classic Theme:
![default](https://cloud.githubusercontent.com/assets/26214543/23598620/58b56f06-0287-11e7-811d-4441e7f72f1c.png)

2. No scrollbar on  window "New Graphs" and "Graphs"  in Moderm, Dark, Paw Theme:
![default](https://cloud.githubusercontent.com/assets/26214543/23599029/2392beac-028a-11e7-98c8-2e5cb649a28a.png)
![default](https://cloud.githubusercontent.com/assets/26214543/23599057/5665a8f8-028a-11e7-9d23-c3ab90dd1366.png)
![default](https://cloud.githubusercontent.com/assets/26214543/23599091/8bac816c-028a-11e7-8cf1-df4d6f90813a.png)
![default](https://cloud.githubusercontent.com/assets/26214543/23599108/a05c606e-028a-11e7-8e8f-97db4d58aa4f.png)
![default](https://cloud.githubusercontent.com/assets/26214543/23599135/ce328d10-028a-11e7-9bb7-4614a7a909d6.png)
![default](https://cloud.githubusercontent.com/assets/26214543/23599147/e3ea5d7c-028a-11e7-86e5-4fce5101830c.png)

OK Scrollbar in Classic Theme:
![default](https://cloud.githubusercontent.com/assets/26214543/23599221/5bdbf75a-028b-11e7-9aa2-67cee835af09.png)

3.  Add new function "Change Site":
![default](https://cloud.githubusercontent.com/assets/26214543/23599269/a9018db0-028b-11e7-93cb-70c54a694830.png)

**Comment by pautiina** [comment]
I also have this problem.

**Comment by cigamit** [comment]
Issue 1) tabs is likely a '$config['url_path']" in the anchor path.  You can see this by viewing the link in debug mode.  Looks like an old plugin too.  If they are old 'SuperLinks', you should verify that you have the GD php module loaded.  Either way, if the tab issue continues, and they are old 'SuperLinks' and you do have the GD module loaded open a separate ticket.  If it's a custom plugin issue, that does not belong here as plugins are responsible for their 'classic' images.

Issue 2) is by design.  Start typing into the device dropdown and you will see that it operates as 'autocomplete'.  This was done as some people have 20k+ devices, and the dropdown list not now work well in those cases.

**Comment by cigamit** [comment]
Changing 'site' is already supported by 'Change Device Settings'.
