### ISSUE TITLE
Cacti 1.2.14 Unable to change Graph Template

### ISSUE THREAD

**Issue by smwadek** [Cacti/cacti#3824]
Hi,

i am unable to change device Graph template on new version Cacti 1.2.14 . I would link to change my Individual device graphs which was previously created from In/Out Bit (64 bits) templates, Now i need to Change it In/Out Bit (64 bits, BW) template but its not showing any change option

Technical Support [Summary]
==========================
Date Wed, 23 Sep 2020 12:59:00 +0600
Cacti Version 1.2.14
Cacti OS 7
Apache 2.4.7
MariaDB 10.4
PHP 7.3
NET-SNMP Version NET-SNMP version: 5.7.2
RRDtool Version Configured 1.4.0+
RRDtool Version Found 1.4.8

![unabletochangetemplete](https://user-images.githubusercontent.com/71777959/94032889-3f9e5a00-fde2-11ea-941b-b8f1bb3a7e8f.PNG)

=== 

![Graphtemplet](https://user-images.githubusercontent.com/71777959/94032969-5349c080-fde2-11ea-9525-e611a433238c.PNG)

Is their any command line (cli ) way to change graph templates ... i have to do it (400+ ) devices...

**Comment by cigamit** [comment]
You have to select a Template in the filter up top to be able to Change a Graph Template.  We do that exactly because of what you tried in your example image above.  You selected multiple completely different types of graphs based on different templates.  You can't change a CPU graph to a Traffic graph for instance.

I did notice one bug though, when first visiting the page, the request variable isn't set, so it doesn't hide the setting.  I will fix that, but its not related to your issue.
