### ISSUE TITLE
Checkbox for Graph Templates in the "New Graphs" do not work

### ISSUE THREAD

**Issue by thurban** [Cacti/cacti#397]
When clicking the checkboxes next to a Graph Template Name on the "New Graphs" page (graphs_new.php). The template will not be selected.

Clicking on any of the cells(i.e some pixel next to the checkbox) will select the template.

Server:
Cacti 1.0.4
Centos 7

Client:
Chrome Version 56.0.2924.87
Windows 10 64 bit

**Comment by cigamit** [comment]
Are you certain that Graphs were not auto-created.  When you enable Automation and you have Graph Templates for a device type.  The Graphs are created automatically on Device Creation.  It saves you steps in managing devices.  Data Query Graphs will also be created automatically if you have Graph Rules created for them.

I'll close for now.  Please re-open, or request re-open if you find otherwise.
