### ISSUE TITLE
Cron/pooler runs after 4 minutes instead of 5

### ISSUE THREAD

**Issue by michaelscl** [Cacti/cacti#4081]
# Describe the bug

The scan runs after 4 minutes instead of 5 

## Screenshots
![2021-01-22_121758](https://user-images.githubusercontent.com/31956130/105485155-c0943200-5cac-11eb-8e19-a914b6a2b8bf.png)

![image](https://user-images.githubusercontent.com/31956130/105493980-61d5b500-5cba-11eb-9273-911a7a0f5ecb.png)

## Server
- OS: Ubuntu 20.04.01 LTS

**Comment by bmfmancini** [comment]
Can you post your crontab setting?
This would not be a Cacti issue as crond would be the one that executes the poller script

**Comment by bmfmancini** [comment]
also can you post the output of 

systemctl status cron

**Comment by TheWitness** [comment]
Yea, Cacti, when using cron has not control of this.  You might want to check that your database is not blocked though.  When you perform a mysqldump, by default, the database locks up.  There is also the cactid service in the latest release.

**Comment by michaelscl** [comment]
> 
> 
> Can you post your crontab setting?
> This would not be a Cacti issue as crond would be the one that executes the poller script
Cron is OK:
![image](https://user-images.githubusercontent.com/31956130/105672852-6af69a00-5ee5-11eb-891f-b02e31847e3b.png)

Collection is also OK:
![image](https://user-images.githubusercontent.com/31956130/105673509-726a7300-5ee6-11eb-8e35-136634b43fb0.png)
![image](https://user-images.githubusercontent.com/31956130/105673559-7e563500-5ee6-11eb-9a28-921cc7dc91d0.png)

I don't use cactid yet.

New info from log:
![image](https://user-images.githubusercontent.com/31956130/105674742-40f2a700-5ee8-11eb-8dc9-bcda0869cc40.png)
Hmmm, Cacti said. Time since last:239 Max Runtime 298... 239 < 298 - Why Cacti starts pooler .... ?

**Comment by TheWitness** [comment]
That Cron entry is wrong.  Should start off

```
*/5
```

**Comment by michaelscl** [comment]
I do not agree. From a certain version it is recommended * * * * *
How would this work 1 Pooling minute collection?
![image](https://user-images.githubusercontent.com/31956130/105706459-d9e9e800-5f11-11eb-9956-ef5c50b7035b.png)

**Comment by bmfmancini** [comment]
for 1 min collection I use

*/1 * * * *
for 5
*/5 * * * *

**Comment by netniV** [comment]
To be honest,`* * * * * *` and `*/1 * * * *` are actually the same thing since the /mm option is the interval of minutes to use.

```shell
# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name command to be executed
```

There are several methods of doing 1 minute polling.  

- **Cron = 5m, Polling = 1m**
  The poller process is only run every five minutes and shuts itself down just before it is restarted.  Any pollable items are requested based on their schedule, so if there is a 5m polling item, that only gets polled once.  If there is a 1m polling item, that would be polled 5 times.

- **Cron = 1m, Polling = 1m**
  The poller process is run every minute and shuts itself down just before it is restarted.  Any pollable items are requested based on their schedule.  If a polling item is due to be polled it will be.  So, over five minuets, 1 minute items would be processed each process, but 5 minute items only on the fifth.
 
- **Cron = 1m, Polling = 5m**
  This scenario is wasted unless you have any one minute polling items.  Four out of the five processes would do nothing.

**Comment by cigamit** [comment]
> Cron = 1m, Polling = 5m
> This scenario is wasted unless you have any one minute polling items. Four out of the five processes would do nothing.

I thought we changed that a long time ago so that it would split up items across the polling if possible.  Maybe I am just going senile in my old age.

**Comment by netniV** [comment]
Honestly, it may do but I don't recall that being the case, I guess @TheWitness may know better?

**Comment by TheWitness** [comment]
We do split items across polling cycles if their data source profile is set to five minutes and the cron is set to one minute.  So, I would suspect that there may be cases for 'very' small systems to have a single polling cycle that skips a beat.

As far as the cron, yes, agree that `* * * * *` is every minute.

**Comment by TheWitness** [comment]
Also, crond has a stupid setting that will skip a cron cycle depending on load.  It's another reason to go with the new cactid.php daemon and the systemd unit file.
