### ISSUE TITLE
Data source template names should be shown in the respective "suggested values" sections

### ISSUE THREAD

**Issue by bernisys** [Cacti/cacti#4161]
# Describe the bug

Data source template names are not shown in the list for the suggested values for data sources, if multiple data source templates are used in the connected graph.

(Not sure if it is wise to create such a query, but we just produced this scenario.)

## To Reproduce

Create 2 data source templates
Create a graph using both data source templates
Create a data query and add the graph template
Check the "Suggested Values - Data Sources" section 
You will see two sections listed belonging to the two data sources, but there is no way to distinguish, which of the DS each of them is connected to.

## Expected behavior

Show the DS template names, as it is done in the "Associated Data Templates" section above.

## Screenshots

![cacti-query-edit-datasource-hint-missing](https://user-images.githubusercontent.com/32120318/110471023-e732ee80-80db-11eb-91f0-3a3323bd4458.PNG)

I have added already a "name" pattern for both, one suffexed "first" and the other one "second" to find out which is which.
I assume that the first one corresponds with the first DS also shown in the top section for the variable-assignment.

**Comment by TheWitness** [comment]
I looked at this and said to myself "how did that happen".  But I've only now gotten enough time to really read the bug.  Yea, that makes sense though doesn't it.  I'm not saying the behavior is desirable, but I can see how that would happen since there are two data sources technically, and each can have it's own suggested name.  Like "|host_description| - Power in Amps" and "|host_description| - Temperature in Celsius".  So, it kind of does make sense doesn't it?

But maybe the questions is "I can tell this one from that one.  There is not enough labeling".  Well that's easier to fix.  I think that's the ticket.  Okay.

**Comment by TheWitness** [comment]
Okay, all better.  All on a good glass of zinfandel.

**Comment by bernisys** [comment]
Well reasoned recap of yours :) And yup, the fix looks pretty reasonable to me, that should do the trick. Cheers!

Thanks for also pushing this small thing directly into 17 ;)
Rough idea when it will be released finally?

**Comment by TheWitness** [comment]
Soon.
