### ISSUE TITLE
Latest source - Data Template Problems

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#4172]
I created a new data template and set the possibility to override the selected value during creation but unfortunately this flag doesn't seem to work. 

It is possible to reproduce it as below: 
![image](https://user-images.githubusercontent.com/1744639/111349268-45824300-8681-11eb-9a60-1d2b8e46a2a6.png)

![image](https://user-images.githubusercontent.com/1744639/111349642-998d2780-8681-11eb-8793-76c051ba60f5.png)

do you have any suggestions about it? am I doing something wrong?

**Comment by TheWitness** [comment]
Is this on initial creation, are you doing it manually?  If so, there is a fix already in the 1.2.x branch.  However, explain how the Graphs are created, if you are letting automation do the naming, then, you won't get prompted.  If you are looking to have the 'option' to change the values after creation since they were forced in using automation without giving you the option to set those values (which is kind of not part of automation), yea, that would be a bug I think.  Give me some feedback.

**Comment by TheWitness** [comment]
Was able to manually create and get this.  But that's from the Graph Template.  Let my try what you asked for.

![image](https://user-images.githubusercontent.com/1439914/111568521-4bf2e680-8777-11eb-899f-63b4582fd165.png)

**Comment by TheWitness** [comment]
Confirming.  Data and Graph template overrides show up, but not the Customer Data overrides.

![image](https://user-images.githubusercontent.com/1439914/111568905-01259e80-8778-11eb-8e13-53701888e452.png)

**Comment by TheWitness** [comment]
Likely just did not catch it when making the other related fix.  Likely super simple to fix.

**Comment by anarkia1976** [comment]
> Likely just did not catch it when making the other related fix. Likely super simple to fix.

Thanks a lot, i'm waiting.

**Comment by TheWitness** [comment]
Pretty sure this is working now.  Take the recent updates and then let me know what happens with your existing Data Sources, and then delete and existing 'broken' graphs then do the following:

1) Run automation on the device and see that the graph is NOT created.
2) Create the Graph manually and see that you can now edit the 'Custom Data'.
3) Give me feedback on the existing ones.

**Comment by anarkia1976** [comment]
Very good, all is working now. Thanks a lot for your great work.
