### ISSUE TITLE
Script 'cacti_user_stats.php' return 0 with cacti user

### ISSUE THREAD

**Issue by oijkn** [Cacti/cacti#4308]
# Describe the bug

If I run the script `cacti_user_stats.php` with the cacti user, it returns the value 0. But if I run it with root or www user, it returns values. So from the web interface the graphs are empty but in real time mode, it displays data. The problem is the same with Cacti v1.2.16 or 1.2.17.

**From cacti user**:
```
cacti@poller:/$ /usr/local/bin/php -q /usr/local/share/cacti/scripts/cacti_user_stats.php
valid:0 invalid:0 active:0 sleeping:0 garbage:0 uactive:0 usleeping:0
```
**From www user:**
```
www@poller:/$ /usr/local/bin/php -q /usr/local/share/cacti/scripts/cacti_user_stats.php
valid:0 invalid:0 active:1 sleeping:0 garbage:0 uactive:1 usleeping:0
```

## To Reproduce

1. Run the script from cacti user -> return 0

2. Run the same script with root or www user -> return values

## Expected behavior

I assume that the script must return values with the defaut cacti user.

## Desktop (please complete the following information)

- OS: [FreeBSD 12.2]
- APP: [Cacti 1.2.17]

![image](https://user-images.githubusercontent.com/18188407/122258833-cbf12f80-ced1-11eb-8071-b5b65141d344.png)

**Comment by netniV** [comment]
It's a permissions problem.

**Comment by oijkn** [comment]
> 
> 
> It's a permissions problem.

Ok but I don't know why, I set 755 perm on file and set cacti user as owner.
All others scripts works good, except this one.

**Comment by xmacan** [comment]
Tested on FreeBSD 12.1. It is really permission problem. User cacti hasn't permission to read /tmp/sess_xxxxxxx files:
root@kaktus ~ # ls -ald /tmp/
drwxrwxrwx  8 root  wheel  704 16 čvn 21:49 /tmp/

root@kaktus ~ # ls -al /tmp/
-rw-------   1 www    wheel     68218 16 čvn 21:49 sess_39ceb1cd7170dc021f1440fecc8b7669
-rw-------   1 www    wheel      1838 16 čvn 21:47 sess_c31509a8b3377ee7a15068ba69dce4a0
-rw-------   1 www    wheel     17595 16 čvn 21:49 sess_f44500c8ea9c6dbe4b681e43a281a190

Realtime is working well, because /tmp/sess files reads www server and it has permssion. Poller is started with user cacti and this user hasn't permission to /tmp/sess files.

**Comment by xmacan** [comment]
@netniV Wouldn't it be better to get the data from table user_log.time instead of getting it from a cookie?

**Comment by oijkn** [comment]
@xmacan Thank you for pointing me in the right way 👍🏻 until the developers find a solution, I added the following lines in the root crontab to allow the cacti user to read the session files :

```
# Cacti: fix owner & permission for session files
*/5 * * * * /usr/bin/chgrp cacti /tmp/sess_* > /dev/null 2>&1
*/5 * * * * /bin/chmod 640 /tmp/sess_* > /dev/null 2>&1
```

**Comment by xmacan** [comment]
@oijkn - have you php installed with mod_php7x not php-fpm?

Another workaround - run poller in cron with user www instead of cacti user

**Comment by oijkn** [comment]
> @oijkn - have you php installed with mod_php7x not php-fpm?
> 
> Another workaround - run poller in cron with user www instead of cacti user

Yes I use mod_php with Apache and I can't change poller user in my office structure.

**Comment by netniV** [comment]
OK, so not sure whether it is us or PHP that creates those sess_ files, suspect it's us.  We could probably get the process to update the sec to be 640 but with the group being wheel, that wouldn't help.  If there is no "PII" in the files, we could potentially do 644, but not sure I like that idea as it's giving session information world readability.

**Comment by xmacan** [comment]
I guess that it creates php and it depends on umask. Nice workaround is set $cacti_db_session = true; in config.php

**Comment by netniV** [comment]
Yes, so it must be us.  Since we are switching where to store that info.

**Comment by xmacan** [comment]
640 is better. We can easily add cacti to group wheel.

**Comment by netniV** [comment]
ouch, no.  that's a bad call, wheel is the equivalent of Administrators!

**Comment by xmacan** [comment]
You are right. It is bad idea. I'm doing too many things at once and I wanted to write the group www. But that's not a solution because the group is wheel and not www. My bad. Save session to db is workaround.

**Comment by netniV** [comment]
So, after some investigation, we are definitely using the builtin PHP session handlers.  Something I suspected from previous dealings with CSRF but wanted to make sure I was correct before leading you down a false path.  Therefore, we have no control over the user or permissions used when creating the sessions.

If you set the cacti_db_session flag, we instead include the file in `include/session.php` which uses [session_set_save_handler](https://www.php.net/manual/en/function.session-set-save-handler.php) to override the built in functions and plonk all that data into the database.  This basically negates the original security failure.

Now, if you wish to continue using PHP to create the files locally rather than in the database, you have several choices:

1. Write a script to mod the files (which you have done), 
2. Change the user of the non-website scripts to be the web user
3. Potentially use a different directory where the group is sticky and save your session files there ensuring both the web and the script users have that group

For the last part, look at [session.save_path](https://www.php.net/manual/en/session.configuration.php#ini.session.save-path) and [session_save_path()](https://www.php.net/manual/en/function.session-save-path.php)

It should also be noted, that depending on the OS, PHP itself may not even have the rights to do much with the PHP session files apart from read/write to them, as per [Christopher Kramer's](https://www.php.net/manual/en/session.configuration.php#115842) comment:

> Why does Debian not use PHP's garbarage collection?
> For security reasons, they store session data in a place (/var/lib/php5) with very stringent permissions. With the sticky bit set, only root is allowed to rename or delete files there, so PHP itself cannot clean up old session data. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=267720 .

Further reading on the XY problem of session files can be done via [Palec's](https://stackoverflow.com/a/27079746/697159) comment on StackOverflow. 

For now, I'm going to go ahead and close this as resolved, won't fix because it's not really a problem with our code, more how PHP works.
