### ISSUE TITLE
How to move graph templates to another data source profile.

### ISSUE THREAD

**Issue by georgej77** [Cacti/cacti#4335]
Hi Cacti Team,

We are using custom data source profile in cacti version 0.8.8b. I have installed cacti 1.2.18 on another server. Then, copied RRA files from old system to new server. I have restored DB from backup.
After login to Cacti console, I have noticed that all the template went to wrong data source profile. When I moved the template to another profile, graphs stopped plotting and got blank graph.

Data source profile 0.8.8b
![image](https://user-images.githubusercontent.com/41739394/124584638-1c750080-de72-11eb-9b38-3d8595f36c22.png)

I want to move the graph template to highlighted profile without affecting the existing graph flow. Can you help it.
Data source profile 1.2.18
![image](https://user-images.githubusercontent.com/41739394/124605136-3d951b80-de89-11eb-86d2-f2c71d9c263e.png)

Thanks,
Jinju.

**Comment by netniV** [comment]
I presume you managed to resolve this yourself?

**Comment by annmaria1** [comment]
I have created a New server and migrated cacti 0.8.8 to 1.2.15 last year. So there are two servers running parallel (vm1 (0.8.8 ) vm2 (1.2.15). Recently we have noticed that one week time interval graph is getting on daily average graph and one month graph is getting on weekly graph and so on. It is because the graph template selected the wrong data source profile on server 1.2.15 server. When I moved the graph template to the actual data source, all our graphs stopped writing.
Then I tried to migrate again from cacti 0.8.8 to 1.2.18 on the new server. I have noticed that all the graph templates were moved to the wrong data source profile. We required Daily,weekly,monthly,3month and yearly graphs. So I created the ticket here.
When I check it the next day, the interface graph is plotted with the correct template. But when I looked into the data source template, the graph template was in the wrong profile. I don't know how I got the correct output. But the advanced ping 1.4 graph was not working. So I restored VM2 from the last original backup.
Now I'm thinking of upgrading from 1.2.15 (vm2) to 1.2.18 again. I hope it will resolve my problem.
If the graph template takes the wrong data source profile how can I change it without affecting the graph?
What is the best way to upgrade 1.2.15 to 1.2.18?

**Comment by annmaria1** [comment]
Hi Mark,
Can you provide a good solution for the below highlighting issues?
I have created a New server and migrated cacti 0.8.8 to 1.2.15 last year.
So there are two servers running parallel (vm1 (0.8.8 ) vm2 (1.2.15).
Recently we have noticed that one week time interval graph is getting on
daily average graph and one month graph is getting on weekly graph and so
on. It is because the graph template selected the wrong data source profile
on server 1.2.15 server. When I moved the graph template to the actual data
source, all our graphs stopped writing.
Then I tried to migrate again from cacti 0.8.8 to 1.2.18 on the new server
(vm2). I have noticed that all the graph templates were moved to the wrong
data source profile. We required *Daily,weekly,monthly,3month and yearly
graphs*. So I created the ticket here.
When I check it the next day, the interface graph is plotted with the
correct template. But when I looked into the data source template, the
graph template was in the wrong profile. I don't know how I got the correct
output. But the advanced ping 1.4 graph was not working. So I restored VM2
from the last original backup.
Now I'm thinking of *upgrading from 1.2.15 (vm2) to 1.2.18 again*. I hope
it will resolve my problem.
*If the graph template takes the wrong data source profile how can I change
it without affecting the graph?*
*What is the best way to upgrade 1.2.15 to 1.2.18?*

**Comment by annmaria1** [comment]
Hi,

Is there any way to move the graph templates to id 2 of data_source_profiles.?

MariaDB [cacti]> select * from data_source_profiles;
+----+----------------------------------+-------------------+------+-----------+----------------+---------+
| id | hash                             | name              | step | heartbeat | x_files_factor | default |
+----+----------------------------------+-------------------+------+-----------+----------------+---------+
|  1 | 34ed3e32747a9a405fc164e83a03c4cb | Upgrade Profile 1 |   60 |       120 |            0.5 |         |
|  2 | e6c117ad7f5f6a101bae6866dadaf1d9 | Upgrade Profile 1 |   60 |       120 |            0.5 |         |
|  3 | e44c8f41fadc88bf882c40852f438dbd | Upgrade Profile 1 |  300 |       600 |            0.5 |         |
+----+----------------------------------+-------------------+------+-----------+----------------+---------+
3 rows in set (0.000 sec)

MariaDB [cacti]> select * from data_source_profiles_rra;
+----+------------------------+----------------------------+-------+--------+-----------+
| id | data_source_profile_id | name                       | steps | rows   | timespan  |
+----+------------------------+----------------------------+-------+--------+-----------+
|  1 |                      1 | Daily (1 Minute Average)   |     1 |   1440 |     86400 |
|  2 |                      1 | Weekly (1 Minute Average)  |     1 |  10080 |    604800 |
|  3 |                      1 | Monthly (1 Minute Average) |     1 |  43200 |   1814400 |
|  4 |                      1 | 3Month (1 Minute Average)  |     1 | 129600 |   5237568 |
|  5 |                      2 | Daily (1 Minute Average)   |     1 |   1440 |     86400 |
|  6 |                      2 | Weekly (1 Minute Average)  |     1 |  10080 |    604800 |
|  7 |                      2 | Monthly (1 Minute Average) |     1 |  43200 |   1814400 |
|  8 |                      2 | 3Month (1 Minute Average)  |     1 | 129600 |   5237568 |
|  9 |                      2 | Yearly (5 Minute Average)  |     5 | 103680 |  15712704 |
| 10 |                      3 | Daily (1 Minute Average)   |     1 |   1440 |    345600 |
| 11 |                      3 | Weekly (1 Minute Average)  |     1 |  10080 |   2618784 |
| 12 |                      3 | Monthly (1 Minute Average) |     1 |  43200 |  10475136 |
| 13 |                      3 | 3Month (1 Minute Average)  |     1 | 129600 |  31536000 |
| 14 |                      3 | Yearly (5 Minute Average)  |     5 | 103680 | 126144000 |
+----+------------------------+----------------------------+-------+--------+-----------+
14 rows in set (0.000 sec)

MariaDB [cacti]>

**Comment by annmaria1** [comment]
Let me try to use splicerrd

**Comment by netniV** [comment]
Sorry, I have not been around and I have never manually moved sources between profiles.  At the moment, I haven't enough free time to have a look.  There is a couple of RRD cli's that would handle things, I think splicerrd is one that should work well for you.

**Comment by annmaria1** [comment]
Thanks.
I used splicerrd to resolve the issue.

There is a gap on graph When i using spine for polling. Investigating it.

[image: image.png]

**Comment by TheWitness** [comment]
The solution to this would be a good README or video.  There way to do this for existing RRDfiles is a little complicated.  You have to do it in a few steps:

1) Change the Data Template to the new profile (easy)
2) Update the data_template_data table and change rrd_step and data_source_profile_id manually to the correct values (not so easy, but strait forward)
3) Update the data_template_rrd table and change the rrd_heartbeat to the correct value (not so easy, but strait forward)
4) Rebuild the poller cache (easy but potentially timely)
5) Use the splice_rrd.php and a small script to:
a) Copy all the impacted RRDfiles to a new directory 
b) Allow Cacti to recreate those RRDfiles using the poller, 
c) Running splice_rrd.php to merge the old RRDfile data into the new structure. (painful for a rookie)

**Comment by TheWitness** [comment]
I hope this helps.  I've done it many times before even using a batch scheduler to perform all the splicing.  Makes it pretty fast when you have 100k+ rrdfiles.
