### ISSUE TITLE
Last 3Months show wrong graph ! on version 0.8.8b

### ISSUE THREAD

**Issue by networksafe** [Cacti/cacti#4453]
hello guys
have a good time

Im using old cacti (Version 0.8.8b)
today I realized cacti dosnt show previous graph correct !

for example : 1day or 1 week or 2 month shows correctly !

**but when I choose 3month or previously, cacti dosnt show correctly !**

**can you help me to fix it ?**
its very important for me to fix this problem and dont upgrade, please help me

_unfortunately I cant upgrade cacti to the newest version,
I got backup from cacti and setup on another machine, I try to update, when update complete and cacti loaded in graph shows :
Failed to open data file, poller may not have run yet :
my_device.rrd
(RRA Folder : root)_

last day :
https://gcdn.pbrd.co/images/Blmr3p8GEQjV.jpg

last week
https://gcdn.pbrd.co/images/C6ZPh9k6rBwr.jpg

last month
https://gcdn.pbrd.co/images/dPUzfF6F6jZI.jpg

last 2month
https://gcdn.pbrd.co/images/rHTUx5HsLcBr.jpg

last 3month
https://gcdn.pbrd.co/images/ioEm9aEZovzD.jpg

last 6month
https://gcdn.pbrd.co/images/bU75oTksbY7C.jpg

last 2years
https://gcdn.pbrd.co/images/7eoy01GypfJu.jpg

My Setting :

https://gcdn.pbrd.co/images/7vlRYZJmSEDv.jpg
https://gcdn.pbrd.co/images/2tlSUCzZOY8v.jpg

best regards

**Comment by netniV** [comment]
Unfortunately, we don't actively support 0.8.8b.  You can find help from other users on our forums https://forums.cacti.net

With regards to the upgrade, did you follow all the steps of our upgrade guides?  You need to ensure that when you migrate between 32-bit and 64-bit versions of the host, that you export and import your RRD data as well because the file structure changes (an RRDtool limitation, not ours). 

Finally, your paths to software and data should be in the exact same places if you are upgrading an existing databse.  This is because many paths are stored within the database, not just based on the configuration file.  

You may also need to setup a cron schedule if you haven't done so.

**Comment by networksafe** [comment]
> RRDtool limitation, not ours).

Thanks A Gazillion 
Yes, I updated it with step by step guid line but dosnt work and there are many problems !

can you help me for upgrade this ?


is there version compatible with 0.8.8b ?
can you propose to me one of version?

which one of version that can I upgrade without problem ?

**Comment by netniV** [comment]
You should be able to upgrade to any version as long as you ensure that you export/import all your RRD's (if switching between 32-bit and 64-bit) and keep everything in the same file locations.

We have had plenty of people upgrade from 0.8.8 through to 1.2.x

**Comment by xmacan** [comment]
I will help you, if you want. Please send me mail - petr.macek@kostax.cz
