### ISSUE TITLE
poller_reindex_hosts.php can not connect to cacti database

### ISSUE THREAD

**Issue by GitHub2022** [Cacti/cacti#4524]
Cacti 1.2.20 

The script doesnt start as it seems like it can not determine the mysql connection:

php poller_reindex_hosts.php --id=all
FATAL: Connection to Cacti database failed. Please ensure: 

  - the PHP MySQL module is installed and enabled.
  - the database is running.
  - the credentials in config.php are valid.

**Comment by GitHub2022** [comment]
Addition - PHP-SNMP is disabled because of the usage of SNMPv3.

**Comment by TheWitness** [comment]
Sounds like a config issue.  Maybe a permission issue, in that maybe it can not read the config.php?

**Comment by netniV** [comment]
Ensure that you are running your cli scripts using the same user that servers the website (eg, sudo su -u www-data php -q cli/poller_reindex_hosts.php --id=all).  I tend to run all the scripts from the cacti root dir, but running any CLI program should correctly resolve itself.

This is most likely a permission issue rather than a bug.

**Comment by GitHub2022** [comment]
yes that solved the problem! Thank you my fault.
