### ISSUE TITLE
Graph based on template bug during unlock procedure

### ISSUE THREAD

**Issue by linusky** [Cacti/cacti#455]
Hello,

I use Cacti 1.0.5 on Centos 7.3 + Mysql 5.5.21-log.
I have built a new Graph Template including 20 Areas stacked and declared Graph Item Inputs for 20 colors and 20 Data sources.
If I use this template to create new graph all works fine. Next I can edit and unlock the graph to select for each Data source the Ds I want to assign in the Combobox displayed.
I have more than 2000 Data Sources configured and unlock this graph take very long time because PHP script must fill the combobox of each Data Source with the 2000+ data sources (around 2 min on Intel i7).

My problem is that the mapping between the Data sources selected in each combobox and the data stored in the Database is wrong.
After selected the 20 data sources in the Graph and saved the modification, some data sources (3 or 4, depend) are not saved and the combobox still at 'none assigned'.
For the moment, to fix it and display the Graph, I had to find into the Database, using SQL requests into 'graph_templates_item' and 'data_template_rrd', all the ID of each data source I want and update all row manually for this Graph.

There are not error or message into the log and Cacti say that all is OK.

I hope my explications are sufficient.

What more informations could I give you to help you ?

Thank you

Olivier

**Comment by cigamit** [comment]
This is a hug problem with the way data sources work in Cacti.  However, for this problem you will need to break things for us one more time.  Here is the procedure.

1) Install Firebug Firefox extension.
2) Enable it, and open and enable the console
3) Goto the page in question and note that entries showing 'GET' will start showing up in the console.
4) Edit the template, and then before hitting 'save'.  Clear the console so that there are not entries there.  Then press save.
5) At this point, you will see and entry with 'POST'.  Open the entry by clicking on the plus sign, and goto the 'Post' tab.
6) Enlarge the firebug window so that you can see everything, and take a screen shot of this window and attach into this ticket.

I'm not sure that we can make the speed much better.  We are working on a new syntax for aggregate graphs that get's you out of this 'manual' and difficult hand graph edit.  But it's not ready yet.

**Comment by linusky** [comment]
Hello,
I will try to follow your procedure and retrieve all informations as asked, next I'll back to you.

**Comment by cigamit** [comment]
Yes, please do.  Some of these corner cases are hard to debug and so you need to put in a lot of effort to either self diagnose, or fee developers enough information to determine a root cause.

**Comment by cigamit** [comment]
Still waiting.  I'll give this a day or two more before I close.
