### ISSUE TITLE
detect the graph with stale rrd or missing rrd 

### ISSUE THREAD

**Issue by gj00354347** [Cacti/cacti#4639]
# Feature Request

## Is your feature request related to a problem? Please describe

Hi All ,

many times our customer write to us , like , Hey Gopal , Can you please check this graph x , y , z of device ABC , it is displaying NAN  and troubleshoot .

then we log into poller , fire snmpwalk and find that snmp time out issue is there or may be a wrong community string or may be data range is too high or low or may be that interface is down or  some other reason and that causes the graph to display NAN .

but this approach is reactive and not proactive . Like customer faces issue with some switch or routers and then he wants to see the performance graphs and then he discovers that the interface for which he is looking graphs are NAN and he is completely blind on that .

## Describe the solution you'd like

so can you please add a url in Management Tab where we can use filter like , poller , device or device template , graph template and list the dysfunctional graph which means the graph whose rrd file is not populated for the last 24 hours or more than that or whose rrd file is missing for the last 24 hours and we can find those NAN graphs and work on them proactively rather than waiting for customer's input .

may be you can add a feature or a plugin where we can schedule a report of devices based on device template and find the dysfunctional /stale graphs and send a report to customer or to ops team .

## Describe alternatives you've considered

I belive solution lies some where in the database table where we have mapping of graph and rrd file and then we can scan the rrd file for that particular device and find the stale rrd file and using the mapping of rrd file and graph in database table , we can have this solution.

**Comment by bmfmancini** [comment]
Hey Gopal this is not a cacti supported script however what ive done in the past is call on rrdtool to check if the last x values written to the rrd have nan's which usually indicates there is not value 

It a bash script that I was looking to convert to something else that can be multi-threaded to be faster  

https://github.com/bmfmancini/RRD_Data_Check

**Comment by TheWitness** [comment]
Well, this seems like a good extension of the data debug feature for daily batch data debug.  I'll be adding a 1.2.22 release in milestones soon.  It can be added to the 1.2.22 as an enhancement.

It would have to be parallel for customers with over a million rrdfiles, and it would have to lock around the feature to move to structured paths on the fly which was for me a near term requirement.

**Comment by TheWitness** [comment]
@xmacan, start with poller_dsstats.php.  it's a parallel poller, then you need a temp table with all the rrdfiles in it and distributed to each thread, then just follow the data debug path.  Maybe as a second thought make the data debug script parallel. Boost does almost the same thing, splits the data sources island assigns a thread and then each thread does it's thing.

**Comment by bernisys** [comment]
@TheWitness, do we need "dsstats" activated to make this functionality work?
We have that feature disabled in our environment because of the huge DB load it imposed.
Is it safe to turn it back on after several SQL query improvements had been made inside Cacti in the past?

I had written a perl script in the past, which processes thru all rrd files, grabs the data rows, and analyzes them to detect periods of no data, but as there are literally hundred thousands of files, this takes weeks ...

**Comment by xmacan** [comment]
I was talking to @TheWitness about it. My idea was (without dssstats): 
Basically, I'd like something like a poller_output table that would populate with defective DSs with each cycle. I would process them in each cycle, created a graph of it intropage and did an admin email if the graph is not functional last hour/24 hours, ....

He agreed but we wanted discuss it more. 

I like this better than periodic startup (once per hour or day) and searching in rrd files. This will be time consuming for many files. I just can't estimate how much poller time will increase with such a modification. 

If I understand correctly, it would be enough to extend the *process_poller_output function - when a 'U' value is returned, it is logged to the mysql table.

When @TheWitness  says "yes", I'll try to prepare it

**Comment by TheWitness** [comment]
I've got the same issue right now.  I also really need DSSTATS in production, but I'm fearful to turn it on in production which has 900k+ RRDfiles.

I've made it parallel now, so that's good though I want to go further.  One of the reasons that I haven't turned it on yet in production is timing and ancillary things being more scalable like boost.

With the latest boost improvements in 1.2.21+, I'm now comfortable with a 1B row archive table.  So, boost can now be on a 6 hour cycle which is great.  That means there is more time between DSSTATS updates too.

So, its just about time to revisit it from my perspective, but I have to make time for it. That's the hard part.

If your dev environment is at 1.2.22, you should spin it up.  Put boost on a long cycle and hit the database with 10 or so DSSTATS threads.  Report back how it went.

**Comment by TheWitness** [comment]
BTW, the answer to your question is no.  You literally can write a simple script for it.  I've already written one, likely I've lost it from all the projects I'm working on and are not finished with at the moment.

The latest structure paths script could be repurposed for such a thing.  It's parallel now too, or you could just write a script using `find rra -mtime 10`, and parsing that list and comparing to the path in the poller items table for what should otherwise be live data sources.

**Comment by TheWitness** [comment]
Petr, the problem with 'U' detection is spike kill.  It sends unknown data if the SNMP Agent restarts to suppress spikes.  So, that's just one 'U' though.  So you could write a rule to ignore the onesies in the table.

I would say go for it though.  It would nice for there to be a panel for that too.  But remember, bulk updates....

**Comment by TheWitness** [comment]
Also, it's been quiet for a while.  Good thing.  Though, there are more changes coming.  There is a reindex bug that I'm just about to commit.  Makes reindex parallel too. @bmfmancini will be happy for that.

**Comment by bmfmancini** [comment]
Yes!

**Comment by xmacan** [comment]
Ok, all is clear not. I will prepare it in few days for testing

**Comment by TheWitness** [comment]
Looking forward to i @xmacan!

**Comment by xmacan** [comment]
@gj00354347 something like this? I made copy from dsstats paraller poller, I need few days for finish and testing. I have only small installation. Could you test this feature on bigger installation?
![Screenshot 2022-08-24 at 15-15-11 Console Rrdcheck](https://user-images.githubusercontent.com/26485719/186430878-d8e4698a-479c-453a-8a1e-73183cf2de4d.png)

**Comment by TheWitness** [comment]
Sweet.  Use one of the parallel examples I committed recently to stretch this out.  I think the `find` command is fine for Linux installation, but for Windows, I don't know.  But it looks like you are checking more than the recent touch date, so maybe one of the parallel server examples should be fine.  Should turn it into a generic Class library, but I'm stretched on time ATM.

**Comment by xmacan** [comment]
yes, I used your dsstats paraller poller (I made a copy, rrdcheck is indepndent on dsstats). Your parallel code works well. It isn't only about touch date, I need check values in rrd files for stale values.  Touch test could optimize it a bit, I'll report files that haven't been accessed for a long time. 
I added few option to settings like dsstats, you can select how often run and how many threads.
Now I have few day off. I would like to complete this issue in few days.

**Comment by xmacan** [comment]
@gj00354347 - merged. You can try actual 1.2.x branch and let me know.

**Comment by TheWitness** [comment]
Officially resolved in #4943

**Comment by TheWitness** [comment]
Going to close as resolved, though you can still continue the conversation.

**Comment by TheWitness** [comment]
Great work @xmacan !
