### ISSUE TITLE
Data input method: Graphs are not plotting, Cacti: 1.2.18

### ISSUE THREAD

**Issue by mihirprad** [Cacti/cacti#4642]
# Describe the bug

Cacti is not passing inputs to scripts when creating a graph.

## To Reproduce

1. Go to Management -> Data Input methods

2. Create a Data input method using Script server

3. In the input string, specify the path to script and various inputs such as <ip> <snmp_port> <snmp_version>

4. See error/ logs

## Screenshots
![image](https://user-images.githubusercontent.com/84665785/159599965-c50c62a5-7296-4103-9ec0-43467a41245d.png)
![image](https://user-images.githubusercontent.com/84665785/159600042-474cc07c-338b-4f62-a3f6-83a92540b631.png)
![image](https://user-images.githubusercontent.com/84665785/159600158-54feaf04-8f1e-468f-a0c8-0d1c2b362028.png)

black boxes represent data

According to the logs, the script isnt receiving any inputs. I have configured the inputs in data input method such that the inputs are automatically passed in by cacti based on the host. however this is not happening.

## Desktop 

- OS: RHEL 7

- Browser: Chrome

## Additional context

In addition for other data input methods that ARE passing data to the script an error occurs when creating the graph.

**Comment by mihirprad** [comment]
Hi so I have managed to fix the previous issue, however it looks like manual user inputs are still not getting passed into the script.
![image](https://user-images.githubusercontent.com/84665785/159619593-3a7ea7b5-fa60-42a7-8199-282ef6e1269f.png)
These input in the data input are meant to take in user input. however the inputs do not get passed into the script.
![image](https://user-images.githubusercontent.com/84665785/159620827-cb64fc22-eb4c-4b00-b833-098fc2695673.png)

this is what the script receives:
![image](https://user-images.githubusercontent.com/84665785/159621474-321c6fb5-4e7a-4995-9c22-b1f54bb6519b.png)

note: "unchanged" refers to the default value given to the input via data source template

**Comment by TheWitness** [comment]
I'm going to punt to the 1.2.20 release due up this weekend as the solution.  However, can you please look at your poller cache and see what is missing?  In Cacti 1.2.20 everything should be quoted, so it'll be easy to differentiate between columns.

I would prefer use use the hostid special type code instead of passing in all those details though.  That way in your script server script you can do something like the following:

```php
$device = db_fetch_row_prepared('SELECT * FROM host WHERE id = ?', array($hostid));
$snmp_version = $device['snmp_version'];
<snip>

```

And then pull the records right from that object.  If the system is really big and you have 10's of thousands of these calls, it might be better to continue to pass all of them, but it would reduce the bug hunting by orders of magnitude.

**Comment by TheWitness** [comment]
If you can't wait, then just upgrade to the latest 1.2.x branch this way (assuming your installed from source).

```sh
cd /var/www/html
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti.new
chown -R apache:apache cacti.new
/bin/cp -rfp cacti.new/* cacti
```

Then hit F5 on your browser to force the upgrade.  Pretty simple actually.

**Comment by TheWitness** [comment]
No feedback.
