### ISSUE TITLE
Implement bulk change for large group of entities (devices, data sources, graphs)

### ISSUE THREAD

**Issue by stefanbrudny** [Cacti/cacti#4798]
I can't delete huge amounts of entities nor I can automate removal of these (more than eg. 50k). 

I'd like to have an ability to select ALL entities and NOT ONLY the ones in a visible page of a table and execute action on all of those. It is important to have a feedback about the action, eg. the action can be executed in the background or in foreground, but I really must be sure that it was executed. I expect progress bar or an option to put the action into 'deep background' so the results are logged.

Also, there is missing reindexing method and potentially other actions to be executed on devices (assuming this should be another ticket).

It happen from time to time in Cacti that an action is silently broken, therefore feedbackis amust.

The only alternative is to delete manually hundreds of thousand of entities (graphs, devices, data sources etc) which is impractical (thousands of repetitive actions). Using direct DB access was considered, but its not vital option for secure access for users. 

I ask for this since 2015 (https://forums.cacti.net/viewtopic.php?f=21&t=54036) and it really  prevented myself from installing Cacti for a  large scale (I had more than ~ 10 installations larger than 250k of devices). Instead, I had to use custom scripts.

**Comment by cigamit** [comment]
If you would like to submit a patch or pull request then feel free.

**Comment by TheWitness** [comment]
Large bulk changes need to be CLI driven, and remove actions have always been lacking in the CLI space.

For the web side there have always been post size issues, GUI response, and timeouts that plague us, and even if you could live with some of the slowness, php-fpm does not always accept longer timeouts.

So, the browser will get a gateway timeout, while the action actually can continue and does continue. It didn't used to be that way, but that changed with php-fpm.

So, what @netniV did with the installer was interesting. He starts a transaction and then polls via a callback if it's complete or not.  So, you don't have to worry about browser timeouts.  Doing that generally, the way Cacti is written may be difficult.

**Comment by stefanbrudny** [comment]
@TheWitness I'd say not really must all be CLI driven in regard of removal. I'd say marking / disabling graphs / disabling dead hosts / and other similar actions could be done by Autom8 and THEN purged from the disk. I do understand the rationale (post size issues), and this is actually preventing myself from using arrays larger than ~ 50k. I can perform proper analysis which features exactly are needed for my case...

...which is very simple: if my customer screws, creates 10k of wrong graphs using autom8, I need to clean it and as he is not the only user in this installation, I must be careful. Either CLI or web gui won't help as of today.

**Comment by stefanbrudny** [comment]
@cigamit I am not using cacti at professional work since ~2012 because of these issues. I try every year to review what is happening at Cacti, thus we write.

You are wrong in your assesment ("You seem to be using cacti for large installs with a very specialized use case"), my use case is (was) very standard yet difficult for current Cacti version.

One exception from the standard approach is I have ever changing CPE base, look, in installation of 100k devices:
* every month churn of devices is 10-20k, I need to disable them as spine mostly waits for responses, doing nothing, these devices may return up to 6 months, but also may not return back anymore,
* every month new devices are created at a pace of 12-24k (installation grows a little)

Other than that, I need to retrieve: 
* uptime, basic device data (10-20 OIDs)
* interface traffic (up to 6 OIDs)

So in comparison to static, old-times-traditional-dusty data center installation, I only have changing environment (there is much more, but not relevant for this discussion).

The difference is that admin in DC would have to clean once a year or two or can even live with some bloat. Myself, I need to clean manually every month or sometimes 2 weeks.

In so changing environment, even my smallest installations at ~ 50k are very challenging for Cacti (marketed for hundreds of thousands of devices, that's a big stretch if this case is considered). 

My bet is I am not alone. I can clearly see it in a forum and in the telco industry. Closing topics in forum prevents others to comment and see that others have same issue. Closing here, people will not even know that a patch is welcome.

**Comment by TheWitness** [comment]
50k devices these days is manageable, but not especially pleasant.  Management pages like Graphs and Data Sources are a bit unwieldy though, and the Presets and Templates pages could us some caching of Object Counts as the slow down those pages.

We had considered pinning the Graphs and Data Source Pages as Sub Tabs of Device edit, which is what just about every other tool does due to performance and UX reasons, and had in fact done that for the never releases 0.8.9 release.  Maybe we should consider that again. We would have to preserve both the Graphs and Data Source Pages for other reasons, but the could be optionally turned off.  I've encountered cases where I want to delete 10's of K Graphs from a single template, and yea, it goes slow.  There have been many cases where I just have scripted it. 

With 100k plus devices and a lot of churn, I would do what other large telcos do and create multiple pollers and automate the device add and removal using your CMDB as the gospel.

**Comment by TheWitness** [comment]
50k devices these days is manageable, but not especially pleasant.  Management pages like Graphs and Data Sources are a bit unwieldy though, and the Presets and Templates pages could us some caching of Object Counts as the slow down those pages.

We had considered pinning the Graphs and Data Source Pages as Sub Tabs of Device edit, which is what just about every other tool does due to performance and UX reasons, and had in fact done that for the never releases 0.8.9 release.  Maybe we should consider that again. We would have to preserve both the Graphs and Data Source Pages for other reasons, but the could be optionally turned off.  I've encountered cases where I want to delete 10's of K Graphs from a single template, and yea, it goes slow.  There have been many cases where I just have scripted it. 

With 100k plus devices and a lot of churn, I would do what other large telcos do and create multiple pollers and automate the device add and removal using your CMDB as the gospel. 

I'm in the HPC space these days, and when we are burning up cloud instances, we can easily add 10k devices in a day, and the a week from that day, never see them again.  Yea, thats kind of matches your CPE case too.

**Comment by TheWitness** [comment]
One slight correction and it might be a typo "hundreds TO tens of thousands".  If it say "hundreds of thousands", it's a typo.

I had put it at about 50k, the way spine was engineered for a single poller, sure you can get higher, but pushing it.

I have not reassessed that subsequently after all the semaphore work by @netniV and the changes to hardware re threads and MariaDB's improved thread handling.  Maybe I'll do that again at some point.

**Comment by TheWitness** [comment]
Just confirmed:

"All of this is wrapped in an intuitive, easy to use interface that makes sense for LAN-sized installations up to complex networks with tens of thousands of devices."

Web site is right. Now that I'm a Cacti customer (again), I've started addressing scalability.  For example in the 1.2.20 release, I pretty much re-engineered the permissions system, which when you get 1M plus graphs, it kind of melts down as soon as you start restricting things. 

@stefanbrudny, It would be nice if you could log specific feature requests, having pointed feature requests vs. broad ones will make the remaining easier to go after.

Thanks!

**Comment by TheWitness** [comment]
@stefanbrudny, marking disabling Graphs and Data Sources was on the 1.2.22 roadmap.  I need it for work, so, it'll be coming sooner than later.

**Comment by stefanbrudny** [comment]
Yes, meant "hundreds of thousands". Not hoping for millions. Yet.

"With 100k plus devices and a lot of churn, I would do what other large telcos do and create multiple pollers and automate the device add and removal using your CMDB as the gospel."

See, this is where things are more complicated. Telcos do not generally use SNMP, it is considered obsolete outside of DC, as it does not allow for structural management. CMDBs are used for feeding other systems, which use other protocols for communication than SNMP, more suitable for management at volumes of tens of millions of devices (double checked, no typo this time, >10M of devices using single clustered installation). CMDBs feed other systems rarely for monitoring purpose - this is not considered important, they feed it for devices provisioning. I don't think anyone in telco does anything what is not explicitly necessary, and if there is no utmost importance, performance monitoring won't land in their diagram of critical systems and their connections.

So why bother with Cacti you may ask? well, turns out there is niche and at some point SNMP remains supplementary for basic monitoring. It remains handy for small to mid scale (now in telco 100k - 400k, in some world regions even more), for companies without significant budget and / or as supplementary for legacy systems. And for larger companies it can be handy and delivered as a service, providing... it does not rely on CMDB, and simple scanning for devices within the network is enough.

This is why bulk management, flexibility and fast management in Cacti is needed, at least if it is not consumed totally by other protocols.

**Comment by TheWitness** [comment]
> 10M Devices.  That's a lot.  I'm curious, the protocols they are using are likely distributed steam protocols with a distributed database.

The industry seems hot on things like AMQP, Telemetry, Telegraf, Prometheus, etc.  These are basically agent based push services that deliver unsolicited data to the monitoring cluster.  Cacti could do that, and I started a specific plugin for that, but I'm finding it hard to maintain interest.
