### ISSUE TITLE
Feature Request - Export table results to Excel, PDF or CSV

### ISSUE THREAD

**Issue by smiles1969** [Cacti/cacti#486]
A cacti function to export the current table results to Excel, PDF or CSV.  

This would be VERY useful for exporting the devices table, or any other plugin that utilizes the built-in Cacti html_nav_bar functions.

Ideally this could be added as an action in the action dropdown selection.

Possibly just integration of an existing php library like PHPExcel?

**Comment by cigamit** [comment]
Great idea.  It'll be CSV though.

**Comment by smiles1969** [comment]
Any ETA on this?

**Comment by cigamit** [comment]
To be honest, I'm pretty busy at the moment.  By the end of the day, this is the last thing I want to work on, and we are not getting a lot of help on feature enhancements at the moment.  This is likely due to the fact that it's summer time.  Likely won't be doing any big things for at least a month.  It'll be in the 1.2 branch for sure.  We are restricting the development branch to bug fixes only right now, and that is taking the lions share of the effort right now.

**Comment by smiles1969** [comment]
Ok, thanks for the update

**Comment by cigamit** [comment]
I wanted to do this in a generalized way, but I think I'll just do it for the devices table today so we can close this.

**Comment by cigamit** [comment]
Done.  No import, but export is there.

**Comment by naransho** [comment]
I notice that this was made available in 1.1.17. I am using 1.1.28. Where are the options to export available?

**Comment by netniV** [comment]
When you are on the devices list under Console -> Devices, select the device details you wish to export and then click the Export button.  The button appears differently depending on if you have the filter section collapsed or expanded. 

- If expanded, it'll be a button that's labelled "Export"
- if collapsed then it's an icon of a downward arrow and when you hover over it it'll say "Export"
