### ISSUE TITLE
Maximum and Minimum of graphs on Daily Basis.

### ISSUE THREAD

**Issue by mrneilk** [Cacti/cacti#4891]
# Feature Request
A feature that can generate a daily or bi-weekly report of all the graphs having traffic that shows maximum and minimum of that graph in some duration of time say one day, or two days, or hourly basis.

I don't know whether this option is available or not, if it is available some one can get me know how we can achieve this.
I would like a csv or a excel file generated as a report showing all the active graphs maximum and minimum amount of traffic on that particular period of time.

Its like automation of maximum and minimum traffic compiled into one sheet for referral at later point of time.

Thanks for your support.

**Comment by bernisys** [comment]
I have modified the traffic template in our setup to achieve a similar result.

You can add dashed max/max and min/min lines to the "interface traffic" output, and you can also have the min and max values printed into the legend.
Then all your graphs would have the same information with just modifying the standard template.

This is what our setup for the traffic graphs looks like:
![image](https://user-images.githubusercontent.com/32120318/185373198-c028d5f0-d54c-4749-af4d-8124f150979c.png)

This is a sample output, you have the average area as usual, overlayed by the dark line, indicating the "max" values, so that your information about peaks is not averaged away in longer graph time periods.
![image](https://user-images.githubusercontent.com/32120318/185373559-6cb1da20-8dde-4f0d-8323-4ad2f91bd19f.png)

This example also shows the 95th percentile lines, which show basically the amount of traffic, which the graphs stays below for 96% of the time. For that, i just need to know how to convince cacti to show the correct unit (k, M, G ...) in the legend - it works properly with the graph, but the legend is missing the unit somehow. Ideas welcome.
![image](https://user-images.githubusercontent.com/32120318/185373777-e6b1229f-ec94-4509-93b0-4f2020936aca.png)

**Comment by mrneilk** [comment]
It would be more of ease if i could import the maximum/minimum data as raw data for making analytics reports. But this feature also looks great. Thank you for the enhancement.

**Comment by TheWitness** [comment]
@bernisys, is your company good with contributing this?  If so, forward the exported device template this way and I can have it incorporated into the default packages.

**Comment by bernisys** [comment]
@TheWitness: Hi Larry, sorry for answering late.
yes i had asked a while ago already and they are okay with exchanging such data.
It's only fair, this should be a give-and-take situation.
Shall i send it via mail or attach it here in the ticket?

**Comment by bernisys** [comment]
OK, here we go:

[Cacti Template - Traffic with peaks and percentile.zip](https://github.com/Cacti/cacti/files/9534732/Cacti.Template.-.Traffic.with.peaks.and.percentile.zip)

Please tell me if that is okay or if i have missed anything important.
I believe i just modified the original template, i did not create a separate one.
