### ISSUE TITLE
error opening graph

### ISSUE THREAD

**Issue by hnomkeng** [Cacti/cacti#493]
Validation error for variable graph_start, with value of "NaN". See backtrace below for more details.
(/graph_image.php: 35 get_filter_request_var)(/lib/html_utility.php: 430 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

https://hnomkeng.com/cacti/graph_image.php?local_graph_id=8&graph_start=NaN&graph_end=NaN&graph_width=NaN&graph_height=NaN

**Comment by cigamit** [comment]
What version and what were you doing when this error was thrown?  If it's from a fresh upgrade, did you clear your browser history on Chrome, or hit F5 on IE or FF?

**Comment by hnomkeng** [comment]
last github today.

เมื่อ 28 มี.ค. 2017 7:03 PM "Jimmy Conner" <notifications@github.com>
เขียนว่า

**Comment by hnomkeng** [comment]
![cacti_8](https://cloud.githubusercontent.com/assets/9112684/24403991/88c2b14a-13e9-11e7-9487-660e64e593f7.png)

test with Chrome and Firefox

**Comment by cigamit** [comment]
Is this a fresh install?  Does the error go away once the rrdfile is created?

**Comment by cigamit** [comment]
Also, you have not answered my original question yet.  Please re-read and answer very precisely.

**Comment by hnomkeng** [comment]
@cigamit Yes, new install.

**Comment by cigamit** [comment]
Again, you have not answered my question.  What section of the GUI were you in and what action did you take to generate this error?

**Comment by cigamit** [comment]
Also, did the problem go away once the rrdfile was created?

**Comment by reboot1983** [comment]
@hnomkeng 
I suggest you open a topic at [http://forums.cacti.net](http://forums.cacti.net). That's where the forums are for.

Since you've made a fresh install, my first guess is: your directory permissions are incorrect.
The cronjob for poller.php is running (every 5 minutes?) at a specific user, so you must verify that this user can write to the cacti/rra, cacti/log and cacti/cache directories.

Please also see: [http://www.cacti.net/downloads/docs/html/unix_configure_cacti.html](http://www.cacti.net/downloads/docs/html/unix_configure_cacti.html)

**Comment by cigamit** [comment]
I'm going to close this one.
