### ISSUE TITLE
RRD file cleaner does not delete orphaned RRD files

### ISSUE THREAD

**Issue by jhonnyx82** [Cacti/cacti#508]
When RRD files are listed after a scan in the RRDfile cleaner utility, the files are not deleted.

I verified that both apache and cactiuser has rights to delete the files but the files are not deleted.

**Comment by browniebraun** [comment]
Once marked for deletion RRDcleaner will put those entries into a table queue, which will be processed at the bottom of the next poller run. You only have to wait for the next poller run and do not run a rescan in the meanwhile. Due to that reason Apache does not need to have the permission for removal.

Regards
-Andi
