### ISSUE TITLE
Add parameter "version" for Graph Templates

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5130]
Now we have version only in package but not in cacti (console -> templates). So sometimes it's unclear which version I'm using. Sometimes I need compare templates with another cacti installation.
Add parametr "version" would solve this. Add for device, graph, data and data query template. It was my idea ;-)

We discussed about it @TheWitness  - he extended this solution. It would be nice to be able to roll forward and roll backward versioning as well. Two possibilities:
1) every time you modify a template create the XML file and drop it into an archive table that you could then selectively restore a template at any point in the past. It would have some downstream implications if rrd files for example were created from a data template. So we have to be a little bit careful there
2) snapshots - add a snapshot option to the drop-down menu inside of the template and then prompt the user for the version and then append the timestamp to that version and then when they publish they would remove the timestamp of course and put whatever version they want on there.

**Comment by TheWitness** [comment]
Instead of each change.  I would propose a new table that has a large blob that stores the modified packages.  It does this by doing the following:

For each Template Object, Provide the following two options:

* Create Snapshot, and 
* Restore from Snapshot

Those options are the following:

* Device Template
* Graph Template
* Data Query

Each snapshot is literally a package.

When you create a snapshot you can alter the version.  By default, the version will be $version+timestamp()

For example:

1.2.23-167.....

You should also be allowed to Name the snapshot.

**Comment by TheWitness** [comment]
The version parameter is there now, but not the archiving.  I will take those requirements to the packing plugin update and go from there.  Considering this one done.
