### ISSUE TITLE
Boost log file visibility and rotation not as expected

### ISSUE THREAD

**Issue by KnoAll** [Cacti/cacti#5640]
When the Boost debug log is configured in the Performance tab, the file is not visible in the 'Logs' tab, and the files does not rotate.

## To Reproduce

1. Go to 'Settings > Performance'

2. Configure Boost Debug Log > eg: /var/www/html/cacti/log/boost.log

3. Navigate to Logs and under the dropdown the debug log does not appear as an available log

4. The debug log also does not rotate as the other logs do per the log rotation settings. (This resulted in the debug log file that was accidentally left configured consuming over 50GB of disk space filling the volume)

**Comment by TheWitness** [comment]
This is not a bug, but an enhancement.

**Comment by TheWitness** [comment]
@KnoAll

I'm working again on 1.3 now.  I'll be tackling this next week.

Larry

**Comment by TheWitness** [comment]
This is resolved no.  A few points:

* The boost debug log must exist in the same directory as the Cacti log, otherwise an error will be issued
* The boost file will be named boost.log
* Rotation happens like any other file
* File will be accessible from the Log tab just like standard error and the normal Cacti log.

![image](https://github.com/user-attachments/assets/cc3e2592-f409-4a80-b1ad-552b5b118b26)

![image](https://github.com/user-attachments/assets/744c5b83-f810-4ad6-9560-177257cd0f63)

![image](https://github.com/user-attachments/assets/93fc6d13-acb8-49a1-933e-53548a70cb59)
