### ISSUE TITLE
Fix issues with posix-based kills on Windows

### ISSUE THREAD

**Issue by MSS970** [Cacti/cacti#5806]
Cacti version: 1.3 [Dev]
OS: Windows 2019

ERROR PHP ERROR: Uncaught Error: Undefined constant "SIGTERM" in D:\cacti\apache\htdocs\cacti\lib\poller.php:2401 Stack trace: #0 D:\cacti\apache\htdocs\cacti\plugins\thold\poller_thold.php(94): register_process_start() #1 {main} thrown in file: D:\cacti\apache\htdocs\cacti\lib\poller.php on line: 2401

/lib/poller.php line: 2401 is not supported in Windows
posix_kill($r['pid'], SIGTERM); 

**To resolve this bug:**
if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
    posix_kill($r['pid'], SIGTERM);
} else {
    exec("taskkill /PID " . $r['pid'] . " /F");
}

**Comment by TheWitness** [comment]
Well, is the Posix module available on Windows?  I think it is.

**Comment by TheWitness** [comment]
I'm looking now, and I'm shocked...  Checking.

**Comment by TheWitness** [comment]
We have a lot of posix_kill() through out many plugins.  We will have to handle this differently.  Truly shocked.  I don't use Windows any more, but I always thought it was there.  Maybe it was at some point, but was removed.

**Comment by TheWitness** [comment]
Okay, it's been this long.  Windows deprecated POSIX support in Windows 8 (which is unfortunate).  So, that explains some things.  I'm seeing some various hacks, but now I've got to audit the code.  Grumble....

**Comment by MSS970** [comment]
Can you list the files and related paths where posix_kill() or any posix function is use.
Much appreciated in advance.

**Comment by TheWitness** [comment]
Well, I did the audit last night.  We have a few things, that need to be addressed.

1) New posix_kill() wrapper function that supports signals 0 (is it running), SIGHUP, SIGTERM, and SIGKILL.
2) There are other posix functions that we use for things like lib/ping.php, but they are properly wrapped.

With the posix_kill, the signals mean essentially:

* 0 - Is the process still running
* SIGHUP - Send a signal to the pid that it needs to reload it's running configuration (FlowView supports this).
* SIGINT - Die Slowly
* SIGTERM - Die more quickly
* SIGKILL - Die not, no signal handlers allowed.

The COM module in Windows will support 0 and SIGINT/SIGTERM/SIGKILL, but I'm not sure how in Windows how you tell a pid to reload it's config.  Right now though, it's only FlowView.  So, since not too many people will run FlowView on Windows, I think we can ignore it.  Here are some nice wrapper functions from php.net.  Let me know what you think.

```php
function isRunning($pid) {
        $isRunning = false;
        if(strncasecmp(PHP_OS, "win", 3) == 0) {
            $out = [];
            exec("TASKLIST /FO LIST /FI \"PID eq $pid\"", $out);
            if(count($out) > 1) {
                $isRunning = true;
            }
        }
        elseif(posix_kill(intval($prevPid), 0)) {
            $isRunning = true;
        }
        return $isRunning;
}
```

```php
function win_kill($pid) {
    $wmi=new COM("winmgmts:{impersonationLevel=impersonate}!\\\\.\\root\\cimv2");

    $procs=$wmi->ExecQuery("SELECT * FROM Win32_Process WHERE ProcessId='".$pid."'");

    foreach($procs as $proc) {
      $proc->Terminate();
    }
}
```

I can not get CIM to work from Linux these days, Microsoft keeps breaking it by changing the acceptable bind methods and continually closing my Windows desktop firewall for WMI.  So, I've just given it up and pretty much abandoned the WMI plugin in Cacti sadly.  I'm not sure how much leg's it has in the Windows space in general now.  Maybe you can research that.

The `TASK*` functions likely won't die though like WMI.  So, maybe that's the way to go.

**Comment by TheWitness** [comment]
Sadly, the `pcntl_*` functions are not supported either.  The `pcntl_fork()` command is so useful in Linux, and simply just does not happen in Windows.  Back in 2003-2004 I had to do all sorts of hoops to make things parallel in Windows when it it just had `pcntl_fork()` it would have been a breeze.

**Comment by TheWitness** [comment]
Fixed this on 1.2.x branch.  I'll be in dev shortly.

**Comment by TheWitness** [comment]
Update to the latest develop.  Should be fixed now.

**Comment by MSS970** [comment]
Honestly, I am planning to install FlowView on Windows. I just downloaded it. Is there any advice?

**Comment by TheWitness** [comment]
@MSS970, Hehe, It's more about service control.  Do you have any MS Studio Experience to build a simple startup service?  You can also do it using the Windows COM module.  Let me get you the link.  I would want a pull request too.  The script in the service directory called 'flow_capture' has to be made into a Windows compatible service.

**Comment by TheWitness** [comment]
here is your guide.  I would expect a few changes to the flow-capture script.  They would include:

1. Change to the --help output to add --install --uninstall options
2. Use the instructions here: https://www.php.net/manual/en/win32service.examples.php to actually do the start/stop/install/uninstall steps.

In the 1.2.x version of Cacti, we use the following to determine Windows or non-Windows:

```php
if ($config['cacti_server_os'] == 'win32') {
   // Do something for Windows
} else {
   // Do something for any LINUX/UNNIX
}
```

Think you can tackle that?

**Comment by TheWitness** [comment]
Before you go too far, open a feature request under the FlowView issues list.
