### ISSUE TITLE
Can't delete data source. 

### ISSUE THREAD

**Issue by gamineiro** [Cacti/cacti#598]
When selected any data source, after delete option I received the message "You must select at least one data source."

Cacti 1.1.3

**Comment by cigamit** [comment]
Please check again.  In Cacti 1.x we will not allow you to delete a Data Source that is in use.  Likely what you did was select an in use Data Source, and then Delete followed by 'Go', which would result in this error.

**Comment by gamineiro** [comment]
Even excluding the graph, data source I can't can delete. How I can check if DS is in use? Sql command?

**Comment by cigamit** [comment]
There is a 'Deletable' column.

**Comment by peter-thoenen** [comment]
Same issue with 1.1.2 and noticed not in the release notes as a fix in 1.1.4.

Re: Comment the comment by cigamit I first "disabled" the source to see if that would help, same issue as described by initial poster.

The "Deletable" comment referenced in in last comment says "no".  I understand that prohibits me from deleting them, the question is (and to the OP point) they didn't use to be "no" (something changed between my 1.0 and 1.1.x update) so I do I get them back to "yes"

**Comment by cigamit** [comment]
If we re-introduce this delete Data Source, we would have to force delete Graphs, and since we can support multiple Graphs using the same Data Source it becomes difficult problematic.  This also includes Aggregates.

However, with that said, it can be a challenge to find the Graphs associated with a Data Source.  So, I'm debating re-introducing this.  There just would not be an option to leave a Graph alone.

**Comment by peter-thoenen** [comment]
I'm not against leaving it removed but then I think you should delete the "data graph list" entry from above so folk don't click it.  That or some how give some context / an error message on the "data source list" page when you go to "delete" don't just leave it gray with a delectable column "no", i.e. instead of making it "not selectable" [which confuses people] let them select and hit "delete" and then spit out an error that says something like "This data source is associated with an existing graph and cannot be deleted.  Please delete or unassociate this data source with the corresponding graph [via 'Graph List'] first"

**Comment by cigamit** [comment]
That should not be the case.  We now maintain one data source for all graph types.  So, once you create a graph for an interface, all the other graph types will use the same data source.  What version are you running, and it's it an upgrade or a new install?

**Comment by gvoitis** [comment]
Hello,

I have this issue, i cant data sources with no graph.

![screenshot_3](https://user-images.githubusercontent.com/42605037/44627463-22fb7380-a937-11e8-8049-e0c6f7b77700.jpg)
![screenshot_4](https://user-images.githubusercontent.com/42605037/44627464-22fb7380-a937-11e8-8c04-241e436e33ec.jpg)

--
Thank you,
Gabriel

**Comment by cigamit** [comment]
Okay, interesting.  Can you please dump your database and attach to this ticket?

**Comment by cigamit** [comment]
Optionally, email to developers at cacti dot net

**Comment by gvoitis** [comment]
Hello, i think i found a solution :) 
At least dont see anymore as an warning in logs, i disabled the IDs

**Comment by netniV** [comment]
@gvoitis if you can't send us the DB, we will close this issue as unverified.  It is likely something very specific with your data.

**Comment by cigamit** [comment]
We did have a re-index issue that was just fixed.  It won't undo any damage that was done, but this should not happen again.  So, closing.
