### ISSUE TITLE
Data source not displaying device name

### ISSUE THREAD

**Issue by neuraload** [Cacti/cacti#655]
Hello,

When clicking on a data source the device selection is blank even though  is it allocated to the correct device. It should display the current device as it was in the older Cacti versions.

<img width="1162" alt="screen shot 2017-05-05 at 17 55 09" src="https://cloud.githubusercontent.com/assets/2500116/25751003/3ffaaac6-31bc-11e7-8854-5f56a708c371.png">

Best regards,

**Comment by reboot1983** [comment]
@cigamit 
Although I'm unable to reproduce at my current develop or production environment, I've found the following at data_sources.php, line 778 and further.

```
if (get_request_var('host_id') > 0) {
	$value = db_fetch_cell_prepared('SELECT description 
		FROM host WHERE id = ?', 
		(isset_request_var('host_id') ? array(get_request_var('host_id')) : (isset($data_local['host_id']) ? array($data_local['host_id']):array(0))));
}else{
	$value = '';
}
```

The if statement suggest that the $value will only be set by the query if host_id is given in de URL; but the query has an inline-if-statement with also the possibility of getting the host_id out of $data_local (which will never be reached). Could this be the problem here?

**Comment by cigamit** [comment]
reboot, please do the optimization.  There was a wc3 optimization for a doubly defined 'host_id' post variable that introduced this bug.  Some of the old legacy Cacti form post magic gives me headaches.  This is one of them.  We need to avoid having multiple post ID's as it creates and array during the post variable.

So, more importantly, the real issue is in graphs_new.php that needs to be addressed.  You can review the revert and the initial commit in the graphs_new.php changelog.  We are reusing the same form, and in one version of the post, the 'host_id' variable appears twice (but likely in another form), and one was then optimized out.

Thinking about it more, since we were not seeing an array in the post, maybe the Firefox add-on htmlvalidator is the one with the bug here.  So, this may be a non-issue.  I won't be able to look into it until tomorrow though.
