### ISSUE TITLE
1.1.2 "ERROR: unknown option '--border'"

### ISSUE THREAD

**Issue by CLGREEN94** [Cacti/cacti#678]
Hello, 

my cacti just randomly decided to update its self without warning. and now all my graphs are saying. 
"ERROR: unknown option '--border'"

I have no idea what has happened or how to fix this. Could anyone help or point me in the right direction. 

I am now running Cacti 1.1.2 and Running CentOS 7. 

Thanks, 
Callum.

**Comment by kaf3773** [comment]
> my cacti just randomly decided to update its self without warning.

I wonder how the above is possible.

Anyway i think you are getting that error because of an older rrdtool and you need something >=1.4.

You can try this temporarily to see if the issue goes away. In ../lib/rrd.php line 2156 comment out the following

`           if (isset($rrdborder) && $rrdversion >= 1.4) {`
`                      $graph_opts .= "--border $rrdborder " ;`
`              }`

So you should have something like the below

`  //         if (isset($rrdborder) && $rrdversion >= 1.4) {`
`  //                    $graph_opts .= "--border $rrdborder " ;`
`  //            }`

**Comment by thurban** [comment]
A user with the same issue didn't have rrdtool 1.4 installed. 

http://forums.cacti.net/viewtopic.php?f=21&t=57437

**Comment by CLGREEN94** [comment]
Hi everyone, 

When Cacti updated for some odd reason it thought had RRDtool 1.6 when I logged on to the server I typed `rrdtool` and it told me the server was running. 

`RRDtool 1.3.8  Copyright 1997-2009 by Tobias Oetiker tobi@oetiker.ch`

Now when looking into this I did attempt to update RDDtool but the links on the RRDtool websites are broken and don’t resolve to a website anymore so It might be something the developer will have to look into. 
Anyways when poking around the setting section of my cacti in ‘Cacti Settings (General)’ I found at the bottom you can change the RDDtool version so I changed it from 1.6 to 1.3 and the graphs work again. 
Thanks for everyone’s help.

**Comment by cigamit** [comment]
Very odd.  Please pick a new system, and do a fresh install and see if cacti improperly detects 1.6.  If not, please close this issue.

**Comment by jayaich** [comment]
FYI - CentOS 7 (at the moment) will install cacti 1.1.2 and rrdtool 1.4.8 from the standard CentOS 7 repos. If you install something like 'yum-cron' then the system will update packages automatically when they are released (by CentOS). You can disable certain packages being automatically updated by modifying '/etc/yum.conf'. If you want to use cacti 1.1.6 then you can use the version from the epel-testing repo for CentOS 7. (I am currently using this, and it works fine.)

**Comment by cigamit** [comment]
Okay, so apparently this is a packaging issue.  I'm going to close then.
