### ISSUE TITLE
Sort order in Time Graph View

### ISSUE THREAD

**Issue by stalker37** [Cacti/cacti#680]
Sort order in  "Time Graph View" not eq to sort order in Data Source Profile.

In Data Source Profile rras sequence is:

Daily (5 Minute Average)
Hourly (1 Minute Average)
Weekly (30 Minute Average)
Monthly (2 Hour Average)
Yearly (1 Day Average)
![scr9](https://cloud.githubusercontent.com/assets/6966211/25918702/07feb3ca-35d5-11e7-8e22-7bd481a7bdbe.png)

But in view "Time graph View" sort order is

Daily (5 Minute Average)
Weekly (30 Minute Average)
Monthly (2 Hour Average)
Yearly (1 Day Average)
Hourly (1 Minute Average)
![scr10](https://cloud.githubusercontent.com/assets/6966211/25918764/3763a7e2-35d5-11e7-86b9-c603d4a4b2cb.png)

**Comment by stalker37** [comment]
Version is 1.1.3. updated from 0.8.x

**Comment by cigamit** [comment]
Resolved.  There are some out there who have steps == 1 for both 1 minute and 5 minute RRA's in their Upgrade Profile.  For those users, I recommend a custom script to remove either the 1 or 5 minute RRA from the Data Source Profile, and though it is possible, remove them from the RRDfiles.  It's not on the top of my list.  So, you won't see me writing it anytime soon, but possibly others may help there.

**Comment by gdsotirov** [comment]
The problem is not only with same values in column `data_source_profiles_rra.steps`. I have Cacti with pooler running every minute and so I have manually added "Hourly (1 Minute Average)" years ago. However, after upgrading to Cacti 1.0.6 I had the same problem of graphs sorting in Time Graph View hence I stumbled upon this issue. I found this into the database, which explains the  wrong "sort" order without explicit "ORDER BY" clause:

`mysql> select * from data_source_profiles_rra;`

id|data_source_profile_id|name|steps|rows|
--|----------------------|----|-----|----|
1|1|Daily (5 Minute Average)|**5**|25920|
2|1|Weekly (30 Minute Average)|30|9000|
3|1|Monthly (2 Hour Average)|120|2250|
4|1|Yearly (1 Day Average)|1440|797|
5|1|Hourly (1 Minute Average)|**1**|10080|

And it explains why I got Hourly at the end, but of course commit 40baee3 solves the problem until I upgrade to Cacti 1.1.x :-)
