### ISSUE TITLE
FATAL: You are not authorized to use this service

### ISSUE THREAD

**Issue by Zioool** [Cacti/cacti#738]
Hello,

Since a add a remote poller,i have noted the following issue :
When a device is selected to use a remote poller, the snmp informations from the top of the page are not anymore show. Instead an error message "FATAL: You are not authorized to use this service" is shown .
You can found an example in attachment.
Is it a bad configuration ? Or a bug ?
Regards,
Nicolas
![cacti](https://cloud.githubusercontent.com/assets/28760567/26398736/b1c895b0-407a-11e7-8d0c-f3a6a6281527.jpg)

**Comment by cigamit** [comment]
This is a setup problem.  You need to ensure that the hostname that is entered into the main poller when you edit it is resolvable by the remote pollers using either the address entered there, or the hostname.

So, goto the Data Collectors section, edit the Main Data Collector, and take the entry there, goto the remote poller, and ping using that address.  If it comes back 'unknown host', you have your solution.

Note, if there is a NAT involved, we will still be able to resolve since the header includes the originating IP address.  There have been requests to use a static token instead of the IP (since we already have a key-pair defined in Cacti), I just have not gotten around to it.

I hope this explains your issue more clearly.

**Comment by Zioool** [comment]
Hi,

Thanks for your quick reply. It was the main data collector which was stay
on localhost. As soon as i have edit it to the name of the server all was
working :D.

Regards,

Nicolas
