### ISSUE TITLE
Realtime don't stop remote poller when closed  realtime window or closed the botton

### ISSUE THREAD

**Issue by horizonlin** [Cacti/cacti#747]
version:1.1.6
nginx+php-fpm

Realtime don't stop remote poller server when closed  realtime window or closed the botton.  Any operation will not get response.  It will be normal after restart php-fpm service .

**Comment by cigamit** [comment]
That's actually not how it works.  What is happening is the remote data collector is not timing out.  Likely due to a device that is unavailable.  You will have to do some more debugging.

Goto line 47 in remote_agent.php and add the following: 

`ini_set('max_execution_time', '5');`

Let us know if the problem goes away.

**Comment by horizonlin** [comment]
Not work.    I think the problem is not timing out .  I try to log it ,  Then see the message  time after time.

**Comment by cigamit** [comment]
Please keep us posted.

**Comment by cigamit** [comment]
No update in a month.  Closing.
