### ISSUE TITLE
Update Password settings in Cacti New Install to NIST standards

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#752]
NIST Password Guidelines are changing and Cacti should update new installations to the new guidelines.

https://github.com/usnistgov/800-63-3

**Comment by paulgevers** [comment]
I was just looking into the fact that the /install/index.html web page isn't authenticated. Will/should that be part of the redesign?

For some background: in Debian I change the admin password to some random value and pass-by the install page, such that after installation, nobody but the administrator can log in and change things in the cacti database. Because of the changes in cacti 1.x I now need to figure out how to move forward. If the /install/index.html were behind password, I would have little issue with letting the administrator handle the final setup via the cacti web-page, but without it, I believe I have to work around this security issue.

**Comment by ronytomen** [comment]
Not related to this issue, loosely as security, this is just default settings change for new installs.

But to your point, yes the installation needs authentication.  As a work around, you can run the cli upgrade either automatically or prompt the user. You can then protect the installation directory from access except localhost.  

I have added an additional issue to address this concern:
https://github.com/Cacti/cacti/issues/809

**Comment by paulgevers** [comment]
@ronytomen thanks for responding. Regarding upgrades, this (running cli upgrade) is indeed what we do in Debian, but as far as I can tell that doesn't help for fresh installs. Thanks for creating #809.

**Comment by amprantino** [comment]
Configure apache to access install directory from specfic IP range.
Just delete the install directory after you had finished the upgrade procedure.

**Comment by netniV** [comment]
My thoughts on this are that the install folder is also used to perform upgrades currently.  A new install should probably allow unauthenticated access since the user would not necessarily know the admin credentials until logged in.  

However, upgrades should require an authenticated user with upgrade rights to make sure any issues are displayed to someone who knows what they are doing, not just the first authenticated user to come along who could even be a customer/client if the cacti system was opened to customers/clients.

**Comment by paulgevers** [comment]
@netniV I don't agree that the initial install should be unauthenticated. The admin could install the package and forget to go through the install pages (or even be beaten by somebody else). This would leave too much open in my opinion. More so for distributions where you can install Cacti as any other package. Of course those distributions should handle this appropriately (that is why I do that in Debian), but a unified experience makes things easier.

**Comment by netniV** [comment]
So I went and took a look at similar packages and there is a split between using the setup wizard without authentication and requiring a default username and password.  Since we do have the ability to run scripts via the poller etc, then I think it is something we should implement.

I also agree with the point that it prevents a  situation where someone who random accesses the system ends up becoming the system admin unless they know that default username and password combination.  It wouldn't take them too long to find though so it wouldn't be that much of a preventative.  

One side effect of that is this would mean you would need to disable the updating of the admin password (a minor change).  I can do some work to test the code in that situation as we are starting to get features in for 1.2.  Being a big change, it would be a good time to implement this.

**Comment by netniV** [comment]
So one of the things that we should be changing for NIST standards is that the maximum inactivity must force a logout.  To be able to use AAL2, we would have to allow authentication methods via 2FA methods such as Google Authenticator.

Auth Level | Active Logout | Inactive Logout
--- |  --- | ---
AAL1 | 30 days | 30 days
AAL2 | 12 hours | 30 minutes
AAL3 | 12 hours | 15 minutes

One of the other parts we should be introducing is a password meter to show the strength of a given password, plus block against commonly used and blacklisted passwords using something like https://www.jquerycards.com/forms/password/jquery-password-entropy/

From what I've read so far, simply storing an auth in a cookie does NOT count as a method of reauthentication pass the timings above.

**Comment by cigamit** [comment]
I suggest that we enhance our existing callback to include strength and blacklisted words.  We should not implement a JavaScript library as we are allowing customization from the authentication page.

**Comment by ronytomen** [comment]
Related to issue#1974

**Comment by TheWitness** [comment]
Right now, the default remember me is 30 days without activity.  I guess we should make it configurable too.
