### ISSUE TITLE
Installation should have authentication

### ISSUE THREAD

**Issue by ronytomen** [Cacti/cacti#809]
The installation section on new installs or upgrades should require authentication to enter.  Only allow "admin" level users to login and perform upgrade.

**Comment by netniV** [comment]
This has now been implemented in the new 1.2 installer.  I have mentioned about this to @paulgevers for the Debian packages, but I guess we should also reach out to the other package maintainers to ask them to test this once it becomes integrated into the main develop (1.2) branch.

Since the default password when installing from GitHub will be the one set by the cacti.sql source when imported to the database, @paulgevers normally overrides this.  I think that a "distribution" based message should be added to the login screen until the first user has actually logged in.  The same file simply be replaced by the maintainers if we decided to also set one for GitHub users.
