### ISSUE TITLE
ss_host_disk.php not calculating Total Disk Space for large disks

### ISSUE THREAD

**Issue by hackdefendr** [Cacti/cacti#824]
This issue occurred way back in Cacti v0.87 as discussed here:  [http://forums.cacti.net/viewtopic.php?f=21&t=28713](url)

Problem:  Disks/Partitions larger than 8TB won't graph Total Disk Space properly.

Why was the fixed version of ss_host_disk.php rolled back to older code?

JS

**Comment by hackdefendr** [comment]
Any updates on this?

I have several partitions that are greater than 8 Terabytes and cannot graph them using the current ss_host_disk.php script.

**Comment by cigamit** [comment]
If you can create a pull request that corrects this, we will commit.  I was unaware that this change did not make it into the mainline.  I think it's there.  Again, the best thing for you to do is create a pull request with your updates.

**Comment by hackdefendr** [comment]
Problem is I didn't write the fixed code from the forum post linked above. So I wouldn't be able to create a pull request.

**Comment by hackdefendr** [comment]
Why is this unverified....is it because no one has a disk/partition greater than 8 terabyte to test with?  Because I do, and its verified that my 17 Tb partition only graphs to 8 Tb.

**Comment by cigamit** [comment]
I am suggesting if you want this fixed that you should learn to create a pull request with the fix.  This project relies on people who are able to contribute their work, and in this case a fix, to the project.  You will note, if you search GitHub, we have now over two dozen contributors since moving there.  Bottom line, you have the problem, fix it, and do a pull request.  You are half way there in that you have a GitHub account.

**Comment by hackdefendr** [comment]
The only thing I would be able to do is take the patched file from that forum post and have you pull that from me. Other than that I am not proficient in PHP enough to fix this.

**Comment by cigamit** [comment]
Please test with the latest ss_host_disk.php and let me know if it helps.

**Comment by hackdefendr** [comment]
Ok I tried the new script...deleted old graphs and created new ones based on the new script.  I still am only showing 8 Terabytes for a 17 Tb partition. Something tells me this has to do with HOST-RESOURCES-MIB not supporting 64 bit systems...which apparently was implemented in net-snmp v5.5, which I am using.

**Comment by cigamit** [comment]
Please run the following command, and post your output:

`snmpwalk -c yourcommunity -v2c youhostname | grep HOST-RESOURCES | grep hrStorage`

Post the output.

**Comment by hackdefendr** [comment]
Here is the output from snmpwalk:

HOST-RESOURCES-MIB::hrStorageIndex.1 = INTEGER: 1
HOST-RESOURCES-MIB::hrStorageIndex.3 = INTEGER: 3
HOST-RESOURCES-MIB::hrStorageIndex.6 = INTEGER: 6
HOST-RESOURCES-MIB::hrStorageIndex.7 = INTEGER: 7
HOST-RESOURCES-MIB::hrStorageIndex.10 = INTEGER: 10
HOST-RESOURCES-MIB::hrStorageIndex.31 = INTEGER: 31
HOST-RESOURCES-MIB::hrStorageIndex.35 = INTEGER: 35
HOST-RESOURCES-MIB::hrStorageIndex.36 = INTEGER: 36
HOST-RESOURCES-MIB::hrStorageIndex.37 = INTEGER: 37
HOST-RESOURCES-MIB::hrStorageIndex.38 = INTEGER: 38
HOST-RESOURCES-MIB::hrStorageIndex.39 = INTEGER: 39
HOST-RESOURCES-MIB::hrStorageIndex.40 = INTEGER: 40
HOST-RESOURCES-MIB::hrStorageIndex.41 = INTEGER: 41
HOST-RESOURCES-MIB::hrStorageType.1 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.3 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.6 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.7 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.10 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.31 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.35 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.36 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.37 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.38 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.39 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.40 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.41 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: Physical memory
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual memory
HOST-RESOURCES-MIB::hrStorageDescr.6 = STRING: Memory buffers
HOST-RESOURCES-MIB::hrStorageDescr.7 = STRING: Cached memory
HOST-RESOURCES-MIB::hrStorageDescr.10 = STRING: Swap space
HOST-RESOURCES-MIB::hrStorageDescr.31 = STRING: /
HOST-RESOURCES-MIB::hrStorageDescr.35 = STRING: /dev/shm
HOST-RESOURCES-MIB::hrStorageDescr.36 = STRING: /boot
HOST-RESOURCES-MIB::hrStorageDescr.37 = STRING: /export
HOST-RESOURCES-MIB::hrStorageDescr.38 = STRING: /home
HOST-RESOURCES-MIB::hrStorageDescr.39 = STRING: /tmp
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: /archive
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: /opt/arcsight
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.3 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.6 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.7 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.10 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.31 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.35 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.36 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.37 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.38 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.39 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.40 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.41 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageSize.1 = INTEGER: 529261516
HOST-RESOURCES-MIB::hrStorageSize.3 = INTEGER: 553837512
HOST-RESOURCES-MIB::hrStorageSize.6 = INTEGER: 529261516
HOST-RESOURCES-MIB::hrStorageSize.7 = INTEGER: 188763752
HOST-RESOURCES-MIB::hrStorageSize.10 = INTEGER: 24575996
HOST-RESOURCES-MIB::hrStorageSize.31 = INTEGER: 74521776
HOST-RESOURCES-MIB::hrStorageSize.35 = INTEGER: 66157689
HOST-RESOURCES-MIB::hrStorageSize.36 = INTEGER: 487652
HOST-RESOURCES-MIB::hrStorageSize.37 = INTEGER: 2491020
HOST-RESOURCES-MIB::hrStorageSize.38 = INTEGER: 12570289
HOST-RESOURCES-MIB::hrStorageSize.39 = INTEGER: 66157689
HOST-RESOURCES-MIB::hrStorageSize.40 = INTEGER: 735328280
HOST-RESOURCES-MIB::hrStorageSize.41 = INTEGER: 2146371072
HOST-RESOURCES-MIB::hrStorageUsed.1 = INTEGER: 213763592
HOST-RESOURCES-MIB::hrStorageUsed.3 = INTEGER: 213763592
HOST-RESOURCES-MIB::hrStorageUsed.6 = INTEGER: 174576
HOST-RESOURCES-MIB::hrStorageUsed.7 = INTEGER: 188763752
HOST-RESOURCES-MIB::hrStorageUsed.10 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.31 = INTEGER: 596394
HOST-RESOURCES-MIB::hrStorageUsed.35 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.36 = INTEGER: 118109
HOST-RESOURCES-MIB::hrStorageUsed.37 = INTEGER: 5631
HOST-RESOURCES-MIB::hrStorageUsed.38 = INTEGER: 13371
HOST-RESOURCES-MIB::hrStorageUsed.39 = INTEGER: 40
HOST-RESOURCES-MIB::hrStorageUsed.40 = INTEGER: 69310483
HOST-RESOURCES-MIB::hrStorageUsed.41 = INTEGER: 7386277

**Comment by cigamit** [comment]
So, here is the issue, /opt/arcsight has a hrStorageSize of 2146371072 and a hrStorageAllocationUnits of 4096.  No way to fix that one with your current setup.  It's going to report at ~8TB.  What is the snmpd version on the system that you are querying?  If you say it was fixed in Net-SNMP 5.5, you may have to trigger a configure flag to allow the INTEGER type be 64bit signed vs. 32bit signed (which, by default, it is today).  That would also apply for the snmpwalk command.

In a corner case like this also, you should ensure that you are not using the php-snmp module, but the Net-SNMP binaries for collecting that snmp information.  I'm not certain what spine will do.  My guess is that if the Net-SNMP API is built for 64bit signed integers, then spine will leverage them.  This all adds up to building Net-SNMP on your own.

Also, if you are currently getting the Net-SNMP packages from package maintainers, logging a bug that the integer types are being build as 32bit signed, and should be built as 64bit signed.  If that's the case, your bug report to the package maintainers WILL BE VERY IMPORTANT TO THE COMMUNITY AS WELL.

Keep us posted on your efforts, and thanks for your contribution, though, now that I see the problem, I will back out the changes.

**Comment by hackdefendr** [comment]
I was afraid you would say that... :^)

OK...I will start by trying to compile net-snmp from scratch to be sure when I open a bug with Redhat I have all my ducks in a row.

Thanks for the help.

**Comment by cigamit** [comment]
By the way, the other solution (one of my NAS volumes is quite large) and the daemon is 5.7.3, is to report the hrStorageAllocationUnits to a false number (larger that it really is), so that the hrStorageSize does not overflow.  I think that this might already be implemented in Net-SNMP 5.7.3 as a hack/workaround.  Test with that first.  If you can get the agent to report back an hrStorageAllocationUnit of greater than 4096, you will be out of the woods.

BTW, I was looking for a compiler flag for 64bit signed integers on 5.7.3, still looking....  The aforementioned 'hack' may be your only option (again I'm making assumptions).

**Comment by cigamit** [comment]
It's going to have to be the hack as I just reviewed the HOST-RESOURCES-MIB snmp agent file and the type is defined as Integer32, which means that if the agent is smart, it will falsely increase the hrStorageAllocationUnit to a larger value when there is an overflow condition.

**Comment by hackdefendr** [comment]
OK I compiled net-snmp v5.7.3 but its still showing the same numbers.  Not sure what you meant by hack/workaround -- is this something I could search for? Is it something I have to change in the code before compiling?

Also note that I am not seeing an overflow in my snmpwalk output...doesn't those show up with a Minus in front of the number?

**Comment by cigamit** [comment]
Well, you should open a ticket with RedHat.  So, if I were to write pseudocode, It would look something like the following:

`hrStorageAllocationUnits = something;
while (true) {
  if (hrStorageSize > 32bit signed integer) {
    hrStorageSize = hrStorageSize / 2;
    hrStorageAllocationUnits = hrStorageAllocationUnits * 2;
  } else {
     break;
  }
}`

RedHat can pass that pseudocode along to the Net-SNMP team, and they know where to make the change, and how to make it properly.

**Comment by cigamit** [comment]
Just want to let you know, I found a snmpd.conf option:

`realStorageUnits 0`

Using that option will allow Net-SNMP to adjust the storage allocation units which will allow you to properly report real big disks now.  You should enable it on your 'real big' storage server.

**Comment by hackdefendr** [comment]
Excellent! Thank-you!
