### ISSUE TITLE
CMDPHP PHP ERROR NOTICE Backtrace

### ISSUE THREAD

**Issue by itsjoke** [Cacti/cacti#825]
I have a new install of Cacti.I found `Cacti.log` have too many error When I `Apply Thresholds`.

My Cacti Version  is 1.1.10 ,OS is CentOS Linux release 7.3.1611 (Core),PHP Version is 7.1.5.

```
2017/06/23 16:08:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 716 api_plugin_hook)(/lib/plugins.php: 69 api_plugin_run_plugin_hook)(/lib/plugins.php: 162 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 2049 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/23 16:08:54 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: local_data_id in file: /home/cacti/plugins/thold/thold_functions.php on line: 2049
2017/06/23 16:06:04 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 597 api_plugin_hook)(/lib/plugins.php: 69 api_plugin_run_plugin_hook)(/lib/plugins.php: 162 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 2049 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
```

BR,
David

**Comment by itsjoke** [comment]
```
2017/06/23 16:13:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php: 39 clog_view_logfile)(/lib/clog_webapi.php: 130 general_header)(/lib/functions.php: 3404 include)(/include/top_general_header.php: 96 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/23 16:13:19 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
2017/06/23 16:13:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/clog.php: 39 clog_view_logfile)(/lib/clog_webapi.php: 130 general_header)(/lib/functions.php: 3404 include)(/include/top_general_header.php: 32 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/23 16:13:19 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
```

**Comment by itsjoke** [comment]
How can I fix the issue?
Is somebody here?
```
2017/06/26 17:25:59 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php: 313 grow_right_pane_tree)(/lib/html_tree.php: 924 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/26 17:25:59 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
2017/06/26 17:25:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php: 186 top_graph_header)(/lib/functions.php: 3397 include)(/include/top_graph_header.php: 130 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/26 17:25:57 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
2017/06/26 17:25:57 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph_view.php: 186 top_graph_header)(/lib/functions.php: 3397 include)(/include/top_graph_header.php: 63 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/26 17:25:57 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
2017/06/26 17:25:49 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/syslog/syslog.php: 85 general_header)(/lib/functions.php: 3404 include)(/include/top_general_header.php: 96 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/26 17:25:49 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
2017/06/26 17:25:49 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/syslog/syslog.php: 85 general_header)(/lib/functions.php: 3404 include)(/include/top_general_header.php: 32 draw_navigation_text)(/lib/functions.php: 2783 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/26 17:25:49 - ERROR PHP NOTICE: Array to string conversion in file: /home/cacti/lib/functions.php on line: 2783
```

**Comment by cigamit** [comment]
Well, these are what appear to be plugin issues.  The first post is an issue with thold that I will be addressing soon.  The second seems related to syslog.  If you could open these issues in the plugins section, I would appreciate it.

**Comment by tddcacti** [comment]
Was the thold issue ever resolved?  I'm experiencing the same problem and found this thread, not able to find if it was ever opened in the plugins section per cigamit's request.

In my case this issue started when I went to use a time based threshold for the first time.  Looking at line 2049 in thold_functions.php and working my way backwards in the code, I see that $local_data_id is indeed never defined within the function thold_check_threshold.

To fix this I simply added the following on line 1569, just below a similar definition for $local_graph_id:

$local_data_id = $thold_data['local_data_id'];

This seems to be working for me.  I checked the latest code for thold_functions.php, and unless I missed it, I'm still not seeing this fix in the latest file.

To give a bit more background for anyone who might be seeing this problem: I noticed two unexpected behaviors after enabling a time based threshold (set to 5 triggers in one hour).  The first unexpected behavior was that I would receive a Resolved / Normal alert after just one trigger event--I didn't expect this to happen, since there had not been 5 trigger events and also I never received the alert email.

The second behavior was on a graph where the threshold was breached and stayed breached--I expected to receive the alert email after 5 polling cycles, but it never came.  

In troubleshooting both of these things I found that the fact that $local_data_id is undefined causes $step to become blank in line 2049, which cascades and causes the logic further down to fail to increment $failures correctly--it would only ever get to 1, and then back to zero when the threshold breach cleared.

**Comment by netniV** [comment]
Can you create a pull request for your change?

**Comment by netniV** [comment]
Also, can you open this as a new issue on the thold issues list, or add it to https://github.com/Cacti/plugin_thold/issues/174#issuecomment-372652670

**Comment by tddcacti** [comment]
Thanks, issue 174 looks to be the same issue, so I've added this as a comment there.

I've not created a pull request before, but I can try to figure it out if you need me to do that.

**Comment by netniV** [comment]
I was about to iterate what I normally do about closing this issue but it's already closed so will continue discussions on the other issue thread.
