### ISSUE TITLE
Unable to delete a datasource->Console->Devices-Device name->Data Source List

### ISSUE THREAD

**Issue by ikorzha** [Cacti/cacti#859]
In Latest Github Cacti I have discovered an issue that I'm unable to delete a data source.

Console->Devices-Device->Device name->Data Source List -> (Put a checkmark on interface to be deleted)  -> Choose Action Delete.   ALL interfaces become Grayed OUT and no delete can be executed.
Screenshot attached:
![unable-to-delete](https://user-images.githubusercontent.com/11211789/28214952-46b0c0c2-687a-11e7-94fe-95ff54c669f2.jpg)

**Comment by cigamit** [comment]
Not a bug.  You see that column where it says "Deletable" and has "No" for the value?  That means its not deletable because a graph depends on it.  If you have to delete the graph instead and have it remove the data source with it.

**Comment by ikorzha** [comment]
Thank you for clarification and sorry that I reported false positive..

**Comment by browniebraun** [comment]
We don't allow you to remove Data Sources that are in use.  Delete the graphs instead.  I would consider 're-enabling' this, but it 'might' break graphs.
I guess we could instead of deleting the graphs, remove the data sources from them.  Might be catastrophic too.
The easy thing was to simply deny removal of data sources till they are not in use.
This is due to the fact that we do not duplicate data sources any longer.  If you create, for example, a 64bit Bytes per second, and a 64bit Bits per second graph, they both use the same Data Source.
