### ISSUE TITLE
cacti version 1.1.16 graphing issue

### ISSUE THREAD

**Issue by abouhamadelias** [Cacti/cacti#905]
Please note that we have installed cacti version 1.1.16 using yum command (the default setup) on centos7 centos-release-7-3.1611.el7.centos.x86_64.
We are using poller spine and all RRDs are working normally.

Case1: when we enabled the Structured RRD path in the data storage settings, the RRD were created but the system is not drawing graphs.
Below error detected in var/log/messages when the Structured RRd  path is enabled

“Aug 14 10:58:08 cacti httpd: ERROR: opening '/usr/share/cacti/rra/bsalim-juniper_m10i_traffic_in_453.rrd': Permission denied

Case2: we re-installed cacti from scratch, without enabling the “Structured RRd path”. Thus we need to enable the “On-demand RRD update”.
Everything was working normally except when we zoom into the graph the new data are not being drawn.

Please advise.
Regards

**Comment by cigamit** [comment]
Did you run the structure_rra_paths.php.  That's a requirement when you have an existing system and then go to structure paths.

**Comment by abouhamadelias** [comment]
yes , when i run the script the files onwer has been change from cacti/cacti to cacti/root. but the problem is still not solved. in addition every new rrd is created under cacti/cacti. 
the solution you proposed didn't solve case 2 also

**Comment by abouhamadelias** [comment]
![image](https://user-images.githubusercontent.com/22761985/29353413-b67b228c-8272-11e7-849b-03531c544f48.png)

**Comment by cigamit** [comment]
For the permission issue, you have to set a sticky bit on the group permissions so that all files can be updated by the crontab process, and the web browser.  There are several examples on the forums as to how to do that.

On the second issue, I suspect that you have an issue with the permissions of the realtime cache directory which is under `<path_cacti>/cache`, that directory needs to be writable by the Web account.  If you have SELinux installed, you may have to setup some more rules.  Since this sounds like more of a support issue at this point, I will close this issue.
