### ISSUE TITLE
Wiki Formatting?

### ISSUE THREAD

**Issue by jpartain89** [Cacti/cacti#924]
What language are the wiki pages supposed to be coded in.... 

Because there's a ton of `//` items and `;` at the beginning of lines.... 

These don't exactly make sense, especially if you're trying to use MarkDown, as other parts of the docs ARE appropriately using... 

If there is a need to change the Wiki pages/Documentation to a specific language, I'd be more than happy to help, but in need of a singular language/format.

**Comment by cigamit** [comment]
Thanks.  We are currently reviewing the whole Wiki/Documentation effort.

**Comment by cigamit** [comment]
Can you post a few links of those pages?

**Comment by devsibwarra** [comment]
@cigamit https://github.com/Cacti/cacti/wiki/Linux-Installation is one example.  Looks like a spliced mix of MediaWiki and MarkDown was used on that page

**Comment by cigamit** [comment]
Okay, noted.  Right now we are working on a refresh to the documentation plan.  We have created a documentation repository, and we will be breaking the rather large manual.md into categories that can be displayed in the various GUI sections of Cacti.

For example, we will have a documentation section on Presets, Presets > VDEF, Presets > Colors, Presets > GPrint Presets, Presets > Data Source Profiles, etc.

If you have suggestions for Chapters, we would welcome them.  Pull requests there are also welcomed.  My first thought would to be to align the markdown files similar to how our HTML documentation reads, but to add these various sections so that we can link to them inside the GUI.

**Comment by jpobeda** [comment]
Whatever you device, please do it thinking on multi language so people can help with translations in the future.

**Comment by cigamit** [comment]
Tony would like help first updating the documentation in English, then we will create independent language directories such as 'en', etc.  He please use the Wiki on the documentation repo to share thoughts on chapters.  Then, if you can help with English first, we will then move to other languages.

Pull requests will be the way we take updates as with everything else.

**Comment by jpobeda** [comment]
I'm happy to help.

**Comment by ronytomen** [comment]
Good to know!

I'm going to move this issue to the documentation repository.

**Comment by ronytomen** [comment]
Ok, I can't move issues.. lol

It will stay here to remind me.

**Comment by netniV** [comment]
We can't move this issue, but I have recreated it as https://github.com/Cacti/documentation/issues/4
