### ISSUE TITLE
Hyperlinks for Data Profile stats

### ISSUE THREAD

**Issue by eschoeller** [Cacti/cacti#981]
I would like to request that the "Data Sources Using" and "Templates Using" stats in the Data Source Profile display become hyperlinks that produce a listing of the individual data sources or templates using these profiles. As you can see from the screenshot I have 2 templates using some strange data source profile ... but I have no idea what they are - so no way to trace back and figure out how to fix them.

![screenshot_2017-09-17_18-01-12](https://user-images.githubusercontent.com/12864741/30526130-c56f9740-9bd2-11e7-86e7-5aed00f8f936.png)

**Comment by eschoeller** [comment]
I suppose by going to Templates/Data Source you can see the "Profile Name" and sort by that. And then from there you can trace back to what graphs are using it. So perhaps this isn't really necessary. Let me know what you think.

**Comment by cigamit** [comment]
I think it's a great idea.  We have not been making much progress on 1.2 since we keep getting little bugs in the 1.1.x branch.  This one, along with being able to pick the profile for Data Queries should be done together.

This is not a huge change in itself, and will likely be done in the feature-1.2 branch pretty quickly, but 1.2 likely will not be out before November.  Patching won't be a big deal if you need it before release.

**Comment by cigamit** [comment]
Resolved.

**Comment by eschoeller** [comment]
Sorry for the late reply. I upgraded and tested. This looks great, and I very much appreciate the addition!
